### ISSUE TITLE
Importing a variable with missing values but no labels

### ISSUE THREAD

**Issue by larmarange** [tidyverse/haven#219]
In SPSS, you could have a variable with defined missing values but no value label. In such case, `read_spss` is producing a vector with a structure like:

``` r
> x <- structure(c(1.2, 2.4), class = c("labelled_spss", "labelled"), na_values = 9)
```

If  it's working with `print`, there is a bug when using `summary`:

``` r
> x
<Labelled SPSS double>
[1] 1.2 2.4
Missing values: 9
> summary(x)
Error: `x` and `labels` must be same type
```

In fact, as currently written, `labelled_spss` format doesn't allow a vector with no value labels.

``` r
> labelled_spss(c(1.2, 2.4), NULL, na_values = 9)
Error: `x` and `labels` must be same type 
```

**Comment by hadley** [comment]
I think there are two problems here:

```R
# First, you should be able to create a labelled spss vector with no labels
# (That's a bit inelegant but it's expedient)
labelled_spss(c(1.2, 2.4), na_values = 9)
labelled_spss(c(1.2, 2.4), double(), na_values = 9)

# Also need to make sure the C++ code returns an object with that structure

# Second you should be able to subset that object
# (That's the root cause of the summary failure)
x <- structure(c(1.2, 2.4), class = c("labelled_spss", "labelled"), na_values = 9)
x[1]
```

Would you mind providing an SPSS file that contains that variable so I can test?

**Comment by hadley** [comment]
@larmarange do you still have any interest in this issue?

**Comment by huftis** [comment]
I’m not the original submitter, but here’s an example SPSS file as requested, @hadley:
[missing-no-label.zip](https://github.com/tidyverse/haven/files/1942576/missing-no-label.zip)

Example code to trigger the error message:

```r
library(haven)
d <- read_sav("https://github.com/tidyverse/haven/files/1942576/missing-no-label.zip", user_na = TRUE)
summary(d$x)
#> Error: `x` and `labels` must be same type
```

**Comment by dusadrian** [comment]
I was recently thinking about a similar example, and concluded it simply does not make any sense to have a declared missing value with no label. This would be similar to a general NA in R.
How about using the value itself as a label?
Something like:

`x <- structure(c(1.2, 2.4), class = c("labelled_spss", "labelled"), labels = c("9" = 9), na_values = 9)`

Something like that could be done at import time.

**Comment by hadley** [comment]
Reprex with built-in dataset:

``` r
library(haven)
sav <- system.file("files", "testdata.sav", package = "foreign")
x <- read_spss(file = sav, user_na = TRUE)

x$numeric_long_label
#> <Labelled SPSS double>
#> [1] 1.00000 2.00000 3.33333 4.00000      NA
#> Missing range:  [1, 2]
x$numeric_long_label[1:3]
#> Error: `x` and `labels` must be same type
```

<sup>Created on 2019-01-23 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1.9000)</sup>
