### ISSUE TITLE
SPSS system missings read as NaN

### ISSUE THREAD

**Issue by wepelham3** [tidyverse/haven#223]
After installing the v1.0.0 update I noticed a bunch of `NaN`s in datasets I have been importing to R from SPSS using `read_sav()`.

It appears that the `.` or system missing values in my `.sav` files are now being read into R as `NaN` rather than `NA`.

Here is a [dataset](https://github.com/tidyverse/haven/files/503434/data.zip) with just one variable to illustrate the issue.

This variable has 12 missing values in the `.sav` file, and when imported with haven v0.2.0 we see 12 `NA`s in R.  Then when imported with haven v1.0.0 we see 12 `NaN`s in R.

Here is code to reproduce the issue with that dataset:

```
remove.packages("haven")

# with v0.2.0 the 12 missing values are read in as NA
devtools::install_version("haven", version = "0.2.0", repos = "http://cran.us.r-project.org")
data <- haven::read_sav("data.sav")
table(data$var1, useNA = "always")

remove.packages("haven")

# with v1.0.0 the 12 missing values are read in as NaN
install.packages("haven") # v1.0.0
data <- haven::read_sav("data.sav")
table(data$var1, useNA = "always")
```

**Comment by evanmiller** [comment]
@hadley I think you meant to close #233 (this one should be re-opened).

**Comment by hadley** [comment]
@evanmiller grrr, oops

**Comment by jrosen48** [comment]
Has there been an update to this? Same issue. Makes working with `.sav` files hard(er) to use - they're no fun to begin with!

**Comment by pkq** [comment]
I'd love to see a fix for this as well. 

@jrosen48, the best workaround I've found so far is this one-liner to change all `NaN`s to `NA` after importing (assuming a datafile named df):

`df[df == "NaN"] <- NA`

**Comment by hadley** [comment]
@pkg I think that should be `df[is.nan(df)] <- NA`

**Comment by pkq** [comment]
That gives me an error message:

`Error in is.nan(df) : 
  default method not implemented for type 'list'`

All of the columns imported using `read_sav` are atomic. Is haven actually setting the value to the character string "NaN"?

**Comment by hadley** [comment]
Oh I just assumed that `is.nan()` worked the same way as `is.na()`, but it doesn't. Grrr. 

This does work:

```R
mtcars[sapply(mtcars, is.na)] <- NA
```

**Comment by pkq** [comment]
Interesting. You can convert from `NA` to `NaN` using `df[is.na(df)] <- NaN`, but not from `NaN` to `NA` using `df[is.nan(df)] <- NA`.

@hadley: Any idea what caused the change in behavior from [v0.2.1](https://github.com/tidyverse/haven/releases/tag/v0.2.1) to [v1.0.0](https://github.com/tidyverse/haven/releases/tag/v1.0.0)? Is this an issue with haven or [ReadStat](https://github.com/WizardMac/ReadStat)?

**Comment by hadley** [comment]
@pkq no, but I doubt it will be hard to find/fix when I look at haven again.

**Comment by pkq** [comment]
Sounds good, I'll try to be patient. haven & the tidy verse have changed my life!

**Comment by hadley** [comment]
Could someone please provide a minimal reprex that I can use to test?

**Comment by pkq** [comment]
I think this should work. I had some trouble getting the install/loading sequence automated, but it passed [reprex](https://github.com/jennybc/reprex), so I think it gives you what you need. Let me know if you have any questions!

```
# with v0.2.1 missing values are correctly written & read as NA
if (require("haven")) remove.packages("haven")
devtools::install_github("tidyverse/haven@v0.2.1")
df <- tibble::tibble(x = c(1, 2, NA, 4, NA))
tempfile <- tempfile(fileext = ".sav")
write_sav(df, tempfile)

works <- read_sav(tempfile)
table(works$x, useNA = "always")

# with v1.0.0 missing values are incorrectly read as NaN
detach("package:haven", unload=TRUE)
if (require("haven")) remove.packages("haven")
devtools::install_github("tidyverse/haven@v1.0.0")

fails <- read_sav(tempfile)
table(fails$x, useNA = "always")
```

**Comment by skanskan** [comment]
@pkg Then we just need to use haven 2.1?
Or also need to do anything else when reading the data? such as using tibble.

**Comment by hadley** [comment]
I've cleaned up the issue title/comment thread to focus on key components of problem. Thanks for the correspondence so far :smile:

**Comment by hadley** [comment]
@pkg unless I specifically ask for it, there's no reason to include code that works in a reprex. I've cleaned up your reprex for you

**Comment by pkq** [comment]
Much appreciated!

**Comment by pkq** [comment]
Awesome, thanks @hadley!

**Comment by Keniajin** [comment]
realised the same issue with `read_dta()`

**Comment by eivindhammers** [comment]
@Keniajin +1

**Comment by tomhopper** [comment]
@Keniajin +1

`unloadNamespace("haven")
devtools::dev_mode(on = TRUE)
devtools::install_version("haven", version = "0.2.0", repos = "http://cran.us.r-project.org")
library(haven)
packageVersion("haven")
# returns '0.2.0'
states_df <- read_dta(path = "dataSets/states.dta")
states_df
# Shows NA in row 9 and elsewhere that should be NA
devtools::dev_mode(on = FALSE)
unloadNamespace("haven")

library(haven)
packageVersion("haven")
# returns '1.0.0'
states_df <- read_dta(file = "dataSets/states.dta")
states_df
# Shows NaN in row 9 and elsewhere that should be NA
unloadNamespace("haven")
`

[states.dta.zip](https://github.com/tidyverse/haven/files/1030797/states.dta.zip)

**Comment by borisma** [comment]
Hello! I would like to ask when the `haven` CRAN version will be updated? We are using `haven` for introductory psychology stats and first year students do not usually install from github. We can't use `haven` properly as long as the CRAN version imports missings as `NaN`. Thanks!

**Comment by hadley** [comment]
I'll add a release to my to do list. Looking at the news, I think it should be straightforward so will hopefully happen next week.

**Comment by borisma** [comment]
Thanks very much!
