### ISSUE TITLE
Misreading SAS data

### ISSUE THREAD

**Issue by alawami** [tidyverse/haven#225]
I tried using haven (because I had the similar problem with sas7bdat package before it) to read the following data:

ftp://nhtsa.gov/NASS/2014/Formatted%20Data/gv.sas7bdat

It reads the variable 'ALCTEST' (third column) for example as a double. So in SAS I see the data starts as:

C,C,C,C,0,C,C,C,... 

But in R, haven is reading it as:

NA, NA, NA, NA, 0, NA, NA, NA, ...

**Comment by hadley** [comment]
@evanmiller any ideas on this one

**Comment by evanmiller** [comment]
This is a tagged missing, yeah? Does haven display the tag or `NA`?

**Comment by alawami** [comment]
haven displays NA. It is tagged missing. For this particular variable there
are 5 different missing tags, which haven displays all as NA.

**Comment by hadley** [comment]
@alawami you need to use `na_tag()` to extract the values

```R
tmp <- tempfile()
download.file("ftp://nhtsa.gov/NASS/2014/Formatted%20Data/gv.sas7bdat", tmp)

x <- read_sas(tmp)$ALCTEST
na_tag(x)
```

I'd recommend reading http://haven.tidyverse.org/articles/semantics.html#missing-values
