### ISSUE TITLE
write_sav() - Invalid SPSS file with string length 255

### ISSUE THREAD

**Issue by BurninLeo** [tidyverse/haven#226]
Haven:write_sav() will produce invalid SPSS files under some circumstances. Here's an example that won't work with SPSS v23. It seems an issue with string that are exactly 255 characters long.

    df = data.frame(row.names = c("1","2"))
    df$A = 1
    df$B = ""
    df["2","B"] = "123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789|123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789|1234567890123456789012345678901234567890123456789|12345"
    library(haven)
    write_sav(df, "test.sav")

R version 3.2.4 Revised (2016-03-16 r70336)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows >= 8 x64 (build 9200)
Package: haven_1.0.0
SPSS 23.0.0.0 (64bit) in unicode mode

Resulting SPSS file:
[test.zip](https://github.com/tidyverse/haven/files/538807/test.zip)

**Comment by evanmiller** [comment]
Hi, I can confirm the issue. I will post here when a fix is available.

**Comment by evanmiller** [comment]
@hadley This is fixed here: https://github.com/WizardMac/ReadStat/commit/e4b4c1bcd36e629a42201b4d37f0308690d58624
