### ISSUE TITLE
Encoding

### ISSUE THREAD

**Issue by marciz** [tidyverse/haven#231]
SAS:

> Libname my_lib _'path to iris data'_;
> 
> Data iris(encoding = "wbaltic");
> Set my_lib.iris;
> Run;

R:

> My_dt <- read_sas(_path_, encoding = 'wbaltic')

Unsupported character set code: 67
Error in eval...

**Comment by evanmiller** [comment]
@hadley this is fixed here: https://github.com/WizardMac/ReadStat/commit/ae79755f77cd8eed59aaf46b152a23e1fa2c0024
