### ISSUE TITLE
Misreading SAS transport files

### ISSUE THREAD

**Issue by karldw** [tidyverse/haven#233]
I'm excited that `haven` now supports SAS transport files!  I'd like to read data from the [Medical Expenditure Panel Survey](https://meps.ahrq.gov/mepsweb/data_stats/download_data_files_detail.jsp?cboPufNumber=HC-172).  Using `haven::read_xpt` gives incorrect results, while `foreign::read.xport` seems valid.

An example:
```r
library(haven)
library(foreign)
library(dplyr)
# Download MEPS dataset:
download.file('https://meps.ahrq.gov/mepsweb/data_files/pufs/h172ssp.zip', 
              'h172ssp.zip', mode = 'wb')
unzip('h172ssp.zip')
df_haven <- read_xpt('h172.ssp')
# get rid of factors to aid comparison:
df_foreign <- read.xport('h172.ssp') %>% as.tbl() %>% mutate_if(is.factor, as.character)
# Different number of rows:
dim(df_haven) == dim(df_foreign)
# Differing values:
df_haven[10,1] == df_foreign[10,1]
```

**Comment by evanmiller** [comment]
Thanks for the bug report. @hadley this is fixed by https://github.com/WizardMac/ReadStat/commit/a2271e4393b0d5da421a238d61b44b9975df247e

**Comment by karldw** [comment]
Wonderful, thank you both for such amazing work!

**Comment by Deleetdk** [comment]
I'm trying to load from of the NHANES data. Gives a weird error currently, using Github version.

http://wwwn.cdc.gov/Nchs/Nhanes/Search/DataPage.aspx?Component=Questionnaire&CycleBeginYear=2013

Weight history datafile. Only available in XPT.

```
> nhanes13_wh = haven::read_xpt("../data/2013/WHQ_H.XPT")
Error in .Call("haven_df_parse_xpt_file", PACKAGE = "haven", spec) : 
  "haven_df_parse_xpt_file" not available for .Call() for package "haven"
```
