### ISSUE TITLE
`write_dta` fails with error (no file written)

### ISSUE THREAD

**Issue by g3o2** [tidyverse/haven#235]
The code 
```R
path <- system.file("examples", "iris.dta", package = "haven")
haven::read_dta(path)

tmp <- tempfile(fileext = ".dta")
haven::write_dta(mtcars, tmp)
```

produces the error
```R
Error in eval(substitute(expr), envir, enclos) : 
  Writing failure: Unable to write data.
```

If I replace `write_dta` by `write_sav` or `write_sas`, no error is produced and the file appears to be saved.

```R
> sessionInfo()
R version 3.2.3 (2015-12-10)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 7 x64 (build 7601) Service Pack 1

locale:
[1] LC_COLLATE=French_Luxembourg.1252  LC_CTYPE=French_Luxembourg.1252    LC_MONETARY=French_Luxembourg.1252
[4] LC_NUMERIC=C                       LC_TIME=French_Luxembourg.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
[1] readr_1.0.0    assertthat_0.1 tools_3.2.3    haven_1.0.0    tibble_1.2     Rcpp_0.12.7   
````

This has occurred since haven version 1. Before, the said code would run without any error.

**Comment by rogerjdeangelis** [comment]
Write_sas does not produce an error for me in SAS, however neither WPS nor SAS can read the dataset.

Are you able to read the R SAS dataset in WPS or SAS?

Initially I got the following error from SAS

'dataset is not a SAS dataset'

I slugged in the datset name, which seemed to be missing and I still got a less troublesome error

'I/O error on SAS dataset TEST'

**Comment by evanmiller** [comment]
@rogerjdeangelis Definitely looks like progress. I'll add code to provide a default data set name, so then we can worry about the I/O error.

**Comment by evanmiller** [comment]
See https://github.com/WizardMac/ReadStat/commit/109a629cb5dd27ed4fd89de87223417a6b270db3

**Comment by g3o2** [comment]
@evenmiller and @rogerjdeangelis, in what way are your remarks related to the issue I've created ?

**Comment by rogerjdeangelis** [comment]
Not related to datastep name, but I have examined WPS, SAS  and Stat
Transfer datasets and none of then have the contents of byte 32 = 33 with
the contents of byte(35)=22. I think it might ne better if both bytes
contained 33. This bytes effect offsets.

None of Mat's test dataset have the 33/22 combination?​

**Comment by evanmiller** [comment]
@g3o2 Sorry, we got off-topic! I will delete my irrelevant comments. @rogerjdeangelis let's move the discussion to #224.
