### ISSUE TITLE
Accessing variable labels

### ISSUE THREAD

**Issue by methodds** [tidyverse/haven#237]
Hi,
I understand that value labels can be accessed with ``print_labels()`` and variable labels are displayed beneath variable names in the dataviewer. But is it also possible to access variable labels and store them , e.g. in a list? What I'm looking for is as possibility to copy Stata's ``lookfor`` command:

![stata_lookfor](https://cloud.githubusercontent.com/assets/7460499/20156366/5c3a535c-a6d0-11e6-8139-da04a11c2f9c.png)

The command basically uses a regex to search within variable labels and then returns all variable names (and other information, which is not that important) matching these labels. A function for this would be very helpful for larger survey datasets.

**Comment by hadley** [comment]
This seems like a good idea, but unfortunately it's not high enough on my priority list that I will implement it myself. However, I'd be happy to review a PR.

Here some (untested) code to get you started:

```R
look_for <- function(x, pattern) {
  stopifnot(is.data.frame(x))
  
  var_label <- function(x) {
    label <- attr(x, "variable.label")
    if (is.null(label)) "" else label
  }
  
  labels <- vapply(var_label, x, character(1))
  
  names(x)[grepl(pattern, labels)]
}
```

You'd need to think about what this function should return - a vector of variable names or the variables themselves?
