### ISSUE TITLE
read_dta fails with error

### ISSUE THREAD

**Issue by methodds** [tidyverse/haven#238]
Hi, 
trying to load a Stata 14 dataset (file for reproduction is available [here](https://www.dropbox.com/s/u0a6pufln1sao6g/bla_sample.dta?dl=1)) raises an error. The dataset is not corrupt, as loading it with Stata or pandas works without a problem.

```
df <- read_stata('bla_sample.dta')


Error in eval(substitute(expr), envir, enclos) : 
  Failed to parse /home/bla_sample.dta: Invalid file, or file has unsupported features.
```

**Comment by evanmiller** [comment]
Thanks for the report. This issue is fixed in ReadStat here: https://github.com/WizardMac/ReadStat/commit/fac9625a80b2dd09cd2e3a9f5a51731806240179

**Comment by hadley** [comment]
And now fixed in haven thanks to readstat update
