### ISSUE TITLE
Unexpected termination of R when trying to read a large sas7bdat

### ISSUE THREAD

**Issue by Zardoz1978** [tidyverse/haven#254]
I am currently testing R with large data file. Whe trying to load a large SAS data file (1,8GO sas7bdat, uncompressed) with -on purpose - not enough memory (standard allocation), the R sesssion is brutally terminated without any message about lack of memory.
![crash - read_sas](https://cloud.githubusercontent.com/assets/24603698/21395099/7a6506a6-c79b-11e6-8e1d-3dc7fc2f8afa.JPG)

**Comment by hadley** [comment]
Unfortunately there's no way for us to fix this without a reproducible example.
