### ISSUE TITLE
Support stata value labels longer than 32 characters

### ISSUE THREAD

**Issue by brianstamper** [tidyverse/haven#259]
Stata allows value labels longer than 32 characters, but haven write_dta() does not permit them.

To create a demonstration data set, in Stata do:  (Update: added a .zip of this file, below.)

    use http://www.ats.ucla.edu/stat/stata/modules/autolab.dta, clear
    label define foreignlabels 0 "Hey everybody I am a domestic car" 1 "Hey everybody I am a foreign car"
    label values foreign foreignlabels
    save "autolab.dta"

Then in R we observe:

    > nchar("Hey everybody I am a domestic car")
    [1] 33

and

    > k <- read_dta('autolab.dta')   # adjust path as needed
    > write_dta(k, 'test-out.dta')
    Error: Stata only supports value labels up to 32 characters in length. 
    Problems: `foreign`

The length limit of the label name definition (in this case 'foreignlabels') is in fact 32, but the current limit to the value labels themselves is 32,000, according to http://www.stata.com/help.cgi?limits.

**Comment by brianstamper** [comment]
Here's a copy of the autolab.dta file produced by Stata as described above, using Stata 13.

[autolab.zip](https://github.com/tidyverse/haven/files/699289/autolab.zip)

**Comment by hadley** [comment]
@evanmiller does readstat support writing these long variable labels?

**Comment by evanmiller** [comment]
@hadley Yes.
