### ISSUE TITLE
Comment on priority of fixes

### ISSUE THREAD

**Issue by rogerjdeangelis** [tidyverse/haven#260]
We do appreciate the work you are doing with respect to creating SAS datasets and reading SAS fprmat catalogs.

Programmers have other open source alternatives for 'every' foreign data structure in the haven package except writing SAS datasets and reading SAS formats. Python and Perl handle the haven foreign data structures. There may be some 'minor' issues like label lengths, but these are not 'show stoppers'?

I don't want to tell you what to work on, however programmers like me have no alternatives when dealing with SAS objects to and from R.

**Comment by evanmiller** [comment]
Just to provide some context, the SAS binary writer is provided as "experimental" -- we implemented it mainly to provide round-trip test coverage for the reader, and with the hope that if someone was interested enough, they would build on our work to provide proper SAS compatibility.

**Comment by hadley** [comment]
Thanks for the feedback.
