### ISSUE TITLE
Support for Statistica (.sta) files

### ISSUE THREAD

**Issue by Deleetdk** [tidyverse/haven#264]
I've received some Statistica files in `.sta` format. Unfortunately, there does not seem to be any easy ways to convert this to anything without having Statistica. Note Stackoverflow questions:

http://stackoverflow.com/questions/16523674/how-to-open-statistica-sta-file-under-r
http://stackoverflow.com/questions/29750939/how-to-import-statistica-data-sta-into-r

I could not get their solution to work because the R package is no longer on CRAN due to licensing issues.

Had to fall back to obtaining a copy of Statistica, opening the files in that and exporting to something more useful.

**Comment by hadley** [comment]
This is out scope for haven since it's not supported by ReadStat
