### ISSUE TITLE
Catalog option is ignored with read_sas

### ISSUE THREAD

**Issue by rogerjdeangelis** [tidyverse/haven#268]
Thanks for all the good work

```R
library(haven);
sas <- read_sas("d:/sd1/class.sas7bdat",catalog_file= "d:/fmt/simple64bit.sas7bcat")
names(attr(sas[, "SEX"], "labels"))
head(sas)
str(sas)
```
There is not log

supporting dodumentation
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

Issues when reading SAS datasets with associated format catalog

Win 7 64bit SAS 9.4 64bit

Your work with SAS datasets and SAS catalogs is appreciated.
Here are some areas for possible enhancements

I am unable to get value labels using the catalog_file option with read_sas.
The SAS/WPS code below demonstrates that the class.sas7bdat does have the $sex format attached.
The hex listing of the format catalog shows that the format catalog has the sex format and
it is formatted correctly ( I removed the 'filler-growth areas )
SAS TEST BEFORE R;
options validvarname=upcase;
libname fmt "d:/fmt";
options fmtsearch=(fmt.simple64bit);

proc format lib=fmt.simple64bit;
value $sex
'M'='Male'
'F'='Female'
;
run;quit;

libname sd1 "d:/sd1";
data class(compress=no);
format sex $sex.;
set sashelp.class;
put sex $1. +3 sex $sex.;
run;quit;

/* sex does have the format */
M Male
F Female
F Female
F Female
M Male

R CODE;
%utl_submit_r64('
library(haven);
sas <- read_sas("d:/sd1/class.sas7bdat",catalog_file= "d:/fmt/simple64bit.sas7bcat");
names(attr(sas[, "SEX"], "labels"));
head(sas);
str(sas);
');
library(haven);
sas <- read_sas("d:/sd1/class.sas7bdat",catalog_file= "d:/fmt/simple64bit.sas7bcat");
names(attr(sas[, "SEX"], "labels"))
;head(sas);str(sas);
LOG

NULL

A tibble: 6 × 5

 NAME   SEX   AGE HEIGHT WEIGHT
<chr> <chr> <dbl>  <dbl>  <dbl>
1 Alfred M 14 69.0 112.5
2 Alice F 13 56.5 84.0
3 Barbara F 13 65.3 98.0
4 Carol F 14 62.8 102.5
5 Henry M 14 63.5 102.5
6 James M 12 57.3 83.0
Classes 'tbl_df', 'tbl' and 'data.frame':	19 obs. of 5 variables:
$ NAME : chr "Alfred" "Alice" "Barbara" "Carol" ...
$ SEX : chr "M" "F" "F" "F" ...
$ AGE : num 14 13 13 14 14 12 12 15 13 12 ...
$ HEIGHT: num 69 56.5 65.3 62.8 63.5 57.3 59.8 62.5 62.5 59 ...
$ WEIGHT: num 112 84 98 102 102 ...

attr(*, "label")= chr "CLASS"
sas7bcat.txt

**Comment by rogerjdeangelis** [comment]
Added SAS dataset and format catalog

[class.zip](https://github.com/tidyverse/haven/files/739359/class.zip)

**Comment by hadley** [comment]
Thanks for the reprex — you can make it even better by using `download.file()` to download the file to `tempfile()` so that I can copy and paste a single block of code.

Could you please also edit the title to succinctly describe the issue and use ```` ``` ```` to mark the SAS code as code?

**Comment by rogerjdeangelis** [comment]
This is my first time with tempfile, was not sure how to avoid unzipping to desktop folder
Works fine without the 'catalog_file'

````R
library(haven)
zip_path <- tempfile()
download.file("https://dl.dropboxusercontent.com/u/15716238/class.zip", zip_path)
rdata_path <- unzip(zip_path, exdir = "d:/sd1")
sas <- read_sas("d:/sd1/class.sas7bdat",catalog_file= "d:/sd1/simple64bit.sas7bcat")
names(attr(sas[, "SEX"], "labels"))
head(sas)
str(sas)
````

R LOG
Error in df_parse_sas_file(spec_data, spec_cat, encoding = encoding) :
  Failed to parse d:/sd1/simple64bit.sas7bcat: Unable to read from file.
Calls: read_sas -> df_parse_sas_file -> .Call
Execution halted


Just to show the format catalog is valid

proc fmtlib lib=sd1.simple64bit cntlout=lst;
run;quit;

----------------------------------------------------------------------------
|       FORMAT NAME: $SEX     LENGTH:    6   NUMBER OF VALUES:    2        |
|   MIN LENGTH:   1  MAX LENGTH:  40  DEFAULT LENGTH:   6  FUZZ:        0  |
|--------------------------------------------------------------------------|
|START           |END             |LABEL  (VER. V7|V8   30JAN2017:10:26:37)|
|----------------+----------------+----------------------------------------|
|F               |F               |Female                                  |
|M               |M               |Male                                    |
----------------------------------------------------------------------------

**Comment by hadley** [comment]
Can you please continue to tweak the reprex so it's easier for me to run it? (I don't have a d drive). I think you'll find it easier if you don't zip the files.

**Comment by rogerjdeangelis** [comment]
We are all pulling for you with read/write/format interfaces to/from SAS/WPS/Stattransfer and Carolina

I simplified the reprex, eliminating the zip files, see error in log below.

* not sure you will be able to access the dropbox file.
 They are in my public folder but I am runny from workstation
 that has access to the local dropbox file.

It worked for me.

%utl_submit_r64('
source("c:/Program Files/R/R-3.3.2/etc/Rprofile.site",echo=T);
library(haven);
path1 <- tempfile();
download.file("https://www.dropbox.com/s/4hl76800wlfhk71/class.sas7bdat?raw=1", path1, mode="wb");
path2 <- tempfile();
download.file("https://www.dropbox.com/s/t1j25n211id9456/simple64bit.sas7bcat?raw=1", path2, mode="wb");
sas <- read_sas(path1);
head(sas);
sas <- read_sas(path1,catalog_file= path2);
');


> options(help_type = "html")
# A tibble: 6 × 5
    SEX    NAME   AGE HEIGHT WEIGHT
  <chr>   <chr> <dbl>  <dbl>  <dbl>
1     M  Alfred    14   69.0  112.5
2     F   Alice    13   56.5   84.0
3     F Barbara    13   65.3   98.0
4     F   Carol    14   62.8  102.5
5     M   Henry    14   63.5  102.5
6     M   James    12   57.3   83.0
NOTE: 16 lines were written to file PRINT.
Stderr output:
trying URL 'https://www.dropbox.com/s/4hl76800wlfhk71/class.sas7bdat?raw=1'
Content type 'application/octet-stream' length 131072 bytes (128 KB)
==================================================
downloaded 128 KB

trying URL 'https://www.dropbox.com/s/t1j25n211id9456/simple64bit.sas7bcat?raw=1'
Content type 'application/octet-stream' length 17408 bytes (17 KB)
==================================================
downloaded 17 KB

Error in df_parse_sas_file(spec_data, spec_cat, encoding = encoding, cols_only = cols_only) :
  Failed to parse C:/Users/beast/AppData/Local/Temp/RtmpOUVFbn/file12c05ded2657: Unable to read from file.
Calls: read_sas -> df_parse_sas_file -> .Call
Execution halted

**Comment by evanmiller** [comment]
This example does not have any parse errors when using the development version of haven.

```R
> devtools::install_github("tidyverse/haven")
> library(haven)
> sas <- read_sas("/Users/emiller/Downloads/rogerjdeangelis/class-2.sas7bdat", catalog_file = "/Users/emiller/Downloads/rogerjdeangelis/simple64bit.sas7bcat")
> sas
# A tibble: 19 x 5
         SEX    NAME   AGE HEIGHT WEIGHT
   <chr+lbl>   <chr> <dbl>  <dbl>  <dbl>
 1         M  Alfred    14   69.0  112.5
 2         F   Alice    13   56.5   84.0
 3         F Barbara    13   65.3   98.0
 4         F   Carol    14   62.8  102.5
...
```

Not sure how value labels work with haven, but `<chr+lbl>` indicates to me that they're being applied.

@hadley I think it's safe to close this issue.

@rogerjdeangelis In the future please spend time formatting your comments using Markdown, as they are difficult for us to read. This guide should help: https://guides.github.com/features/mastering-markdown/

**Comment by rogerjdeangelis** [comment]
I could not figure out how to force the comment to use a monospace font. I hope this is better.

    Thanks Hadley for your efforts. I provided more detail below. Let me know if there is anything I cando 
    to help, I am somewhat familiar with the binary representation of format catalogs and 
    SAS/WPS/Stattransfer datasets.

[Input dataset CLASS

Up to 40 obs from CLASS total obs=19

Obs    NAME       SEX    AGE    HEIGHT    WEIGHT

  1    Alfred      M      14     69.0      112.5
  2    Alice       F      13     56.5       84.0
  3    Barbara     F      13     65.3       98.0


* Maybe haven could generate this code using the catalog;
* This what my reprex should yeild.
* This is not a trivial problem for you;

CLASS <- read_sas("d:/sd1/class.sas7bdat");
CLASS$SEX <- factor(CLASS$SEX,c("F", "M"), exclude = "");
levels(CLASS$SEX) <- c("Female","Male");
label(CLASS$SEX) <- "";


%utl_submit_r64('

library(haven);
library(Hmisc);
CLASS <- read_sas("d:/sd1/class.sas7bdat");
CLASS$SEX <- factor(CLASS$SEX,c("F", "M"), exclude = "");
levels(CLASS$SEX) <- c("Female","Male");
label(CLASS$SEX) <- "";
str(CLASS);
head(CLASS);

');

Classes 'tbl_df', 'tbl' and 'data.frame':	19 obs. of  5 variables:
 $ SEX   : Factor w/ 2 levels "Female","Male": 2 1 1 1 2 2 1 1 2 2 ...
  ..- attr(*, "label")= chr ""
 $ NAME  : chr  "Alfred" "Alice" "Barbara" "Carol" ...
 $ AGE   : num  14 13 13 14 14 12 12 15 13 12 ...
 $ HEIGHT: num  69 56.5 65.3 62.8 63.5 57.3 59.8 62.5 62.5 59 ...
 $ WEIGHT: num  112 84 98 102 102 ...
 - attr(*, "label")= chr "CLASS"
  A tibble: 6 × 5

        SEX    NAME   AGE HEIGHT WEIGHT
  <int+lbl>   <chr> <dbl>  <dbl>  <dbl>
1      Male  Alfred    14   69.0  112.5
2    Female   Alice    13   56.5   84.0
3    Female Barbara    13   65.3   98.0
4    Female   Carol    14   62.8  102.5
5      Male   Henry    14   63.5  102.5
6      Male   James    12   57.3   83.0
>

* Here is
* interface R with generated code a macro generates &rcode;
%utl_submit_r64(resolve('
  &rcode.
  CLASS;
  str(class);
  table(CLASS$SEX);
'));
](url)
