### ISSUE TITLE
Read (and write?) measurement scale attribute

### ISSUE THREAD

**Issue by sjPlot** [tidyverse/haven#275]
In SPSS (maybe in other packages as well), you can edit the measurement scale of variables, e.g. if a variable is discrete, ordinal or continuous. ReadStat supports these attributes with `readstat_variable_get_measure` and `readstat_variable_set_measure`. Would it be possible to read out these attributes and add them to the labelled vectors as additional attribute?

By this, you could, e.g. write your own functions that automatically choose the right test based on the measurement scale, or choose an appropriate color palette (qualitative vs. diverging vs. sequential) for ggplots, or so.

**Comment by hadley** [comment]
This seems like a good idea, but unfortunately it's not high enough on my priority list that I will implement it myself. However, I'd be happy to review a PR.
