### ISSUE TITLE
 File generated by write_sas cannot be opened by SAS.

### ISSUE THREAD

**Issue by DavisBrian** [tidyverse/haven#277]
MWE

```
library(tidyverse)
data_frame(x = LETTERS, y = letters) %>% write_sas(path = "test.sas7bdat")

x <- read_sas("test.sas7bdat") # This Works
```

However, when I go to SAS (9.3) and try to read it in

> 26   data test_letters;
> 27       set cin.Test;
> ERROR: File CIN.TEST.DATA is not a SAS data set.
> 28   run;
>

**Comment by skhan8** [comment]
I'm getting the exact same problem as @DavisBrian. Am able to read (read_sas) in any write_sas outputs but SAS cannot open any of my write_sas outputs.

**Comment by Henri70** [comment]
Exactly same problem here !

**Comment by evanmiller** [comment]
Duplicate of #224
