### ISSUE TITLE
labelled class is lost when using na.omit

### ISSUE THREAD

**Issue by AnnePetersen1** [tidyverse/haven#278]
I just noticed a weird phenomenon when using variables of class `labelled`. If I apply `na.omit()` to a `labelled` variable, it somehow loses its class information, as opposed to factor variables.  Specifically, I find e.g.
```{r}
a <- c(1, 1, 1, 2, 2, NA)
aFac <- factor(a)
aLab <- labelled(a, labels = c(Joe = 1, Pete = 2))
 bFac <- na.omit(aFac)
bLab <- na.omit(aLab)

> class(aFac); class(bFac)
[1] "factor"
[1] "factor"

> class(aLab); class(bLab)
[1] "labelled"
[1] "numeric"
```  

Maybe there is a clever reason why it should behave like this, but personally, I was a bit surprised, as I use `na.omit()` routinely and was getting strange results. 

I use haven version 1.0.0 from CRAN.

**Comment by hadley** [comment]
Works for me:

``` r
library(haven)

a <- c(1, 1, 1, 2, 2, NA)
aLab <- labelled(a, labels = c(Joe = 1, Pete = 2))
na.omit(aLab)
#> <Labelled double>
#> [1] 1 1 1 2 2
#> 
#> Labels:
#>  value label
#>      1   Joe
#>      2  Pete
```

Might be fixed in dev version.
