### ISSUE TITLE
Failure to install package "haven"

### ISSUE THREAD

**Issue by GeoBer** [tidyverse/haven#280]
Message when compiling:

```
DfReader.cpp(355): error: more than one operator "==" matches these operands:
            built-in operator "pointer == pointer"
            function "Rcpp::operator==(Rcpp::Na_Proxy, SEXP)"
            operand types are: Rcpp::AttributeProxyPolicy<Rcpp::RObject_Impl<Rcpp::PreserveStorage>>::AttributeProxy == SEXP
          if (col.attr("class") == R_NilValue) {
                                ^

compilation aborted for DfReader.cpp (code 2)
make: *** [DfReader.o] Error 2
ERROR: compilation failed for package \u2018haven\u2019
* removing \u2018/home/bermage1/R/x86_64-pc-linux-gnu-library/3.2/haven\u2019

The downloaded source packages are in
        \u2018/export/scratch/SGE/2498721.1.interactive.q/RtmpmcB3yF/downloaded_packages\u2019
Warning message:
In install.packages("haven") :
  installation of package \u2018haven\u2019 had non-zero exit status
R 3.2.3> packageDescription("Rcpp")$Version
[1] "0.12.9"
R 3.2.3>
R 3.2.3> packageDescription("readr")$Version
[1] "1.0.0"
```

Fails also when attempting to install using all of tidyverse.  I need "haven" to read and write sas datasets. Any suggestions on how to fix the problem?

**Comment by lgragert** [comment]
I am having this same issue installing in R 3.3.1 on Linux.

**Comment by hadley** [comment]
See https://github.com/RcppCore/Rcpp/issues/640 - I think you need to update Rcpp

**Comment by jjsandoval** [comment]
You must do two thinks. First. Start by first figuring out your library location: Sys.getenv("R_LIBS_USER"). Second the 00LOCK file must been removed. For example in linux : 
sudo rm -r 00LOCK-haven

**Comment by rensa** [comment]
FWIW, I had the same problem when I tried to install `tidyverse` on a remote machine. Turns out I was using the Intel C compiler version 12.1.9.293 (the default version of it that had been stuck in my Bash profile when my account was created). Switching out to version 17.0.1.132 using the `module` system installed on the machine did the trick :)
