### ISSUE TITLE
SPSS fails to read value labels for ordered factors

### ISSUE THREAD

**Issue by gitrman** [tidyverse/haven#285]
SPSS is unable to read value labels for ordered factors -- whereas unordered factors are fine.

A minimal example:

```{r}
x <- c("a", "b", "c")

df <- data.frame(
  v1 = factor(x),
  v2 = factor(x, ordered = TRUE)
)

library(haven)
write_sav(df, "df.sav")
```

Here is a screenshot of the SPSS **Data View** tab after I open the file in SPSS:

![data_view](https://cloud.githubusercontent.com/assets/18112792/25324684/b20d3794-28f9-11e7-81d5-fcd82f1ca7c6.png)

`v1` and `v2` should look identical - however for `v2` the numeric values rather than the factor labels are displayed.

On the SPSS **Variable View** tab, for the unordered factor `v1`, SPSS correctly displays the measure type as `Nominal` and the value labels are listed correctly in the `Values` column.  Whereas for the ordered factor `v2`, SPSS displays the correct measure type (`Ordinal`), but the value labels have been erroneously set to "None".

![variable_view](https://cloud.githubusercontent.com/assets/18112792/25324680/af864484-28f9-11e7-8323-44313a19fead.png)

I am using the development version of Haven from github (`haven_1.0.0.9000`), Windows 10, and SPSS 22. I have also experienced this error on machines running Windows 7 and earlier versions of Haven.

**Comment by jeroen** [comment]
I ran into the same problem when trying to roundtrip the `diamonds` dataset:

```r
> tmp <- tempfile()
> haven::write_sav(ggplot2::diamonds, tmp)
> diamonds <- haven::read_sav(tmp)
> head(diamonds)
# A tibble: 6 × 10
  carat   cut color clarity depth table price     x     y     z
  <dbl> <dbl> <dbl>   <dbl> <dbl> <dbl> <dbl> <dbl> <dbl> <dbl>
1  0.23     5     2       2  61.5    55   326  3.95  3.98  2.43
2  0.21     4     2       3  59.8    61   326  3.89  3.84  2.31
3  0.23     2     2       5  56.9    65   327  4.05  4.07  2.31
4  0.29     4     6       4  62.4    58   334  4.20  4.23  2.63
5  0.31     2     7       2  63.3    58   335  4.34  4.35  2.75
6  0.24     3     7       6  62.8    57   336  3.94  3.96  2.48
```
