### ISSUE TITLE
Installation error if PKG_CXXFLAGS = -std=c++14

### ISSUE THREAD

**Issue by DominikMueller64** [tidyverse/haven#286]
If I have in my ~/.R/Makevars file the line `PKG_CXXFLAGS = -std=c++14`,  I get the following error when trying to install haven:

`g++ -I/usr/share/R/include -DNDEBUG  -I"/home/domi89/R/x86_64-pc-linux-gnu-library/3.4/Rcpp/include" -I"/home/domi89/R/x86_64-pc-linux-gnu-library/3.4/BH/incl
ude"   -std=c++14 -fpic  -Wall -O2 -c DfReader.cpp -o DfReader.o                                                                                             
DfReader.cpp:7:22: fatal error: readstat.h: No such file or directory
 #include "readstat.h"
`

**Comment by hadley** [comment]
I'm not sure why you think this should work. You can add arbitrary extra compilation flags to a package.
