### ISSUE TITLE
read_dta fails to convert missing values encoded as '.' in STATA to NA

### ISSUE THREAD

**Issue by AmyMikhail** [tidyverse/haven#289]
Not sure how to show this with a MWE, but when a STATA file contains missing values encoded as '.' in string vectors, read_dta does not convert them to NA (they remain as the character string ".").

`zap_missing(x)` also does not correct the problem (I assume since they were not 'tagged' as missing in the first place).

Should read_dta include an argument to specify encoding of missing values on import?

Here is my attempt at a MWE:

```
# Create dummy data:
mydt <- data.table(id = c(1,2,3,4,5), 
                   Age =  c(3,12,61,NA,13), 
                   Sex = c("M", "F", "F", "M", "F"), 
                   Apple = c("Y", "N", ".", "Y", NA))

# Export as .dta:
write_dta(mydt, "test.dta")

# Import back in to r with read_dta:
mydt_imp <- read_dta("test.dta")

# Print:
> mydt_imp
# A tibble: 5 × 4
     id   Age   Sex Apple
  <dbl> <dbl> <chr> <chr>
1     1     3     M     Y
2     2    12     F     N
3     3    61     F     .
4     4   NaN     M     Y
5     5    13     F      
```

As already noted by others the numeric missings are converted to 'NaN' rather than NA but the character string missings (e.g. in column 'Apple' above) remain as is:

```
> is.na(mydt$Apple)
[1] FALSE FALSE FALSE FALSE  TRUE

> is.na(mydt_imp$Apple)
[1] FALSE FALSE FALSE FALSE FALSE

```

**Comment by hadley** [comment]
I'm pretty sure `.` is not a missing string value in stata. The missing value for string is the empty string. See e.g. http://www.stata.com/statalist/archive/2012-09/msg00105.html
