### ISSUE TITLE
Auto coerce SPSS 'nominal' and 'ordinal' variables to factors

### ISSUE THREAD

**Issue by jeroen** [tidyverse/haven#290]
Currently `write_sav` does use the measure attribute for saving, but ignores it for reading:

```r
tmp <- tempfile()
haven::write_sav(ggplot2::diamonds, tmp)
head(haven::read_sav(tmp))
# A tibble: 6 x 10
#  carat       cut     color   clarity depth table price     x     y     z
#  <dbl> <dbl+lbl> <dbl+lbl> <dbl+lbl> <dbl> <dbl> <dbl> <dbl> <dbl> <dbl>
# 1  0.23         5         2         2  61.5    55   326  3.95  3.98  2.43
# 2  0.21         4         2         3  59.8    61   326  3.89  3.84  2.31
# 3  0.23         2         2         5  56.9    65   327  4.05  4.07  2.31
# 4  0.29         4         6         4  62.4    58   334  4.20  4.23  2.63
# 5  0.31         2         7         2  63.3    58   335  4.34  4.35  2.75
# 6  0.24         3         7         6  62.8    57   336  3.94  3.96  2.48
```
It would make sense if `read_sav` would have an option to automatically coerce `SAV_MEASURE_NOMINAL` and `SAV_MEASURE_ORDINAL` variables into factors and ordered factors respectively.

I think this option should be TRUE by default (opt-out). Variables explicitly marked as normal / ordinal in the data format map nicely to factors. 

Edge cases (missing labels) should be solvable (e.g. use value as label for unlabeled values).

**Comment by sjPlot** [comment]
Could be related to #275

**Comment by huftis** [comment]
This sounds like a nice feature, but I don’t think it should be enabled *by default*, as it leads to data loss (factors don’t keep their original values/codes, but are internally reencoded to `1:n`).

**Comment by hadley** [comment]
Given the lack of interest, the relative limited time I have to work on haven, and that I'm not sure this is the right thing to do, I'm going to close this issue.
