### ISSUE TITLE
read_spss: When a missing value is not defined as a value label

### ISSUE THREAD

**Issue by d4ff** [tidyverse/haven#291]
Hi,

Consider a .sav file with several numeric variables where -77 is defined as a missing value, but not as a value label. You would get the following result when trying to index one of them:

```
ds <- read_spss(sav.file, user_na=TRUE)
ds[1]
Error: `x` and `labels` must be same type
```

I'm sure there are plenty of ways to fix it, but I'm looking for a solution that doesn't require operations outside of R, and is faster than a loop. Running user_na=FALSE will avoid the issue, but I need the actual values, NA won't do. The only solution i've found is:

```
ds <- read_spss(sav.file, user_na=TRUE)
val_label(ds[[1]], -77) <- "temp"
na_values(ds[[1]]) <- NULL 
val_label(ds[[1]], -77) <- NULL
```

It's not great, and I don't think I can avoid a for-loop since the solution won't work without double brackets. Can anyone suggest a fast way to perform the above operation on multiple columns in a large dataset?

This may be kind of a fringe issue. The .sav files have been put together by a supplier's computer system. It would be great if there was an option to completely ignore SPSS missing values altogether when performing an import, as opposed to importing them as attributes that can potentially mess things up when dealing with sub-par datasets.

Thanks in advance!

**Comment by strengejacke** [comment]
I'm not quite sure what you would like to achieve: is it a working print-method for your data? You could remove the labelled-class, which would not remove the attributes. This can be done with `unlabel()` from the *sjlabelled*-pkg:

`sjlabelled::unlabel()`

I have tested this on a SPSS-dataset:

```
test[1]
#> Error: `x` and `labels` must be same type

unlabel(test[1])
'> # A tibble: 483 x 1
'>    Codenr
'>     <dbl>
'>  1   3348
'>  2   3294
'>  3   3157
'>  4   3256
'>  5   2041
'>  6   3093
'>  7   2007
'>  8   3190
'>  9   3221
'> 10   3300
'> # ... with 473 more rows
```

**Comment by hadley** [comment]
You can also use `haven::zap_labels()`
