### ISSUE TITLE
write_sav: Crash if value label contains more than 127 characters

### ISSUE THREAD

**Issue by d4ff** [tidyverse/haven#292]
Related to #262 

The conversation in 262 tells me that long labels are truncated to 120 characters. I can confirm that this is the case for me when the number of characters in the troublesome value label is between 121 and 127. However, when the label is 128 characters or longer, the system crashes. Tested in Rstudio and Sublime REPL.

Label was originally 148 characters long. write_sav worked when I removed the label, and when I truncated it before export. I then went on to try different lengths until I find the length at which it crashes -- 127.

**Comment by evanmiller** [comment]
Can you provide a sample script?

**Comment by d4ff** [comment]
```
filepath <- "path to .sav file with a long value label"
ds <- read_spss(filepath, user_na = FALSE)
val_label(ds[1], 1)
>"I am a permanent resident of COUNTRY but I do not have a living space in COUNTRY at the moment because I'm currently residing abroad (e.g. diplomat)"
```
crash:

```
ds <- read_spss(filepath, user_na = FALSE)
write_sav(ds, "ds.sav")
```

no crash:

```
ds <- read_spss(filepath, user_na = FALSE)
val_label(ds, 1) <- substr(val_label(ds, 1), 1, 127)
write_sav(ds, "ds.sav")
```
crash:

```
ds <- read_spss(filepath, user_na = FALSE)
val_label(ds, 1) <- substr(val_label(ds, 1), 1, 128)
write_sav(ds, "ds.sav")
```

**Comment by evanmiller** [comment]
What version of haven are you using? This may have been fixed in https://github.com/tidyverse/haven/commit/d8b1f711e787b941757898a66310e1cfe79905b2

**Comment by d4ff** [comment]
```
other attached packages:
[1] labelled_1.0.0 haven_1.0.0
```

Downloaded the package last week so I'm assuming I have the latest version? CRAN is not suggesting any updates.

**Comment by evanmiller** [comment]
Please try the development version

```R
install.packages("devtools")
devtools::install_github("tidyverse/haven")
```
