### ISSUE TITLE
'Peek' functionality to return a 0 (or some small number) row data frame with column data.

### ISSUE THREAD

**Issue by jtchittenden** [tidyverse/haven#293]
Not an bug, but an enhancement request.

Sometimes I don't want all the rows in the file.  Usually it's that the file is very large and I want to try things out on a subset, rather than load the entire file.  Or I just want to put together some metadata for the columns in the file (e.g. name and type).  I modified Matthew Shotwell's sas7bdat code to do this, but haven has become much more stable than that original codebase and I would love to have this as a native part of the haven package.

**Comment by hadley** [comment]
Part of #194
