### ISSUE TITLE
Filtering data as it loads in read_sas

### ISSUE THREAD

**Issue by jtchittenden** [tidyverse/haven#294]
I would like to hand read_sas an expression that it could use to filter out rows I don't want before trying to return a gigantic object. For instance, if I have a 120Gb file but only need 1% of that which I could filter out, it would be great if that could happen while the file loads.  Something like this: haven::read_sas("file.sas7bdat", filter=SITEID=='097' & VISIT=='SCREENING').  I recognize that this could slow things down quite a bit, but for large files it may avoid memory issues and loading failures.

**Comment by hadley** [comment]
Part of #194
