### ISSUE TITLE
Possible problem with labelled_spss?

### ISSUE THREAD

**Issue by vate01** [tidyverse/haven#296]
Hello!

I'm using the labelled_spss function but it seems that this just work when I load the expss package. 

Without loading expss:
```
> table(haven::labelled_spss(c(1,2,2,2,3,9,1,3,2,9), c(yes = 1, no = 3, other=2, missing = 9), na_values=9))
1 2 3 9 
2 4 2 2 
```
And loading it previously:
```
> library(expss) 
Loading required package: magrittr
Loading required package: htmlTable

Use 'options(expss.output = "viewer")' to display tables in the RStudio Viewer.
 To return to the console output, use 'options(expss.output = NA)'.

> table(haven::labelled_spss(c(1,2,2,2,3,9,1,3,2,9), c(yes = 1, no = 3, other=2, missing = 9), na_values=9))

    yes   other      no missing 
      2       4       2       2 
> 

```
Is this a feature? 

Thanks!

Edited:

Version of packages:

> Package: haven
> Version: 1.0.0
> 

> Package: expss
> Type: Package
> Title: Tables with Labels and Some Useful Functions from Spreadsheets
>         and 'SPSS' Statistics
> Version: 0.7.1
> 

Machine info:

>  Sys.info()
>                                        sysname 
>                                        "Linux" 
>                                        release 
>                                "4.11.6-3-ARCH" 
>                                        version 
> "#1 SMP PREEMPT Thu Jun 22 12:21:46 CEST 2017" 
>                                       nodename 
>                                        machine 
>                                       "x86_64" 
>  

and R info:

R.version
               _                           

> 
> platform       x86_64-pc-linux-gnu         
> arch           x86_64                      
> os             linux-gnu                   
> system         x86_64, linux-gnu           
> status                                     
> major          3                           
> minor          4.0                         
> year           2017                        
> month          04                          
> day            21                          
> svn rev        72570                       
> language       R                           
> version.string R version 3.4.0 (2017-04-21)
> nickname       You Stupid Darkness

**Comment by hadley** [comment]
The expss package must provide a method for table or similar.
