### ISSUE TITLE
Automatic file uncompression only works with lower case file extensions

### ISSUE THREAD

**Issue by connorp** [tidyverse/haven#298]
Per the documentation, haven's read functions can automatically uncompress "Files ending in `.gz`, `.bz2`, `.xz`, or `.zip`." However, if the file extensions are not all lower case, the process fails, since the function tries to read it like a data file. I imagine it would be a simple fix for the check that determines whether the file needs to be uncompressed be case insensitive. 

I have tested this on the latest version of haven, 1.1.0, with both `read_xpt()` and `read_sas()`

**Comment by hadley** [comment]
This behaviour is inherited from readr, so I've filed an issue over there.
