### ISSUE TITLE
invalid byte sequence error on unix, but works on windows

### ISSUE THREAD

**Issue by ajdamico** [tidyverse/haven#304]
library(haven)
	tf <- tempfile()
	download.file( 'http://assets.pewresearch.org/wp-content/uploads/sites/2/2009/09/Pew-GAP-Fall-2009-BW-survey-for-website.zip' , tf , mode = 'wb' )
	w <- unzip( tf , exdir = tempdir() )
	this_file <- grep( "\\.sav" , w , value = TRUE )

	# works on windows, fails on unix
	x <- read_sav( this_file )

	# Error in df_parse_sav_file(spec, user_na) :
	  # Failed to parse /tmp/Rtmp1j5BdG/Pew Global Attitudes Fall 2009 Dataset.sav: Unable to convert string to the requested encoding (invalid byte sequence).

using dev haven on unix.  thank you

	sessionInfo()
	R version 3.3.3 (2017-03-06)
	Platform: x86_64-redhat-linux-gnu (64-bit)
	Running under: Fedora 24 (Twenty Four)

	locale:
	 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C
	 [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8
	 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8
	 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C
	 [9] LC_ADDRESS=C               LC_TELEPHONE=C
	[11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C

	attached base packages:
	[1] stats     graphics  grDevices utils     datasets  methods   base

	other attached packages:
	[1] haven_1.1.0.9000

	loaded via a namespace (and not attached):
	 [1] Rcpp_0.12.12    digest_0.6.12   withr_1.0.2     R6_2.2.2
	 [5] git2r_0.18.0    magrittr_1.5    httr_1.2.1      rlang_0.1.1
	 [9] curl_2.3        devtools_1.13.2 forcats_0.2.0   tools_3.3.3
	[13] readr_1.1.1     hms_0.3         memoise_1.0.0   knitr_1.16
	[17] tibble_1.3.3

**Comment by evanmiller** [comment]
Thanks for the report, I am able to reproduce it on UNIX. The invalid character `0x9d` appears in a value label, between:

    KDH (Kres

and

    ansko-demokratické hnutie)

How does Windows decode that character? Wikipedia indicates the string should be

    Kresťanskodemokratické hnutie

I.e. the troublesome character is a [voiceless palatal stop](https://en.wikipedia.org/wiki/Ť). I'm not sure if SPSS is inserting an invalid character in place of `ť`, or if Windows knows to decode `0x9d` as `ť` (maybe it's defined by a standard somewhere).

**Comment by evanmiller** [comment]
Update: The character `ť` is encoded as `0x9d` in the Windows-1250 character set:

https://en.wikipedia.org/wiki/Windows-1250

The SPSS dataset is clearly labeled Windows-1252, however. It's possible that Windows silently uses Windows-1250 codes when it encounters an undefined code in Windows-1252 -- so I'd still like to know if this string is correctly decoded on Windows.

**Comment by evanmiller** [comment]
@ajdamico I'm still not sure why the original command works on Windows. However if you use the latest dev haven, then on Unix just change this line:

```
x <- read_sav( this_file )
```

To this:

```
x <- read_sav( this_file, encoding = "WINDOWS-1250" )
```

And it should import everything okay. If so, please close the issue, as the SAV file is apparently mis-reporting its character encoding.

**Comment by ajdamico** [comment]
wow, thanks very much for solving this!
