### ISSUE TITLE
read_sas includes deleted records

### ISSUE THREAD

**Issue by rdenham** [tidyverse/haven#306]
This might be a result of poor sas coding, but I got caught out reading in a sas data set after doing a proc sql delete step. The deleted records don't seem to be actually removed, or flagged in anyway in the r data.frame. Here's an example:

    data mywork.rcheck; 
    input x1 x2;
    cards;
    1 1
    2 2
    3 3
    4 4
    5 5
    ;
    run;

This reads in fine:

    > read_sas("rcheck.sas7bdat")
    # A tibble: 5 x 2
         x1    x2
      <dbl> <dbl>
    1     1     1
    2     2     2
    3     3     3
    4     4     4
    5     5     5

If I do a deletion in sas, like:

    proc sql;
	    delete from mywork.rcheck
	    where x1 = 4;
    quit;

And then read the same file in using read_sas I get the same result as before the deletion. 

If I add a datastep then it all works fine:

    data mywork.rcheck_r (compress = no);
        set mywork.rcheck;
    run; 

So, not sure if it is an issue, or just a heads-up to be wary of deleting records in sas, since they don't seem to be actually deleted until a new dataset is created.

**Comment by hadley** [comment]
I don't think this is a haven issue but more of a SAS peculiarity, so I'm going to close this issue.
