### ISSUE TITLE
Support zap_label and/or zap_everything

### ISSUE THREAD

**Issue by jjchern** [tidyverse/haven#308]
Would you mind adding a function that strips variable labels? Something like `zap_label.R`:

```R
#' Zap variable labels
#'
#' Remove variable labels for vectors or the whole data frame.
#' 
#' @param x A vector or data frame.
#' @family zappers
#' @export
#' @examples 
#' path <- system.file("examples", "iris.dta", package = "haven")
#' iris_dta <- read_dta(path)
#' 
#' # Show variable labels
#' lapply(iris_dta, attr, "label")
#' 
#' # Strip variable labels
#' iris_dta <- zap_label(iris_dta)
#' lapply(iris_dta, attr, "label")
zap_label <- function(x) {
        UseMethod("zap_label")
}

#' @export
zap_label.default <- function(x) {
        attr(x, "label") <- NULL
        x
}

#' @export
zap_label.data.frame <- function(x) {
        x[] <- lapply(x, zap_label)
        x
}
```

And here're two tests (`test-zap-label.R`):

```R
context("zap_label")

test_that("zap_label removes a vector's label", {
        x <- structure(c("a", "b", "c"), "label" = "letters")
        x <- zap_label(x)
        expect_null(attr(x, "label"))
})

test_that("zap_label can apply to a data frame", {
        df <- tibble::tibble(
                x = structure(c("a", "b", "c"), "label" = "letters"),
                y = structure(c(0, 1, 2), "label" = "numbers")
        )
        df <- zap_label(df)
        expect_equal(attr(df$x, "label"), NULL)
        expect_equal(attr(df$y, "label"), NULL)
})
```

Sometimes I found that I wanted to zap everything to avoid certain warning messages (for example, messages generated from joining a tibble imported from `haven` and a regular data frame). With `zap_label()`, I can now run 

```R
df %>% 
        zap_labels() %>% 
        zap_label() %>% 
        zap_formats() -> df
```

Having a `zap_everything()` will also be helpful.

Finally, on an unrelated note, is `zap_missing()` part of the "zapper" family? It's not explicitly specified in [zap_missing.R](https://github.com/tidyverse/haven/blob/master/R/zap_missing.R).

**Comment by strengejacke** [comment]
You can use `sjlabelled::remove_all_labels()` to remove label(s) attributes from vectors or data frames (see https://cran.r-project.org/package=sjlabelled).

**Comment by datarichard** [comment]
I would like to remove variable labels from tibbles as well. Currently RStudio Viewer displays the label under the variable name, which can make the column very wide - too wide to see many columns on my (laptop) screen.

**Comment by hadley** [comment]
@datarichard: can you please file an issue with screenshot on RStudio github page?

**Comment by hadley** [comment]
I don't want to keep adding more and more zapper functions to haven, so I think using sjlabelled is best here.
