### ISSUE TITLE
Issues with Haven

### ISSUE THREAD

**Issue by steveniorfa** [tidyverse/haven#310]
I keep getting this error message after I successfully download the haven package and its dependencies. What do I do?
Warning in install.packages :
error 1 in extracting from zip file
Warning in install.packages :
cannot open compressed file 'BH/DESCRIPTION', probable reason 'No such file or directory'

**Comment by hadley** [comment]
It sounds like you're missing some depedency. I'd recommend restarting R and reinstalling haven + bh.
