### ISSUE TITLE
read_xpt not accessing variable labels

### ISSUE THREAD

**Issue by dennisfisher** [tidyverse/haven#314]
I have two SAS outputs containing the identical data: one in sas7bdat format, the other in XPT format.
When I read them using haven (1.1.0) in either RStudio or in a terminal window (R 3.4.1, OS X), the variable labels can be accessed from the sas7bdat version but not from the XPT version.  According to the man pages:

     Variable labels are stored in the "label" attribute of each
     variable.  It is not printed on the console, but the RStudio
     viewer will show it.

but that does not appear to be the case.  
The XPT file does appear to contain the labels (grep returns 
	Binary file /Users/fisher/Desktop/spdata.xpt matches

Any thoughts?  Are you sure that the read_xpt code actually manages labels?

**Comment by evanmiller** [comment]
Hi @dennisfisher, if you can provide an example file I will take a look.

**Comment by dennisfisher** [comment]
A colleague created these two files in SAS. 
When I read them with haven:

SAS7BDAT file:
 data.frame(read_sas(dir()[3])) -> X
> X[,1]
  [1] "B" "B" "B" "B" "B" "B" "B" "B" "B" "B" "B" "B" "B" "B" "B" "B" "B" "B"
 [19] "B" "B" "B" "B" "B" "B" "B" "B" "B" "B" "B" "B" "B" "B" "B" "B" "B" "B"
 [37] "B" "B" "B" "B" "B" "B" "B" "B" "B" "B" "B" "B" "B" "B" "B" "B" "B" "B"
 [55] "B" "B" "B" "B" "B" "B" "B" "B" "B" "B" "B" "B" "B" "B" "B" "B" "B" "B"
 [73] "B" "B" "B" "B" "B" "B" "B" "B" "B" "B" "B" "B" "B" "B" "B" "B" "B" "B"
 [91] "B" "B" "B" "B" "B" "B" "B" "B" "B" "B" "B" "B" "B" "B" "B" "B" "B" "B"
[109] "B" "B" "B" "B" "B" "B" "B" "B" "B" "B" "B" "B"
attr(,"label")
[1] "Lifestage (B - Beginning)"
attr(,"format.sas")
[1] "$"

SAS XPT file:
> data.frame(read_xpt(dir()[4])) -> Y
> head(Y)
  SECTOR PRODUCT        LOT DISTANCE CONTAIN ACTUAT OVALITY  AREA
1      B     REF 0000011234       40      11      1   1.331 675.9
2      B     REF 0000011234       40      12      1   1.414 504.1
3      B     REF 0000011234       40      13      1   1.269 479.6
4      B     REF 0000011234       40      14      1   1.247 443.8
5      B     REF 0000011234       40      15      1   1.186 343.5
6      B     REF 0000011234       40      16      1   1.218 518.7
> 
> Y[,1]
  [1] "B" "B" "B" "B" "B" "B" "B" "B" "B" "B" "B" "B" "B" "B" "B" "B" "B" "B"
 [19] "B" "B" "B" "B" "B" "B" "B" "B" "B" "B" "B" "B" "B" "B" "B" "B" "B" "B"
 [37] "B" "B" "B" "B" "B" "B" "B" "B" "B" "B" "B" "B" "B" "B" "B" "B" "B" "B"
 [55] "B" "B" "B" "B" "B" "B" "B" "B" "B" "B" "B" "B" "B" "B" "B" "B" "B" "B"
 [73] "B" "B" "B" "B" "B" "B" "B" "B" "B" "B" "B" "B" "B" "B" "B" "B" "B" "B"
 [91] "B" "B" "B" "B" "B" "B" "B" "B" "B" "B" "B" "B" "B" "B" "B" "B" "B" "B"
[109] "B" "B" "B" "B" "B" "B" "B" "B" "B" "B" "B" "B"

As you can see, labels are extracted for the SAS7BDAT file, not for XPT.

To confirm that the XPT file contains the labels, I used the SASxport package:
> attributes(read.xport("spdata.xpt")[,1])
$levels
[1] "B"

$class
[1] "labelled" "factor"  

$label
[1] "Lifestage (B - Beginning)"

$SASformat
[1] "$9."


Dennis Fisher MD
P < (The "P Less Than" Company)
Phone / Fax: 1-866-PLessThan (1-866-753-7784)
www.PLessThan.com <http://www.plessthan.com/>

**Comment by evanmiller** [comment]
@dennisfisher I need access to the file itself.

**Comment by dennisfisher** [comment]
the files were attached to the previous email.  i have done so again.  if they are being stripped, i have uploaded them to:
	https://www.dropbox.com/sh/78auodmlq5dgpkp/AABYyujDmCncPdrOF7rXIdV6a?dl=0 <https://www.dropbox.com/sh/78auodmlq5dgpkp/AABYyujDmCncPdrOF7rXIdV6a?dl=0>



Dennis Fisher MD
P < (The "P Less Than" Company)
Phone / Fax: 1-866-PLessThan (1-866-753-7784)
www.PLessThan.com <http://www.plessthan.com/>

**Comment by evanmiller** [comment]
Thanks. ReadStat sees the labels okay so it is likely an issue in haven.

**Comment by pitla1** [comment]
I received an xpt file which generated in SAS using cport procedure. Can "read_xpt" read such transport files? I am unable to read such xpt file with any of the available packages like Hmisc, SASxport, foreign, haven. Also, in windows version of R (version 3.4.0), I get the following error... 
_______________________________________________
library(haven)
data <- haven::read_xpt("C:/Users/pitla1/prj/test.xpt")
**Error: 'read_xpt' is not an exported object from 'namespace:haven'**
_______________________________________________
Any suggestions/solutions/workarounds using R would be highly appreciated. Of course, I can SAS for workarounds...

**Comment by hadley** [comment]
Can you please provide a minimal reprex (reproducible example)? The goal of a reprex is to make it as easy as possible for me to recreate your problem so that I can fix it: please [help me help you](https://nypdecider.files.wordpress.com/2014/08/help-me-help-you.gif)! 

If you've never heard of a reprex before, start by reading "[What is a reprex](http://reprex.tidyverse.org/articles/reprex.html)", and follow the advice further down the page. Please make sure your reprex is created with the reprex package as it gives nicely formatted output and avoids a number of common pitfalls.

For this case, R code illustrating that round tripping from `write_xpt()` to `read_xpt()` loses labels would be extremely useful.

**Comment by dennisfisher** [comment]
Hadley

Sorry about the delay in getting back to you.  I tried to reconstruct the original request but I have not been successful.  But, I have encountered a related problem.  The problem requires some explanation:

1.  I started with a SAS sas7bdat file that was probably created by SAS.  I read the file using haven, then wrote to:
	pk.sas7bdat
using “write_sas”.
So far so good.

2.  I can read the new sas7bdat file with no problem.  However, when attempt to read that file using StatTransfer (which has a good track record for reading sas7bdat files), I get the following error:
> Error reading dictionary -  SAS dataset (/users/fisher/desktop/pltdata-examples/pltdata.sasfiles/datafiles/source/pk.sas7bdat) Processing sas dataset dictionary was stopped because of the error (6). Please email a complete description of your problem to tech@circlesys.com.


3.  I also wrote to:
	pk.xpt
using “write_xpt”.  I can then read the file using read_xpt.  So, haven is internally consistent.  
However, when I try to read the file using foreign:
	read.xport(“pk.xpt”)
I get an error message:
	Error in lookup.xport(file) : file not in SAS transfer format
And when I try in StatTransfer, I get:
	File is not a SAS TRANSPORT file

This makes me think that two functions in haven — write_sas and write_xpt — are not working correctly.

I have attached three files:
	Pk-orig.sas7bdat: this is the starting point.
	The other two files were created in R using haven.

Dennis


Dennis Fisher MD
P < (The "P Less Than" Company)
Phone / Fax: 1-866-PLessThan (1-866-753-7784)
www.PLessThan.com <http://www.plessthan.com/>

**Comment by hadley** [comment]
`read_xpt()` now appears to read the labels. I'll open another issue for the inconsistency between `write_xpt` and `read.xport`

**Comment by dennisfisher** [comment]
Hadley

Thanks for fixing this.  The latest version in CRAN is dated 2018-01-18.  I presume that you are referring to the GitHub version rather than CRAN.  If so, when do you expect the CRAN version to be updated?

Dennis

Dennis Fisher MD
P < (The "P Less Than" Company)
Phone / Fax: 1-866-PLessThan (1-866-753-7784)
www.PLessThan.com

**Comment by hadley** [comment]
It's hard to know, but probably within the next week or two.

**Comment by dennisfisher** [comment]
thanks

Dennis Fisher MD
P < (The "P Less Than" Company)
Phone / Fax: 1-866-PLessThan (1-866-753-7784)
www.PLessThan.com
