### ISSUE TITLE
support labelled logical vectors [feature request]

### ISSUE THREAD

**Issue by salim-b** [tidyverse/haven#315]
I'd like to be able to create a labelled logical vector like this:

```R
library(haven)
logi_var = labelled(rep(TRUE, 5), c("some label" = TRUE, "some other label" = FALSE))
```

Right now this is not supported and gives the error message:
```R
`x` must be a numeric or a character vector`
```

Of course one can always set the corresponding attributes "by hand" using:
```R
logi_var <- rep(T, 5)
attr(x = logi_var, which = "class") <- "labelled"
attr(x = logi_var, which = "labels") <- c("some label" = TRUE, "some other label" = FALSE)
```
Naive as I am  [I tried this in the past (unknowingly about the interplay between `dplyr` and `haven`)](https://github.com/tidyverse/dplyr/issues/3108).

Now because the `labelled()` constructor is called when `select()`ing on dataframes, I was only confronted with the error message – which of course didn't make any sense to me at that time:
```R
library(dplyr)
df <- data_frame(logi_var)
df %>% select(logi_var)
#> Error: `x` must be a numeric or a character vector
```

Therefore my question: Is there any specific reason to not support labelled logical vectors?

And if not, my request: Please add support for it! :slightly_smiling_face:

**Comment by hadley** [comment]
Sorry, the `labelled` class is specifically to support SPSS/SAS/Stata labelled vectors. There are no plans to make it more general.

**Comment by salim-b** [comment]
> Sorry, the labelled class is specifically to support SPSS/SAS/Stata labelled vectors. There are no plans to make it more general.

Thanks for your answer!

I understand that the `labelled` class was originally created for that purpose. But besides being a means to retain all the information of those proprietary data formats when importing them in R, the `labelled` class also offers the general advantage of directly _displaying_ the metadata stored in it when viewing a dataframe in RStudio. I think it would be beneficial to have this functionality for logical vectors, too. I guess the necessary changes to support this would be rather small, right?
