### ISSUE TITLE
Writing SPSS files does not correctly set nominal measure

### ISSUE THREAD

**Issue by jeremiahsb** [tidyverse/haven#317]
The company I work for uses SPSS extensively. There are data transformations which are considerably easier in R. So my setup is to read sav files into R, manipulate them, then save them back to sav files for other users. In doing this, I've noticed that the original sav file will have variables which are set to nominal in the measure attribute in SPSS are switched to scale when creating a new sav file. Based on #133 it looks like this should be supported, though it was stated that round trip was beyond the scope of Haven. Attached is a reprex.

[Reprex.zip](https://github.com/tidyverse/haven/files/1379941/Reprex.zip)

**Comment by hadley** [comment]
Can you please provide a reprex inline?

**Comment by jeremiahsb** [comment]
Sorry about that. Here is the reprex to be used with the attached zip file above:

`library(haven)

exampleDat <- read_sav("Measure Issue Example.sav")

write_sav(exampleDat, "Exported Measure Issue Example.sav")`

In the "Measure Issue Example.sav" file, you'll see the "someTestVariable" variable has a measure set to Nominal. After running through the import/export as listed above, the measure is now set as Scale.

**Comment by hadley** [comment]
Could you please rework your reproducible example to use the [reprex package](http://reprex.tidyverse.org) ? That makes it easier to see both the input and the output, formatted in such a way that I can easily re-run in a local session.

**Comment by jeremiahsb** [comment]
I've been looking at the examples for using the reprex package and I'm not sure how they apply given that I haven't been able to find a way to see the Measure attribute. In the code below it shows the attributes of the sample dataset after having been imported into R via Haven, but there is no attribute for Measure.

Unfortunately, I do not know C, so I could be overlooking something, but when looking at DfReader.cpp I don't see any references to the readstat_measure_e that are present in DfWriter.cpp.

`library(reprex)
library(haven)

exampleDat <- read_sav("Measure Issue Example.sav")

dput(exampleDat)
#> structure(list(someTestVariable = structure(c(1, 2, 0, NA, 1, 
#> 2), label = "An example variable", format.spss = "F1.0", class = "labelled", labels = structure(c(0, 
#> 1, 2), .Names = c("No", "Yes", "Maybe")))), .Names = "someTestVariable", class = c("tbl_df", 
#> "tbl", "data.frame"), row.names = c(NA, -6L))

write_sav(exampleDat, "Exported Measure Issue Example.sav")`

**Comment by hadley** [comment]
Ok, after carefully reading through your prose I think this is currently out of scope for haven - currently haven completely ignores the measure attribute on both read and write.
