### ISSUE TITLE
Read xpt files generated by PROC CPORT in SAS

### ISSUE THREAD

**Issue by pitla1** [tidyverse/haven#321]
I am reposting an earlier post (as a new issue).. deleted the earlier post..

I received an xpt file which was  generated in SAS using PROC CPORT procedure. Can haven's "read_xpt" read such transport files? I am unable to read such xpt file with any of the available packages like Hmisc, SASxport, foreign, haven. Also, in windows version of R (version 3.4.0), 

Any suggestions/solutions/workarounds using R would be highly appreciated. Of course, I can SAS for workarounds...

**Comment by hadley** [comment]
Have you tried? Haven should be able to read any xpt file that follows the spec.
