### ISSUE TITLE
read_dta The provided note is too long for the file format.

### ISSUE THREAD

**Issue by rubenarslan** [tidyverse/haven#322]
The problem disappears if I open this file with Stata 13 and resave, so I assume it's something to do with later versions, but I don't have a later version to make a reprex (and can't share the original file). Sorry that I don't have a reprex, but I was hoping the error message is a clear enough hint.
Would already be much better, if it didn't hard-fail but just truncated those notes.

I tried rebuilding haven with the newest ReadStat, but failed.

> bioage17 = read_dta("SOEP-CORE_v32.1_stata_bilingual/bioage17.dta")
Error in df_parse_dta_file(spec, encoding) : 
  Failed to parse SOEP-CORE_v32.1_stata_bilingual/bioage17.dta: The provided note is too long for the file format.
> traceback()
4: stop(list(message = "Failed to parse /Users/rubenarslan/research/data/SOEP/SOEP-CORE_v32.1_stata_bilingual/bioage17.dta: The provided note is too long for the file format.", 
       call = df_parse_dta_file(spec, encoding), cppstack = list(
    ...
3: .Call("haven_df_parse_dta_file", PACKAGE = "haven", spec, encoding)
2: df_parse_dta_file(spec, encoding)
1: read_dta("SOEP-CORE_v32.1_stata_bilingual/bioage17.dta")

**Comment by hadley** [comment]
Unfortunately without the original file (or some file that exhibits the same problem) there's no way to fix this problem.

**Comment by rubenarslan** [comment]
I was never able to get permission to share a file that has these problems, nor to generate one myself. Nevertheless, the newest haven fixed this somehow.
