### ISSUE TITLE
read_dta can't read ´(\xb4) character

### ISSUE THREAD

**Issue by cimentadaj** [tidyverse/haven#325]
Reading the `dta` files from the European Social Survey raises a warning reading the ´(\xb4) character. However, `read_spss` does the job fine. To download the data briefly sign up with your email [here](http://www.europeansocialsurvey.org/user/new). The script below downloads the data and saves to `tempdir()`. Remember to replace `your_email` with your email in the functions `ess_rounds`

```r
library(haven)
devtools::install_github("cimentadaj/ess", ref = "dev_branch") # To download ess data from R
library(ess)

# Replace email with your registered email
ess_rounds(7, your_email = your_email, only_download = TRUE, output_dir = tempdir(), format = "stata")
ess_rounds(7, your_email = your_Email, only_download = TRUE, output_dir = tempdir(), format = "spss")

stata_path <- list.files(tempdir(), recursive = TRUE, full.names = TRUE, pattern = ".dta")
spss_path <- list.files(tempdir(), recursive = TRUE, full.names = TRUE, pattern = ".sav")

seven_dta <- read_dta(stata_path)
str(seven_dta$prtvtcfi)
#> Class 'labelled'  atomic [1:40185] NA NA NA NA NA NA NA NA NA NA ...
#>   ..- attr(*, "label")= chr "Party voted for in last national election, Finland"
#>   ..- attr(*, "format.stata")= chr "%10.0g"
#>   ..- attr(*, "labels")= Named num [1:22] 1 2 3 4 5 6 7 8 9 10 ...
#>   .. ..- attr(*, "names")=
#> Error in strtrim(encodeString(object, quote = "\"", na.encode = FALSE), : invalid multibyte string at '<b4>s P<61>rty (SPP)"'

seven_spss <- read_spss(spss_path)
str(seven_spss$prtvtcfi)
#> Class 'labelled'  atomic [1:40185] NA NA NA NA NA NA NA NA NA NA ...
#>   ..- attr(*, "label")= chr "Party voted for in last national election, Finland"
#>   ..- attr(*, "format.spss")= chr "F2.0"
#>   ..- attr(*, "display_width")= int 10
#>   ..- attr(*, "labels")= Named num [1:22] 1 2 3 4 5 6 7 8 9 10 ...
#>   .. ..- attr(*, "names")= chr [1:22] "The National Coalition Party" "The Swedish People´s Party (SPP)" "The Centre Party" "True Finns" ...
```

`read_dta` has problems reading` "´"`. More specifically `attr(seven_dta$prtvtcfi, "labels")[2]`
In case you're wondering, `ess_rounds` simply downloads the `dta`, nothing is done on the data. The problem is also raised by other users [here](https://github.com/cimentadaj/ess/issues/11)

**Comment by hadley** [comment]
Have you tried specifying the encoding of the file, per the note in the documentation of `read_dta()`?

If that doesn't help, it would be extremely helpful if you could produce a reprex that doesn't require me to install a package and sign up for an account.

**Comment by cimentadaj** [comment]
Their website has not information on the encoding for that wave so I'm not sure if it's different from UTF-8. I try Win1252 in the reprex. Download the data from [here](https://files.fm/u/zbqa3wv4)
```
library(haven)
#> Warning: package 'haven' was built under R version 3.4.1

ex <- read_dta("st_ex.dta")
str(ex$prtvtcfi)
#> Class 'labelled'  atomic [1:40185] NA NA NA NA NA NA NA NA NA NA ...
#>   ..- attr(*, "label")= chr "Party voted for in last national election, Finland"
#>   ..- attr(*, "format.stata")= chr "%10.0g"
#>   ..- attr(*, "labels")= Named num [1:22] 1 2 3 4 5 6 7 8 9 10 ...
#>   .. ..- attr(*, "names")=
#> Error in strtrim(encodeString(object, quote = "\"", na.encode = FALSE), : invalid multibyte string at '<b4>s P<61>rty (SPP)"'


ex <- read_dta("st_ex.dta", encoding = "Win 1252")
#> Error in df_parse_dta_file(spec, encoding): Failed to parse /Users/cimentadaj/Downloads/try/st_ex.dta: File has an unsupported character set.
```

**Comment by cimentadaj** [comment]
I think this might be an encoding problem as you suggest. The label problem comes from Finnish Political parties which also have Swedish names. However on Stata, there's no error but fills it with "The Swedish People¥s Party (SPP)"

**Comment by hadley** [comment]
@evanmiller more evidence that I don't understand the encoding API:

``` r
library(haven)

# Default encoding
ex <- read_dta("~/Desktop/st_ex.dta")
bad <- names(attr(ex$prtvtcfi, "labels"))[[2]]

bad
#> [1] "The Swedish People\xb4s Party (SPP)"
iconv(bad, from = "ISO-8859-1", to = "UTF-8")
#> [1] "The Swedish People´s Party (SPP)"

# Supply ISO-8859-1
ex <- read_dta("~/Desktop/st_ex.dta", encoding = "ISO-8859-1")
bad <- names(attr(ex$prtvtcfi, "labels"))[[2]]

# This value doesn't seem to change
bad
#> [1] "The Swedish People\xb4s Party (SPP)"
iconv(bad, from = "ISO-8859-1", to = "UTF-8")
#> [1] "The Swedish People´s Party (SPP)"
```

I'm setting the parser encoding with `readstat_set_file_character_encoding()`, and I mark the value returned from `readstat_string_value()` with `Rf_mkCharCE(str_value, CE_UTF8)` so that R know it's UTF-8.

**Comment by evanmiller** [comment]
This appears to be a bug in ReadStat's DTA parser. I'll get it fixed soon.

**Comment by evanmiller** [comment]
Should be fixed in https://github.com/WizardMac/ReadStat/commit/607d159b32bcaeb3621031a0a06ff0a3ea0185b6

**Comment by hadley** [comment]
Awesome - thanks! I'm going to roll this up into a release. Any products of SAS investigation can go to a future release.

**Comment by evanmiller** [comment]
@hadley Did you verify the fix? I think the file is supposed to be UTF-8 but is actually Win-1252 (i.e. `encoding` must be specified even with the patch)
