### ISSUE TITLE
labelled sensitive to labels ordering in Stata

### ISSUE THREAD

**Issue by kuriwaki** [tidyverse/haven#327]
When defining a labelled object, the label-value vector needs to be sorted by its numerical values, or else Stata cannot correctly read the label:

``` r
library(haven)
suppressPackageStartupMessages(library(dplyr))

labs <- c(Democrat = 1, Republican = 2, Independent = 3) # named vector

lbl <- tibble(pid3 = labelled(1L:3L, labs)) # both sorted
lbl_num <- tibble(pid3 = labelled(3L:1L, labs)) # values not sorted
lbl_lab <- tibble(pid3 = labelled(3L:1L, labs[c(1, 3, 2)])) # labels not sorted

write_dta(lbl, "foo.dta")
write_dta(lbl_num, "foo_num.dta")
write_dta(lbl_lab, "foo_lab.dta") # this one gets misread in Stata
```

When I open `foo_lab.dta` in Stata, I get
```

. tab pid3

       pid3 |      Freq.     Percent        Cum.
------------+-----------------------------------
   Democrat |          1       33.33       33.33
          2 |          1       33.33       66.67
Independent |          1       33.33      100.00
------------+-----------------------------------
      Total |          3      100.00
```
So the label for `2` dropped out. Is this a bug?

This error does not occur when the dta file is read into R by `read_dta` and analyze it there; only when I open it in Stata.

**Comment by hadley** [comment]
@evanmiller any thoughts on whether this is the responsibility of haven or readstat?

**Comment by evanmiller** [comment]
@hadley ReadStat should probably order the labels the way that Stata expects before writing.

**Comment by evanmiller** [comment]
@hadley Try pulling in this change: https://github.com/WizardMac/ReadStat/commit/f4d8706fc37d64decb67cb9eb4bb001365c06f48

**Comment by hadley** [comment]
@kuriwaki please try with the latest dev version.

**Comment by kuriwaki** [comment]
@hadley works great. Thank you.
