### ISSUE TITLE
Member name in SAS xport file generated by write_xpt is hard coded to "DATASET"

### ISSUE THREAD

**Issue by sasutils** [tidyverse/haven#328]
There is no way to tell the write_xpt function what member name to use for the SAS transport file that it generates.  Instead is it generating a header record that has the member name hard coded as "DATASET ". 

So if I use this line to write the data frame named ABC to a file named 'abc.xpt' 
   write_xpt(ABC,"abc.xpt")
and then try to read it into SAS I will end up with a dataset named DATASET instead of one named ABC.

The user should be able to specify the member name that they want their SAS dataset to have.  It would be easier to use if the default member name used was based on the input object's name, or perhaps the name of the target file.

**Comment by hadley** [comment]
@evanmiller looks like this is currently hardcoded into `sas7bdat_emit_header`. Any chance we could have it as a setting?

**Comment by sasutils** [comment]
My preference would be use the name of the file being written as the member
name being written to the SAS xport file. Especially as I don't think this
package supports writing multiple members into a single xport file.  So if
I write the a file name 'class.xpt' then the member name in the internal
header record would be 'class'.  It is not clear to me if the name of file
being written is currently available to the function that writes the
header.

Another choice for default would be use the name of the object being
exported.  Also not clear if that name is currently available to the
function.

Adding a user setting would be best.  Would be nice to allow, in addition
to being able to specify the name, an easy way to tell it to use the name
of the file being written or the object being exported.
For user continuity might want to have new setting default to the current
hardcoded value.  Not sure how many use cases are out there that currently
are built around the current hardcoded member name.

For version 5 transport files the name must be 1 to 8 characters. First can
be underscore or letter. Rest can also include digits.  SAS is actually
happy to read mixed case member names from SAS V5 XPORT files, but it only
generates uppercase member names.  For version 8 transport files the names
can be up to 32 characters and can include more characters, although there
might still be some special characters that are not allowed.

**Comment by evanmiller** [comment]
This could be added as a setting in ReadStat.

XPORT file can include both the (symbolic) member name and the (plain language) file label. It's not clear to me if SAS7BDAT files also have both fields.

**Comment by sasutils** [comment]
Both Xport files and SAS datasets can store member names and member labels.  The V5 transport files the member names are limited to 8 bytes and member label is limited to 40 bytes. For V8 transport files and SAS datasets (sas7bdat format) can use 32 byte member names and 256 byte member labels.

**Comment by evanmiller** [comment]
On the ReadStat side this is available now through `readstat_writer_set_table_name`:

```C
readstat_error_t readstat_writer_set_table_name(readstat_writer_t *writer, const char *table_name)
```

I'm open to another name for the function. SAS variously refers to this string as the member name, table name, and data set name. (`set_data_set_name` seemed liable to cause confusion.)

**Comment by hadley** [comment]
`set_dataset_name()` could be a possible option, but I think `table_name` is fine

**Comment by evanmiller** [comment]
Might change the new `metadata` type to `dataset` and then do something like

```C
readstat_dataset_get_name()
readstat_dataset_get_label()
readstat_dataset_get_var_count()
readstat_dataset_get_row_count()
```

Then on the write side

```C
readstat_writer_set_dataset_name() // formerly table_name
readstat_writer_set_dataset_label() // formerly file_label
```

**Comment by hadley** [comment]
@sasutils I think this should now work, but I have no easy way to check. Can you please try it out?

**Comment by sasutils** [comment]
Sure.  Is there any special syntax needed to tell it what name to using
inside the generated XPORT file?
Or will it now just try to name it based on the dataframe that is being
exported?

**Comment by hadley** [comment]
See the docs for the `name` argument, and let me know if they're not clear.

**Comment by sasutils** [comment]
Looks good. I was able to create XPORT from R and read with SAS 9.4 on Windows.

When NAME= not used then it used the base name of the output file.
Or I could use the NAME= and set a different name.
