### ISSUE TITLE
labelled class clashes with Hmisc

### ISSUE THREAD

**Issue by ewenharrison** [tidyverse/haven#329]
https://github.com/tidyverse/haven/issues/86

I'm still having issues with this. I have a data.frame with variables of class `labelled` which I would rather keep. There is still a `haven` conflict. Any ideas appreciated. I'm not using `haven` but it loads with `tidyverse` hence issue. 

```
# Simple linear regression
data(mtcars)
lm(mpg~cyl, data=mtcars) # Works as expected

# Add attribute
class(mtcars$mpg) = c("labelled",class(mtcars$mpg))
lm(mpg~cyl, data=mtcars) # Works as expected

library(haven)
lm(mpg~cyl, data=mtcars) #Error: `x` and `labels` must be same type
```

**Comment by hadley** [comment]
Where are the labelled variables coming from? 

You can't generally expect to add an arbitrary class to variables and expect things to work, but maybe you just did that to minimise the reprex?

**Comment by ewenharrison** [comment]
`Hmisc::label()`

**Comment by hadley** [comment]
I don't think there's a great short term fix for this - the right thing to do is to make the class name more unique (i.e. `haven_labelled`), but that is likely to break downstream packages. I'll explore this next time we do a major release.

**Comment by harlananelson** [comment]
From lrm examples.
```
cholesterol    <- rnorm(n, 200, 25)
label(cholesterol)    <- 'Total Cholesterol'
ch <- cut2(cholesterol, g=40, levels.mean=TRUE) # use mean values in intervals
```
Same error.

**Comment by ewenharrison** [comment]
I think this issue is resolved? I am no longer getting the issue.

**Comment by ewenharrison** [comment]
Apologies, me too with that reprex.

**Comment by gforge** [comment]
This bug can be tricky, some packages depend on other packages that force-load haven. I've recently debugged: AER -> car -> rio -> haven

I think this is something that the CRAN group should look into - each package should define the S3 classes and state which S3 classes it imports. Until then, please consider fixing this. I just wasted about 1-2 hours...
