### ISSUE TITLE
Parse fails for icpsr.umich.edu SAS file

### ISSUE THREAD

**Issue by javierluraschi** [tidyverse/haven#330]
Passing along question from https://support.rstudio.com/hc/en-us/articles/218611977-Importing-Data-with-RStudio...

1) Downloaded "DS1: Collaborative Psychiatric Epidemiology Surveys (CPES), 2001-2003" in SAS format from this website where: http://www.icpsr.umich.edu/icpsrweb/ICPSR/studies/20240.

2) Clicked IMPORT DATASET => format SAS=> tried importing .sas Data files from that survey.

3) Keep getting "Error: Is this valid SAS, SPSS, STATA?"

For `haven`, the equivalent repro is to download this file and run:

```r
read_sas("~/Downloads/ICPSR_20240/DS0001/20240-0001-Supplemental_syntax.sas")
```
```
Error in df_parse_sas_file(spec_data, spec_cat, encoding = encoding, cols_only = cols_only) : 
  Failed to parse /Users/javierluraschi/Downloads/ICPSR_20240/DS0001/20240-0001-Supplemental_syntax.sas: Invalid file, or file has unsupported features.
```

Not sure if the SAS file is valid nor supported.

**Comment by hadley** [comment]
@javierluraschi do we have any evidence that this file opens in SAS?

@evanmiller do you want to take a look?

**Comment by evanmiller** [comment]
Haven reads `.sas7bdat` (SAS binary files), not `.sas` (SAS syntax files)
