### ISSUE TITLE
Feature request: function to write multiple variable labels

### ISSUE THREAD

**Issue by philmikejones** [tidyverse/haven#331]
Dear Hadley et al,

Would you consider implementing a function into Haven that would allow the writing/updating of multiple variable labels at once.

If I have one or two variables I would just manually update the attributes one at a time. If I have multiple variables to update and a vector of labels my current solution is to use `Hmisc::label()`. This works adequately but it would be nice to have a native `Haven` function. It also looks like `Hmisc` plans to use `Haven` for reading SPSS files in future (https://github.com/harrelfe/Hmisc#to-do).

Thanks.

**Comment by philmikejones** [comment]
I've also just discovered that the output of `Hmisc::label()` is not always compatible with the `haven::write_sav()` function, which gave me this error the most recent time I used it:

```
Error in write_sav_(data, normalizePath(path, mustWork = FALSE))
Not compatible with STRSXP
```

**Comment by hadley** [comment]
Not at this time - if we provide more helpers for variable labelling they are likely to live elsewhere.

**Comment by philmikejones** [comment]
No worries, thanks for taking the time to reply
