### ISSUE TITLE
Add pillar printing for the labelled class

### ISSUE THREAD

**Issue by gergness** [tidyverse/haven#340]
I think the labelled class would benefit from having a print method from the pillar package. For labelled values it would be nice to show the label with subtle styling and the special NA values could also be marked as well.

If you're interested, I'm happy to make a first attempt in a PR.

**Comment by hadley** [comment]
Sure, sounds great!

**Comment by elbersb** [comment]
Would this also fix this strange printing issue that occurs now when printing a tibble with a `labelled` column? See below for an example, where the 1 is surrounded by quotes. This only seems to happen when the numbers have different numbers of digits (see second example).

``` r
d <- tibble::tibble(s = haven::labelled(c(1, 10), labels = c("A" = 1, "B" = 10)))
d
#> # A tibble: 2 x 1
#>   s        
#>   <dbl+lbl>
#> 1 " 1"     
#> 2 10
d <- tibble::tibble(s = haven::labelled(c(1, 2), labels = c("A" = 1, "B" = 2)))
d
#> # A tibble: 2 x 1
#>   s        
#>   <dbl+lbl>
#> 1 1        
#> 2 2
```

Created on 2018-09-04 by the [reprex
package](http://reprex.tidyverse.org) (v0.2.0).

**Comment by gergness** [comment]
Oh yeah, agree that this should be fixed. I don't think the design is final yet, but the current implementation in #390 has pretty good behavior.

``` r
d <- tibble::tibble(s = haven::labelled(c(1, 10), labels = c("A" = 1, "B" = 10)))
d
#> # A tibble: 2 x 1
#>   s        
#>   <dbl+lbl>
#> 1  1 [A]   
#> 2 10 [B]


# Can also get just the values with correct spacing by setting option
options("haven.show_pillar_labels" = FALSE)
d
#> # A tibble: 2 x 1
#>           s
#>   <dbl+lbl>
#> 1         1
#> 2        10
```

Created on 2018-09-08 by the [reprex package](http://reprex.tidyverse.org) (v0.2.0).

**Comment by elbersb** [comment]
The PR looks great!
