### ISSUE TITLE
read_sas error: unsupported character set

### ISSUE THREAD

**Issue by beew** [tidyverse/haven#345]
Hi, 
I am having problem reading one sas7bdat file with sas_read() :
```
Error in df_parse_sas_file(spec_data, spec_cat, encoding = encoding, catalog_encoding = catalog_encoding,  : 
  Failed to parse /home/beew/test.sas7bdat: File has an unsupported character set
```
the R package sas7bdat can open it with read.sas7bdat() though.

The culprit turns out to be one mostly empty column with a few entries which have form like:
```
7 = Site Error - Wrong Site Dispensation
```
Removing the column (with SAS) then read_sas() can read the file just fine.

R 3.4.3, haven 1.1.1, OS is Ubuntu Linux.

**Comment by hadley** [comment]
Can you please provide a minimal reprex (reproducible example)? The goal of a reprex is to make it as easy as possible for me to recreate your problem so that I can fix it: please [help me help you](https://nypdecider.files.wordpress.com/2014/08/help-me-help-you.gif)! 

If you've never heard of a reprex before, start by reading "[What is a reprex](http://reprex.tidyverse.org/articles/reprex.html)", and follow the advice further down the page. Please make sure your reprex is created with the reprex package as it gives nicely formatted output and avoids a number of common pitfalls.

**Comment by evanmiller** [comment]
@beew At a minimum, please provide a link to the problematic file. Thanks!

**Comment by beew** [comment]
The file is confidential so unfortunately I can't provide it. But the culprit is exactly as I said, a single column which is mostly blank except for a few rows where you have entries like
```
7 = Site Error - Wrong Site Dispensation

```
Those appear to be formating information about the numerical columns  put in a comment since whoever made the sas file doesn't know proc format apparently. The "Column Attributes" in SAS is that this column is character and has format and informat $200. (length 200)

**Comment by hadley** [comment]
Unfortunately there's not much we can do without the file.  Could you make a subset that contained only that column and just a couple of rows?

**Comment by beew** [comment]
I am thinking of that, and changing the entries into gibberish to protect confidential info, I will ask my employer and if it is no problem I will do that.

**Comment by ShishirShakya** [comment]
The following code downloads the sas file from the public database. I have the same issue. 

# Clean the global enviroment
rm(list = ls())
dev.off(dev.list()['RStudioGD'])
#######################################
## Part-1 : Load all the required packages
#######################################
ipak <- function(pkg){
  new.pkg <- pkg[!(pkg %in% installed.packages()[, 'Package'])]
  if (length(new.pkg)) 
    install.packages(new.pkg, dependencies = TRUE, repos = 'http://cran.us.r-project.org')
  sapply(pkg, require, character.only = TRUE)
}
ipak(c('rstudioapi', 'haven'))

#######################################
## Part-2 : Setup Working Directory
#######################################
path <- dirname(rstudioapi::getActiveDocumentContext()$path)
setwd(path)

dir.create(file.path(path, 'rawdata'))

if (file.exists('rawdata/hosp10-sas.zip') == FALSE) { # get the zip file
  download.file('http://downloads.cms.gov/files/hcris/hosp10-sas.zip', destfile = 'rawdata/hosp10-sas.zip', mode='wb')
}

dir.create(file.path(path, 'rawdata/unzip'))
unzip('rawdata/hosp10-sas.zip', exdir = 'rawdata/unzip')

df2010 <- haven::read_sas(data_file = 'rawdata/unzip/prds_hosp10_yr2010.sas7bdat')

**Comment by evanmiller** [comment]
@ShishirShakya I get a different error with the file provided ("File has unsupported compression scheme.")
