### ISSUE TITLE
write_xpt() does not create file that read.xport() can read

### ISSUE THREAD

**Issue by hadley** [tidyverse/haven#347]
``` r
library(haven)
path <- tempfile()
write_xpt(mtcars, path)
foreign::read.xport(path)
#> Error in lookup.xport(file): file not in SAS transfer format
```

@evanmiller If it helps the source code for `read.xport()` can be found by downloading [the foreign package](https://cran.r-project.org/src/contrib/foreign_0.8-69.tar.gz) then looking in `src/SASxport.c`

**Comment by evanmiller** [comment]
`foreign` can't read V8 files. This works fine:

```R
write_xpt(mtcars, path, version = 5)
```

**Comment by hadley** [comment]
DOH.
