### ISSUE TITLE
Ability to read standalone SAS formats (sas7bcat) without data file

### ISSUE THREAD

**Issue by jemus42** [tidyverse/haven#355]
For a project I'm working on I would have needed to read a SAS format `sas7bcat` file in R to create a table of labels. I was under the impression that I'd already done something like this a while ago and was surprised that `read_sas` does not support this.

TL;DR is/would it be possible to read a standalone `sas7bcat` format catalogue **without** doing so as a by-product of a SAS data file?  

I have dug through the internals of haven to look for the appropriate functions, but it doesn't seem to be possible to *only* read a format file.

**Comment by rogerjdeangelis** [comment]
I think you are out of luck

  WPS express (free version) cannot read SAS sas7bcats

  Only SAS7BDATS

      1. R       (open source)
      2. Python  (open source)
      3. WPS (free express edition - has nor limit on the size od SAS
datasets created by R) **

   Commercial ( I don't think any of these can read a (catalogs)sas7bcat
but you might want to check)

      4. StatTransfer
      5. DBMS Copy
      6. Carolina
      7. SPSS

   If you have a dataset with the formatname and all the outcomes in the
data you may be able to recreate the formats table.
   In R, Python and WPS

**Comment by rogerjdeangelis** [comment]
R does allow allow a format catalog option, but I never got it to work.

Even 64bit SAS cannot read a 32bit SAS format catlog.

On Tue, Feb 27, 2018 at 11:04 AM, Roger DeAngelis <rogerjdeangelis@gmail.com

**Comment by rogerjdeangelis** [comment]
I think you are out of luck

  WPS express (free version) cannot read SAS sas7bcats

**Comment by hadley** [comment]
@jemus42 yes, it should be possible in principle using the readstat C api, but it's would be very different to the rest of the haven so it's unlikely that I will ever work on it. I'd happily review a PR though.

**Comment by ofajardo** [comment]
@jemus42 @rogerjdeangelis In case this is still of interest, the python package [pyreadstat](https://github.com/Roche/pyreadstat) has the ability to read standalone sas7bcat files. 
In my hands however not all sas7bcat files are readable by readstat (see for example [this](https://github.com/WizardMac/ReadStat/issues/146))
