### ISSUE TITLE
read_dta stopped working on version 1.1.1 on Windows

### ISSUE THREAD

**Issue by m-sostero** [tidyverse/haven#356]
In the current version 1.1.1 of haven (https://github.com/tidyverse/haven/commit/5b77840a38817c61dc430bacc6904b7d59626818), and the development version (1.1.1.900), I can't `read_dta` files on Windows.
 
``` r
library(haven)
path <- system.file("examples", "iris.dta", package = "haven")
read_dta(path)
#> Error in df_parse_dta_file(spec, encoding) : object '_haven_df_parse_dta_file' not found
```
haven 1.1.0 (https://github.com/tidyverse/haven/commit/a7a08c096cc0c5916f993138eac10310abd7799f) works correctly.

**Comment by kuriwaki** [comment]
have you tried specifying the `encoding = 'latin1'` as an option, per #344 ?
