### ISSUE TITLE
Error: package or namespace load failed for ‘haven’ in dyn.load(file, DLLpath = DLLpath, …):

### ISSUE THREAD

**Issue by tidyx** [tidyverse/haven#363]
I am not able to open install the 'haven' packages. It gives me the following error:
```
*** copying figures
** building package indices
** installing vignettes
** testing if installed package can be loaded
Error: package or namespace load failed for ‘haven’ in dyn.load(file, DLLpath = DLLpath, ...):
unable to load shared object '/home/R/R/x86_64-redhat-linux-gnu-library/3.4/haven/libs/haven.so':
/home/R/R/x86_64-redhat-linux-gnu-library/3.4/haven/libs/haven.so:undefined symbol: libiconv
Error: loading failed
Execution halted
ERROR: loading failed
* removing ‘/home/R/R/x86_64-redhat-linux-gnu-library/3.4/haven’
Warning in install.packages :
installation of package ‘haven’ had non-zero exit status

The downloaded source packages are in
‘/tmp/Rtmp4y5PTv/downloaded_packages’
```
I have also tried to remove and re-install it, but without success.
```
install.packages('haven', dep = TRUE)
```

**Comment by HoseinHashemi** [comment]
Try specifying the repository. Sometimes install.packages cannot find the right repository.

**Comment by MajoroMask** [comment]
For people who googled to here, you may try this:
`withr::with_makevars(c(PKG_LIBS = "-liconv"), install.packages("haven"), assignment = "+=")`
It seems someone create a typo in somewhere.

**Comment by zhuangfjnu** [comment]
Thank MajoroMask!
very useful information!

**Comment by inesHellmann** [comment]
Thanx a MajorMask! This was driving me crazy.

**Comment by sgmccalla** [comment]
Thank you @MajoroMask! I was able to install haven finally.

**Comment by yangkl0909** [comment]
Thank you @MajoroMask!  Very useful suggestion.

**Comment by marcora** [comment]
Why is this issue closed? I specify the right repository and I still have the same problem!
Doing what MajoroMask suggested fixes the issue temporarily, but this is hardly resolved!

**Comment by hadley** [comment]
Because I didn’t know it was a problem — generally comments on closed issues go unread.

**Comment by MaxGhenis** [comment]
I hit the same error with the `readxl` package after resolving the `haven` one with @MajoroMask's solution. Applying the same to `readxl` worked:
`withr::with_makevars(c(PKG_LIBS = "-liconv"), install.packages("readxl"), assignment = "+=")`

**Comment by arinbasu** [comment]
I had the same problem, I solved it by removing haven and reinstalling tidyverse.
Now it works (fingers crossed).
So I did:
`conda remove r-haven`
conda will remove haven but will also ask to remove r-essentials and r-tidyverse
Remove these as well.
Then re-install tidyverse, with
`conda install r-tidyverse`
(This time do not specify conda-forge, do not use the option -c conda-forge)
A newer version of haven will be installed and this solved my problem.

**Comment by hadley** [comment]
If you use conda, you *must* use conda to install everything else. You can not mix `install.packages()` and `conda install`

**Comment by aakhmetz** [comment]
I mix conda install and install.packages() quite a lot, and no problem

**Comment by inesHellmann** [comment]
I just updated all packages on R 3.6.0 on our centos server -- just R, no conda. When installing haven and readxl, I am still getting the same error message as a year ago:  undefined symbol: libiconv
which can be fixed by the MajoroMask suggestion.
