### ISSUE TITLE
read_dta: Unable to allocate memory.

### ISSUE THREAD

**Issue by protogeezer** [tidyverse/haven#368]
I'm trying to convert a 2.05GB Stata .dta file (created from the ECLS2011-k4 study childk4p.dat file - along with the provided Stata dictionary and do file) to Rds. With master,  the result is:

============
> library(haven)
> a <- read_dta("childk4p.dta")
Error: unable to allocate memory len: 6883203 <<-- a bit of debugging code I added
Error in df_parse_dta_file(spec, encoding) : 
  Failed to parse /Users/sjbespa/vams/data/ECLSK11-k4/orig/childK4p.dta: Unable to allocate memory.
Called from: df_parse_dta_file(spec, encoding)
============

Bumping MAX_MALLOC_SIZE in readstat_malloc.c seems to work around the problem. Maybe that code should check for an error code from malloc/calloc and then deal with it rather than have a fixed maximum?

Stephen

**Comment by hadley** [comment]
Please try again with the development version of haven. If that doesn't help, please file a new issue with a link to the file you're trying to open.
