### ISSUE TITLE
Feature request: read_dta variable and value label language

### ISSUE THREAD

**Issue by rbirkelbach** [tidyverse/haven#369]
Hello,

Stata provides the option to save the variable and language labels in multiple languages. However, to my knowledge, read_dta/read_stata does not provide functionality to specify which language it should load. The package readstata13 provides functionality to select the language from a given dta file. This package can be downloaded here https://github.com/sjewo/readstata13 .

Attached you find a toy dataset which provides multi language labels. It would be great if you'd find time to implement this feature.

All the best,
Robert
[toydata.dta.zip](https://github.com/tidyverse/haven/files/1924104/toydata.dta.zip)

**Comment by hadley** [comment]
@evanmiller any support for this in readstat?

**Comment by evanmiller** [comment]
@hadley There is no support in ReadStat. This feature is not documented by Stata in their DTA specification.

**Comment by hadley** [comment]
Since it's not documented, the chances of us implementing this are slim, so I'm going to close this issue.

**Comment by rbirkelbach** [comment]
@evanmiller @hadley Here you can find the relevant part in the DTA specification. Although it's -- as you already stated -- not explicitely documented with regards to language characteristics of value labels the characteristics part of the specification may give some insight? https://www.stata.com/help.cgi?dta#characteristics 

Also, this code of readstata13 might provide some insights on ways to implement this. https://github.com/sjewo/readstata13/blob/4c122aa52edbe9aa8bbbeded9a985e156eceab41/src/read_dta.cpp#L335
