### ISSUE TITLE
read_*() does not work for special characters in file path

### ISSUE THREAD

**Issue by strengejacke** [tidyverse/haven#371]
I can't provide a reprex, I think, but the message should be clear. The problem occurs when the file path contains, e.g., German Umlauts:

```
test <- read_stata("~/CloudStation/R, diverse/Datensätze zum debuggen/GLES_Vorwahlquerschnitt_ZA5700_v1-0-0.dta")

 Error in df_parse_dta_file(spec, encoding) : 
  Failed to parse C:/Users/Daniel/Documents/CloudStation/R, diverse/DatensÃ¤tze zum debuggen/GLES_Vorwahlquerschnitt_ZA5700_v1-0-0.dta: Unable to open file. 
4.
stop(structure(list(message = "Failed to parse C:/Users/Daniel/Documents/CloudStation/R, diverse/DatensÃ¤tze zum debuggen/GLES_Vorwahlquerschnitt_ZA5700_v1-0-0.dta: Unable to open file.", 
    call = df_parse_dta_file(spec, encoding), cppstack = structure(list(
        file = "", line = -1L, stack = "C++ stack not available on this system"), class = "Rcpp_stack_trace")), class = c("Rcpp::exception", 
"C++Error", "error", "condition"))) 
3.
df_parse_dta_file(spec, encoding) 
2.
haven::read_dta(file = path, encoding = enc) at read_write.R#226
1.
read_stata("~/CloudStation/R, diverse/Datensätze zum debuggen/GLES_Vorwahlquerschnitt_ZA5700_v1-0-0.dta") 
```

Moving the file to a directory without German Umlauts in the file path works.

**Comment by tzoltak** [comment]
Having the same problem (with `read_spss()` and with Polish special characters).

**Comment by hadley** [comment]
Would be great if someone could confirm this is fixed in the devel version.

**Comment by strengejacke** [comment]
My initial issue is solved in the current dev-version! Works for me.

**Comment by tzoltak** [comment]
It also works for me!

**Comment by bajbaj** [comment]
Import via syntax works, but "import dataset" dialogue in RStudio still gives an error message:

![2018-06-22_140748](https://user-images.githubusercontent.com/39564140/41775817-b6dc7c74-7625-11e8-9896-78334d015369.png)

Windows 10, R 3.5.0, RStudio 1.1.453, haven_1.1.1.9000
