### ISSUE TITLE
`read_spss` can't parse `.por` file.

### ISSUE THREAD

**Issue by cimentadaj** [tidyverse/haven#373]
You can download the `.por` file from [here](https://uploadfiles.io/0wyol).  It will be available for 30 days starting today.

```r
library(haven) # latest CRAN version 1.1.1
read_spss("C:\\Users\\cimentadaj\\Downloads\\ESS1_SI_SDDF.spss/ESS1_SI_SDDF.por")
#> Error in df_parse_por_file(spec, user_na): Failed to parse ESS1_SI_SDDF.por: Unable to read from file.
```

I can read this with SPSS with a warning before reading. Picture below.
![pic_spss](https://user-images.githubusercontent.com/8180025/39958259-e811add6-5600-11e8-8a4b-245c0a6ec8d7.png)

Note that `read_por` doesn't have an encoding argument (not even in the dev version). If I do download the dev version then the reprex shows another error.

```r
library(haven)
read_spss("C:\\Users\\cimentadaj\\Downloads\\ESS1_SI_SDDF.spss/ESS1_SI_SDDF.por")
#> Error in read_por(file, user_na = user_na): object 'encoding' not found
```

**Comment by hadley** [comment]
Can you please upload the file to GitHub?

**Comment by cimentadaj** [comment]
There it is: [ESS1_SI_SDDF.spss.zip](https://github.com/tidyverse/haven/files/2119029/ESS1_SI_SDDF.spss.zip)

**Comment by hadley** [comment]
The extension appears to be incorrect: `read_sav("ESS1_SI_SDDF.por")` works for me.
