### ISSUE TITLE
Unable to allocate memory  in read_sas file catalog file 

### ISSUE THREAD

**Issue by alimanager** [tidyverse/haven#375]
Error in df_parse_sas_file ... failed to parse *.sas7bcat :Unable to allocate memory .
it have a size limit for SAS catalog_file ...?  or another issue because read_sas can read the sas data file normaly without catalog.
Nb : sasb7cat file has 500 MB

**Comment by hadley** [comment]
Should be fixed in development version. If installing from GitHub doesn't help, please file a new issue with a reproducible example.
