### ISSUE TITLE
encoding issue continued

### ISSUE THREAD

**Issue by frankcsliu** [tidyverse/haven#376]
Hi, I noticed that the argument  "enc"  was removed, indicating a better detection mechanism for character encoding. But unfortunately, it is not working when I tried again to read in a data set with Big5 encoding and felt frustrated about finding nowhere to specify encoding like using foreign::read.spss(). 

Thanks in advance for helping us out. For replicating the issue: 
https://drive.google.com/drive/folders/1PkRTppDW8DBs6m9wO3z8298mRzqi62n0?usp=sharing

**Comment by batpigandme** [comment]
Could you please turn this into a self-contained [reprex](http://reprex.tidyverse.org/) (short for minimal **repr**oducible **ex**ample) so we can take a look at the input and output without running the code separately? 

If you've never heard of a reprex before, you might want to start by reading the tidyverse.org [help page](https://www.tidyverse.org/help/).

Right now the best way to install reprex is:
```r
# install.packages("devtools")
devtools::install_github("tidyverse/reprex")
```
If you run into problems with access to your clipboard, you can specify an outfile for the reprex, and then copy and paste (or drag and drop) the contents here.

```r
reprex::reprex(input = "fruits_stringdist.R", outfile = "fruits_stringdist.md")
```

Thanks

**Comment by hadley** [comment]
I've closed this issue due to lack of requested reprex. If you still care about this bug, please open a new issue with a reprex.
