### ISSUE TITLE
Problem downloading library haven

### ISSUE THREAD

**Issue by kkumari1** [tidyverse/haven#377]
This is the error I have been getting. My R studio and R are both updates to the latest versions. 

Warning in install.packages :
  installation of package ‘tibble’ had non-zero exit status
ERROR: dependency ‘tibble’ is not available for package ‘haven’
* removing ‘/Users/kritikakumari/Library/R/3.4/library/haven’

**Comment by hadley** [comment]
Try installing tibble manually.
