### ISSUE TITLE
write_dta produces false values for integer64 columns

### ISSUE THREAD

**Issue by Plebejer** [tidyverse/haven#379]
`write_dta()` does not handle columns of class `integer64` correctly:

    > library(haven)
    > library(bit64)
    > 
    > df <- data.frame(a = as.integer64(1))
    > df
      a
    1 1
    > 
    > write_dta(df, "int64.dta")
    > read_dta("int64.dta")
    # A tibble: 1 x 1
                 a
             <dbl>
    1 Inf.NaNe-324

Unfortunately, it does neither produce a warning, nor an error.

**Comment by hadley** [comment]
At this time, it's buyer-beware if you use int64 columns in R.
