### ISSUE TITLE
Request to update ReadStat version included in haven

### ISSUE THREAD

**Issue by tzoltak** [tidyverse/haven#382]
Updating _ReadStat_ version in _haven_ 1.1.1 resulted in throwing errors about being "unable to allocate memory" while trying to read some .sav files (version included in haven 1.1.0 successeded to read the same files). It seems that (at least some of) this problems have been fixed in newer releases of _ReadStat_:
[commit description 1](https://github.com/WizardMac/ReadStat/commit/88cbbda7105dce3847d57a2c5a32aabda33821bc),
[commit description 2](https://github.com/WizardMac/ReadStat/commit/748f1c5b95191d3c25d30488687da4cba57729a6).
Also some other errors have been patched in _ReadStat_ during last few months. Would it be possible to realease a new version of _haven_ including the latest version of _ReadStat_?

**Comment by hadley** [comment]
Working on it now.

**Comment by tzoltak** [comment]
Thanks!
