### ISSUE TITLE
write_dta not working for data.frame which columns contain unicode characters

### ISSUE THREAD

**Issue by withr** [tidyverse/haven#383]
Started from v14, STATA support unicode letter appeared in column names. So the legal column names include: _, 0-9 and unicode letters (Not only latin characters). 

However, the code in **haven.R** used to validate whether the names are legal/valid:

`bad_names <- !grepl("^[A-Za-z_]{1}[A-Za-z0-9_]{0,31}$", names(data))`

This is not correct, it should include another parameter:  version, for version >= 14, and can use the following code for version >= 14: 

`bad_names <- !stringi::stri_detect_regex(names(data), "^[\\p{L}_]{1}[\\p{L}0-9_]{0,31}$")
`

However, **validate_dta** is not the only function to validate the column names. 

The function 'dta_validate_name' in **readstat_dta_write.c** also check the column names. I tried to comment these lines:

    int j;
    for (j=0; name[j]; j++) {
        if (name[j] != '_' &&
                !(name[j] >= 'a' && name[j] <= 'z') &&
                !(name[j] >= 'A' && name[j] <= 'Z') &&
                !(name[j] >= '0' && name[j] <= '9')) {
            return READSTAT_ERROR_NAME_CONTAINS_ILLEGAL_CHARACTER;
        }
    }
    char first_char = name[0];
    if (first_char != '_' &&
            !(first_char >= 'a' && first_char <= 'z') &&
            !(first_char >= 'A' && first_char <= 'Z')) {
        return READSTAT_ERROR_NAME_BEGINS_WITH_ILLEGAL_CHARACTER;
    }

It seems work, but I am not sure due to my limited experience in C.

**Comment by hadley** [comment]
@evanmiller can you update the variable name check?

**Comment by evanmiller** [comment]
It's not a full solution, but I've relaxed the code for DTA 118 and later.

https://github.com/WizardMac/ReadStat/commit/4000645216740a30fcef9544f4bec61dd4c5249b
