### ISSUE TITLE
Importing monthly date format %tm with read_dta

### ISSUE THREAD

**Issue by stupersyn** [tidyverse/haven#385]
This is my first issue submission, so bear with me.

I have prepped this Stata .dta data file (version 14) to contain the %tm date format here:
[tm format_10 obs.dta](https://github.com/stupersyn/stata_tm-format/blob/14595f19bb0f2a7d132f65511637daddebf33e14/tm%20format_10%20obs.dta)

- This date format of %tm contains the year and month such as `'2010m5'` and `'2004m12'`

- Importing this version 14  stata .dta file into R via read_dta imports incorrectly as a `atomic` with values such as `'532'`

**Comment by batpigandme** [comment]
Hi @stupersyn,

From the docs for [`read_dta()`](https://haven.tidyverse.org/reference/read_dta.html):
> Currently haven can read and write logical, integer, numeric, character and factors.
Have you successfully read in dates formatted as this before? I might recommend saving them as characters, and then converting using lubridate and tidyr. (I don't work with Stata, though, so I'm just guessing there).

**Comment by stupersyn** [comment]
Hey @batpigandme and @hadley , @
I went with Mara's route with the characters.  This works since I have access to Stata.  If I did not, then Hadley's method would be the only way to go. 
Thank you! and Sorry for my being a pleb and opening this issue.
