### ISSUE TITLE
Weird handling of labelled variable labels after 'as_factor'

### ISSUE THREAD

**Issue by dar143** [tidyverse/haven#393]
I have a data set that works well for most of the labelled variable but one.
The variable district looks like it has 20 labels but when I convert to as_factor and use in table 
> attributes(marketEN$district)
$`label`
[1] "C. District"

$format.spss
[1] "F8.2"

$class
[1] "labelled"

$labels
 Kapilvastu Arghakhachi       Palpa       Gulmi     Dailekh 
          1           2           3           4           5 
   Jajarkot       Rukum     Surkhet      Salyan       Rolpa 
          6           7           8           9          10 
    Pyuthan      Bardia        Dang     Baitadi        Doti 
         11          12          13          14          15 
     Achham  Dadeldhura  Kanchanpur     Kailali       Banke 
         16          17          18          19          20 

When I look at the out from output from as_factor, it looks OK
> levels(as_factor(marketEN$district))
 [1] "Kapilvastu"  "Arghakhachi" "Palpa"       "Gulmi"      
 [5] "Dailekh"     "Jajarkot"    "Rukum"       "Surkhet"    
 [9] "Salyan"      "Rolpa"       "Pyuthan"     "Bardia"     
[13] "Dang"        "Baitadi"     "Doti"        "Achham"     
[17] "Dadeldhura"  "Kanchanpur"  "Kailali"     "Banke"      
> 
But when I use in a function like table (ggplot shows the same problem) they display a mashed levels vector.

> kable(table(as_factor(marketDfEN$district)))

|Var1        | Freq|
|:-----------|----:|
|1           |   19|
|2           |   12|
|3           |    8|
|4           |   11|
|5           |   16|
|6           |   13|
|7           |   13|
|8           |   16|
|9           |   13|
|Kapilvastu  |    0|
|Rolpa       |    8|
|Pyuthan     |   11|
|Bardia      |   20|
|Dang        |   13|
|Baitadi     |   11|
|Doti        |    8|
|Achham      |   13|
|Dadeldhura  |    7|
|Kanchanpur  |   26|
|Kailali     |   22|
|Arghakhachi |    0|
|Banke       |   10|
|Palpa       |    0|
|Gulmi       |    0|
|Dailekh     |    0|
|Jajarkot    |    0|
|Rukum       |    0|
|Surkhet     |    0|
|Salyan      |    0|
>

Regards
Ross

**Comment by hadley** [comment]
Can you please provide a minimal reprex (reproducible example)? The goal of a reprex is to make it as easy as possible for me to recreate your problem so that I can fix it: please [help me help you](https://nypdecider.files.wordpress.com/2014/08/help-me-help-you.gif)! 

If you've never heard of a reprex before, start by reading "[What is a reprex](http://reprex.tidyverse.org/articles/reprex.html)", and follow the advice further down the page. Please make sure your reprex is created with the reprex package as it gives nicely formatted output and avoids a number of common pitfalls.

**Comment by dar143** [comment]
Hi Hadley

Cute gif.

Sorry but the link “What is a reprex” gave a 404 browser error.

But I have seen the issue. I received the data from a colleague in Nepal who extracted the data from ODK as a sav file.(details yet to determined)
I have extracted one of the problem variables from the sav data set I received and called it ‘ex’.

I now see the leading white spaces as the class values but the class labels are numeric.


> str(attributes(ex)$labels)
Named num [1:20] 1 2 3 4 5 6 7 8 9 10 ...
- attr(*, "names")= chr [1:20] "Kapilvastu" "Arghakhachi" "Palpa" "Gulmi" ...


> str(ex)
Class 'labelled' chr [1:270] " 7" " 7" " 7" " 3" " 3" " 3" " 3" " 3" " 3" " 3" " 3" "16" ...
- attr(*, "format.spss")= chr "F8.2"
   .. .. LABEL: C. District
   .. .. VALUE LABELS [1:20]: 1=Kapilvastu, 2=Arghakhachi, 3=Palpa, 4=Gulmi, 5=Dailekh, 6=Jajarkot, 7=Rukum, 8=Surkhet, 9=Salyan, 10=Rolpa, 11=Pyuthan, 12=Bardia, 13=Dang, 14=Baitadi, 15=Doti, 16=Achham, 17=Dadeldhura, 18=Kanchanpur, 19=Kailali, 20=Banke
> table(ex)
ex
         1          2          3          4          5          6          7
        19         12          8         11         16         13         13
         8          9      Rolpa    Pyuthan     Bardia       Dang    Baitadi
        16         13          0          0          0          0          0
      Doti     Achham Dadeldhura Kanchanpur    Kailali      Banke
         0          0          0          0          0          0
> write_sav(data.frame(district = ex), "savExample.sav")
Error in write_sav_(data, normalizePath(path, mustWork = FALSE), compress = compress) :
  Not compatible with STRSXP: [type=NULL].

This fixes the problem


> ex <- as.numeric(ex)

> str(attributes(ex)$labels)

 Named num [1:20] 1 2 3 4 5 6 7 8 9 10 ...

 - attr(*, "names")= chr [1:20] "Kapilvastu" "Arghakhachi" "Palpa" "Gulmi" ...

> attributes(ex)$labels

 Kapilvastu Arghakhachi       Palpa       Gulmi     Dailekh    Jajarkot

          1           2           3           4           5           6

      Rukum     Surkhet      Salyan       Rolpa     Pyuthan      Bardia

          7           8           9          10          11          12

       Dang     Baitadi        Doti      Achham  Dadeldhura  Kanchanpur

         13          14          15          16          17          18

    Kailali       Banke

         19          20

> table(ex)

ex

 Kapilvastu Arghakhachi       Palpa       Gulmi     Dailekh    Jajarkot

         19          12           8          11          16          13

      Rukum     Surkhet      Salyan       Rolpa     Pyuthan      Bardia

         13          16          13           8          11          20

       Dang     Baitadi        Doti      Achham  Dadeldhura  Kanchanpur

         13          11           8          13           7          26

    Kailali       Banke

         22          10

Fixes  write_sav issue as well


> write_sav(data.frame(district = ex), "savExample.sav")

> exReturn <- read_sav("savExample.sav")

> table(exReturn)

exReturn

 Kapilvastu Arghakhachi       Palpa       Gulmi     Dailekh    Jajarkot

         19          12           8          11          16          13

      Rukum     Surkhet      Salyan       Rolpa     Pyuthan      Bardia

         13          16          13           8          11          20

       Dang     Baitadi        Doti      Achham  Dadeldhura  Kanchanpur

         13          11           8          13           7          26

    Kailali       Banke

         22          10


Kind regards

Ross



Ross Darnell |  CSIRO Data61 | Ecosciences Precinct, 41 Boggo Road, Dutton Park, QLD 4102 | +61 7 3833 5534 | +61 4 47750905

**Comment by batpigandme** [comment]
Hi Ross,

Here's the proper link to reprex: https://reprex.tidyverse.org/

**Comment by dar143** [comment]
Hi Mara

I think we can close this since it boils down to a mismatch between the values in the label class and the class labels values themselves .


Ross

Ross Darnell |  CSIRO Data61 | Ecosciences Precinct, 41 Boggo Road, Dutton Park, QLD 4102 | +61 7 3833 5534 | +61 4 47750905
