### ISSUE TITLE
read_sas: encoding of .sas7bdat 

### ISSUE THREAD

**Issue by iadli100** [tidyverse/haven#394]
Hi all, when the format file contains a "degree" character, it is not correctly displayed. Instead of the character, it shows the Unicode representation.

At the same time, when the data file contains this "degree" character, it imports correctly and output shows the correct sign.

```
  # load dataset
  dataset <- read_sas(
    data_file = "mydatafile.sas7bdat",
    
    # take into account the catalog file
    catalog_file = "myformatfile.sas7bcat", 

    # set encoding
    encoding = "latin1",
    catalog_encoding = "latin1"
  )
```

Example of undesired output of format file applied to data file looks like this:
```
#   value           label
#   0     < 3<U+00B0>
#   1  3 to 5<U+00B0>
#   2 6 to 10<U+00B0>
#   3    > 10<U+00B0>
```
where instead it should say:
```
#   value           label
#   0     < 3°
#   1  3 to 5°
#   2 6 to 10°
#   3    > 10°
```

Correct output of data file only:
```
# [1] "Body temperature [°C]"
```

Do you have any suggestions?
KR Iakov

**Comment by ofajardo** [comment]
Probably now fixed in Readstat (https://github.com/WizardMac/ReadStat/issues/152

**Comment by hadley** [comment]
No reprex, but I think @ofajardo's analysis is correct and hence this is fixed in dev.
