### ISSUE TITLE
`recode` does not work on labelled vector

### ISSUE THREAD

**Issue by elbersb** [tidyverse/haven#400]
see here:

``` r
d <- data.frame(s = haven::labelled(c(1, 1, 2), c(Male = 1, Female = 2))) 
dplyr::mutate(d, dplyr::recode(s, `1` = 2))
#> Error in mutate_impl(.data, dots): Evaluation error: no applicable method for 'recode' applied to an object of class "labelled".
```

Created on 2018-09-03 by the [reprex
package](http://reprex.tidyverse.org) (v0.2.0).

**Comment by batpigandme** [comment]
I believe [`dplyr::recode()`](https://dplyr.tidyverse.org/reference/recode.html) can take a named argument, but not a labelled one:
> Replacements. These should be named for character and factor .x, and can be named for numeric .x. The argument names should be the current values to be replaced, and the argument values should be the new (replacement) values.

From the [`haven::labelled()`](https://haven.tidyverse.org/reference/labelled.html) docs: 
> This class makes it possible to import such labelled vectors in to R without loss of fidelity. This class provides few methods, as I expect you'll coerce to a standard R class (e.g. a factor()) soon after importing.

You could turn the labelled column, s, into a factor with the names supplied, as below (in which case your recoding would be using `Male` and `Female`, I guess):
``` r
d <- data.frame(s = forcats::as_factor(haven::labelled(c(1, 1, 2), c(Male = 1, Female = 2))))
d
#>        s
#> 1   Male
#> 2   Male
#> 3 Female
```
<sup>Created on 2018-09-05 by the [reprex package](https://reprex.tidyverse.org) (v0.2.0.9000).</sup>

Or you could switch to integer or text before recoding with 1s and 2s, and then applying the names.

**Comment by elbersb** [comment]
Sure, all of these work as workarounds, but it still seems like it should work out of the box. The `labelled` vector its just a numeric vector with some labels attached, so it doesn't seem intuitive that a recode does not work. If the idea is that it needs always to be coerced into a factor anyway, then what's the advantage of using the `labelled` vector?

**Comment by batpigandme** [comment]
> If the idea is that it needs always to be coerced into a factor anyway, then what's the advantage of using the labelled vector?

There is no real advantage to using a labelled vector in R. The point of haven is to be able to read in data formats native to _other_ languages. If what you want is for `dplyr::recode()` to accept labelled vectors, then this issue belongs in the dplyr repo.

**Comment by elbersb** [comment]
> The point of haven is to be able to read in data formats native to other languages/statistical software

Right, but why bother with the `labelled` class when it needs to be turned into a factor before being able to do something useful (such as a recode) with it -- haven could just use a factor instead of the `labelled` class. I guess there are other advantages (NA handling etc.). Anyway, will open an issue in dplyr.

**Comment by larmarange** [comment]
In fact, `labelled` package was already extending `dplyr::recode` to handle labelled vectors. cf. https://github.com/larmarange/labelled/commit/ad68c1c83d3aa154b5f63b029b67d92dffd67861
