### ISSUE TITLE
na_tag and a vector of integers

### ISSUE THREAD

**Issue by larmarange** [tidyverse/haven#402]
As mentioned in https://github.com/larmarange/labelled/issues/28

``` 
haven::na_tag(1L:5L)
```

>Error: `x` must be a double vector

is producing an error.  Should `na_tag` coerce `x` into a numeric vector?

**Comment by hadley** [comment]
This doesn't seem that important to me — tagged NA's can only occur in a double vector.

**Comment by gekess** [comment]
Hi hadley,

I might have a similar issue to larmarange: I get na-tags for vectors (in this case variables of a tibble data frame) if I index the variable thus: `is_na(x$variablename)`, however, indexing the same variable through an index-number `is_na(x[,1])` or calling the name `is_na(x[,"variablename")` will yield
> Error: x must be a double vector

This seems very unpractical to me if I want to change several tags on multiple variables at once (see also my yet unanswered question on stackoverflow https://stackoverflow.com/questions/54568815/recoding-na-tags-in-tibble-for-multiple-variables). Any suggestions?)
