### ISSUE TITLE
read_spss and write_spss: missing labels for strings

### ISSUE THREAD

**Issue by beckerbenj** [tidyverse/haven#409]
When importing string variables via read_spss missing labels (and sometimes also value labels) seem to behave strangely depending on the width of the variables (at least in educational large scale assessments missing and value labels for string variables are not that uncommon). I used the current GitHub version of haven. 

<details>
The sav-file I attached looks like this (using SPSS 22.0.0.1 or SPSS 25)

[test1.zip](https://github.com/tidyverse/haven/files/2434912/test1.zip)

![spss_variables](https://user-images.githubusercontent.com/35807186/46302429-51f5ac80-c5a9-11e8-9177-790882f9b5db.jpg)
![spss_data](https://user-images.githubusercontent.com/35807186/46302435-54580680-c5a9-11e8-9afc-22d5d0b9c023.jpg)
 
Importing results in the following attributes on variable level:

``` r
rawDat <- haven::read_spss(file = "N:/spss/test1.sav", user_na = TRUE)
lapply(rawDat, attributes)
#> $v1
#> $v1$na_values
#> [1] 99
#> 
#> $v1$class
#> [1] "haven_labelled_spss" "haven_labelled"     
#> 
#> $v1$format.spss
#> [1] "F8.2"
#> 
#> $v1$labels
#> one 
#>   1 
#> 
#> 
#> $v2
#> $v2$na_values
#> [1] NA
#> 
#> $v2$class
#> [1] "haven_labelled_spss" "haven_labelled"     
#> 
#> $v2$format.spss
#> [1] "A8"
#> 
#> $v2$labels
#> one 
#> "1" 
#> 
#> 
#> $v3
#> $v3$format.spss
#> [1] "A9"
#> 
#> $v3$class
#> [1] "haven_labelled"
#> 
#> $v3$labels
#> one 
#> "1" 
#> 
#> 
#> $v4
#> $v4$format.spss
#> [1] "A21"
```

<sup>Created on 2018-10-01 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

When writing to sav missing labels for string variables are also dropped:

``` r
# set up data frame
df <- data.frame(v1 = c(1, 99), v2 = c("aa", "99"), stringsAsFactors = FALSE)
attributes(df$v1) <- list(na_values = 99, class = c("haven_labelled_spss", "haven_labelled"), format.spss = "F8.2", labels = c(one = 1))
attributes(df$v2) <- list(na_values = "99", class = c("haven_labelled_spss", "haven_labelled"), format.spss = "A2", labels = c(sth = "aa"))
# write sav
haven::write_sav(df, path = "N:/spss/test2.sav")
# read sav
spssDF <- haven::read_spss(file = "N:/spss/test2.sav", user_na = TRUE)
lapply(spssDF, attributes)
#> $v1
#> $v1$na_values
#> [1] 99
#> 
#> $v1$class
#> [1] "haven_labelled_spss" "haven_labelled"     
#> 
#> $v1$format.spss
#> [1] "F8.2"
#> 
#> $v1$labels
#> one 
#>   1 
#> 
#> 
#> $v2
#> $v2$format.spss
#> [1] "A2"
#> 
#> $v2$class
#> [1] "haven_labelled"
#> 
#> $v2$labels
#>  sth 
#> "aa"
```

<sup>Created on 2018-10-01 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

And the spss variable view looks like this:

![spss_test2](https://user-images.githubusercontent.com/35807186/46303222-8c604900-c5ab-11e8-922f-a4a08034b7f2.jpg)

Is there any way to import missing and value labels consistently from sav files to R? 

Thank You!
</details>

**Comment by hadley** [comment]
Can you please confirm that I've captured the problem in the following reprex?

``` r
library(haven)

path <- tempfile()
df1 <- tibble::tibble(
  x = labelled_spss(c("1", "99"), na_values = "99", c(one = "1"))
)

write_sav(df1, path)
df2 <- read_sav(path, user_na = TRUE)

attr(df1$x, "na_values")
#> [1] "99"
attr(df2$x, "na_values")
#> NULL
```

<sup>Created on 2019-01-24 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1.9000)</sup>

**Comment by beckerbenj** [comment]
Yes, that is exactly what I meant.

**Comment by hadley** [comment]
@evanmiller I only dimly remember how this works but in the readstat API I see `readstat_variable_add_missing_double_value()`, but no equivalent for adding strings. Is this something that you haven't implemented yet, or (more likely) am I missing something obvious?

**Comment by evanmiller** [comment]
@hadley Missing string values are not implemented. It was something I overlooked in the file format, I'll get on it soon.

Is there a second bug here with incorrect value labels? Can we get a reprex?

**Comment by hadley** [comment]
@evanmiller I think that's described in #422

**Comment by evanmiller** [comment]
Try https://github.com/WizardMac/ReadStat/commit/963b6eb622ff9d06a5041fb6ba124a8370cb6d86 (dev branch)

**Comment by hadley** [comment]
@evanmiller does `readstat_variable_get_missing_ranges_count()` need an update too? When I read [test1.zip](https://github.com/tidyverse/haven/files/2434912/test1.zip), I see values of 1, 1, 0, 0.

**Comment by evanmiller** [comment]
@hadley Actually it looks like a new-ish record type in the SAV file format:

https://www.gnu.org/software/pspp/pspp-dev/html_node/Long-String-Missing-Values-Record.html#Long-String-Missing-Values-Record

**Comment by hadley** [comment]
Not to self: WIP in local missing-string branch.

**Comment by evanmiller** [comment]
Okay the new record type should work in ReadStat master.
