### ISSUE TITLE
write_sav: wrong column names for tables with more than 10k columns

### ISSUE THREAD

**Issue by Majid-Eismann** [tidyverse/haven#410]
Hallo,
when creating a sav file with more than 10.000 columns the column names are probably repeated. 

In the code bellow I couldn´t show the repetition of names because read_sav corrects duplicate names. read.spss does not import the file. Opening the file in Statistica showed duplicated names.
The same occurs with varying the names to random strings of 32 letters. 

```
library(foreign)
library(tibble)

# create data frame with more than 10k columns and export
randomDF <- data.frame(as.list(1:10001))

# write sample files
write_sav(randomDF[1:10000], "test1.sav")
write_sav(randomDF[1:10001], "test2.sav")

# error reading system-file header
if (F) foreign::read.spss("test2.sav")

# reimport corrects duplicate names (first & last position)
data_frame(
  column_position = 1:10001,
  a = c(names(read_sav("test1.sav")), rep("-", 1)),
  b = names(read_sav("test2.sav"))
) %>% 
filter(a != b)
```
Thanks!

**Comment by evanmiller** [comment]
Related discussion here: https://github.com/WizardMac/ReadStat/issues/122

This should be fixed in the latest version of ReadStat.

**Comment by hadley** [comment]
Looks good to me now.

@Majid-Eismann in future, using the reprex package would be much appreciated as it makes it easier for me to see exactly what results you got.
