### ISSUE TITLE
read_por() invalid file or unsupported features (spss v25)

### ISSUE THREAD

**Issue by zross** [tidyverse/haven#412]
`haven` is an amazing package! I use it constantly to convert SAS, SPSS and others. 

It has worked perfectly to read `.por` files up until now. I've tested SPSS version 14, 20 and 24 and these work fine. But with the `.por` files from version 25 I'm getting an error.

I tried the most recent version of `haven` on CRAN and then I tried the version from GitHub and neither works.

I created a tiny file as both a `.por` and a `.sav` for testing (attached to this issue) and they work as `.sav` but not `.por`.

```r
# not working
root %>% 
  path("tiny_spss25_locale.por") %>% 
  haven::read_por()

# Error in df_parse_por_file(spec, encoding = "", user_na = user_na) : 
#   Failed to parse tiny_spss25_locale.por: Invalid file, or file has unsupported features.

# This works
root %>% 
  path("tiny_spss25_locale.sav") %>% 
  haven::read_sav()
```

Any thoughts?

[tiny_spss25_locale.zip](https://github.com/tidyverse/haven/files/2566560/tiny_spss25_locale.zip)

**Comment by zross** [comment]
@evanmiller has fixed this issue (thanks for the super-quick response). When you get a chance to update the version of ReadStats for Haven that would be great!

**Comment by timparsons** [comment]
I’m also experiencing this issue, and could really use the fix @zross mentioned as soon as possible. Thanks!

**Comment by zross** [comment]
Version 2.0 of Haven was released and includes some great updates but does not include the update from ReadStat that allows the reading of SPSS v25. As a temporary fix, until `haven` includes this edit, others who have this issue can do the following:

1. Clone haven repo
2. Open `haven/src/readstat/spss/readstat_por_read.c`
3. Make the tiny edit you see in this [ReadStat commit](https://github.com/WizardMac/ReadStat/commit/3b613a10b6bd2945b0b9b4c834a4d0cef24e7261#diff-de5a1ad491979008537d2871e7b5af95L203).
4. Build source package
5. Install the source package.
