### ISSUE TITLE
problem with labelled variables

### ISSUE THREAD

**Issue by visseho** [tidyverse/haven#416]
After using haven to read my Stata file, I used this command to transform labelled variables to factors with their labels.
In the new version, it seems to not working.

labeled_vars <- sapply(master_family, function(x) class(x) == "labelled")
master_family[, labeled_vars] <- lapply(master_family[, labeled_vars], as_factor)

**Comment by larmarange** [comment]
In the new version of haven, the class has been renamed "haven_labelled".

To convert all vectors at once, you can also use directly "to_factor()" from "labelled" package on a data.frame.
