### ISSUE TITLE
read_sav gives a memory allocation error when a variable has a long list of value labels

### ISSUE THREAD

**Issue by philstraforelli** [tidyverse/haven#418]
[test2.zip](https://github.com/tidyverse/haven/files/2712960/test2.zip)

I've attached an SPSS file of a variable (no actual data) with 165,772 value labels for that variable. It's giving me an `"Unable to allocate memory."` error when trying to `read_sav()` the file.

**Comment by evanmiller** [comment]
Fixed (or at least increased the limit) in https://github.com/WizardMac/ReadStat/commit/74229e84a08a3168273c9643656c80cbc0085e49
