### ISSUE TITLE
read_spss loses value labels of some strings

### ISSUE THREAD

**Issue by beckerbenj** [tidyverse/haven#422]
Value labels of string variables with width >= 9 in SPSS files are inconsistently imported via `read_sav`. The only alternative package importing the value labels I could find was the `readspss` package. I also tried `foreign` and `memisc`; both packages seem to omit the value labels for both variables.

[spss_created.zip](https://github.com/tidyverse/haven/files/2813181/spss_created.zip)
Variable overview of the example data:

![grafik](https://user-images.githubusercontent.com/35807186/51991026-82dbe480-24aa-11e9-8763-ef08587c2fe1.png)

``` r
df_haven <- haven::read_sav(file = "spss_created.sav", user_na = TRUE)
attr(df_haven$x, "labels")
#> one 
#> "1"
attr(df_haven$y, "labels")
#> NULL

df_readspss <- readspss::read.sav("spss_created.sav", convert.factors = FALSE)
attr(df_readspss, "longlabel")
#> $x
#> one 
#> "1" 
#> 
#> $y
#> one 
#> "1"
```

<sup>Created on 2019-01-30 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

I have tried creating the .sav files with SPSS Version 22 and 25, with both the bug occurs. When the .sav file is created with haven, the bug does not occur. 

``` r
library(haven)
path <- tempfile()
df <- tibble::tibble(
  x = labelled_spss(c("a", "Width of9"), c(one = "1")),
  y = labelled_spss(c("a", "Width of9"), c(one = "1"))
)

write_sav(df, path)
df1 <- read_sav(path, user_na = TRUE)
attr(df$x, "labels")
#> one 
#> "1"
attr(df$y, "labels")
#> one 
#> "1"

attr(df1$x, "labels")
#> one 
#> "1"
attr(df1$y, "labels")
#> one 
#> "1"
```

<sup>Created on 2019-01-30 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

**Comment by hadley** [comment]
I see this with latest readstat. @evanmiller, I think this is one for you.

**Comment by hadley** [comment]
LGTM: 

``` r
df_haven <- haven::read_sav("~/Desktop/spss_created.sav", user_na = TRUE)
attr(df_haven$x, "labels")
#> one 
#> "1"
attr(df_haven$y, "labels")
#> one 
#> "1"
```

<sup>Created on 2019-02-03 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1.9000)</sup>
