### ISSUE TITLE
Error in if (any(bad_labels)) { : missing value where TRUE/FALSE needed with write_dta

### ISSUE THREAD

**Issue by bouli80** [tidyverse/haven#427]
Hi!

I successfully imported this SPSS file 
http://vs-web-fs-1.oecd.org/piaac/PUF-Data/SPSS/prgautp1.sav. But then I tried to export it as a dta file and encountered the following error: "Error in if (any(bad_labels)) { : missing value where TRUE/FALSE needed"
My code:
library(haven)
library(plyr)
data1 <- read_sav("./spss/prgautp1.sav")
write_dta(data1, "./piaac.dta")
R version 3.5.1
haven  version  2.0.0.9000 468bff2

**Comment by hadley** [comment]
Can you please provide a minimal reprex (reproducible example)? The goal of a reprex is to make it as easy as possible for me to recreate your problem so that I can fix it: please [help me help you](https://nypdecider.files.wordpress.com/2014/08/help-me-help-you.gif)! 

If you've never heard of a reprex before, start by reading "[What is a reprex](http://reprex.tidyverse.org/articles/reprex.html)", and follow the advice further down the page. Please make sure your reprex is created with the reprex package as it gives nicely formatted output and avoids a number of common pitfalls.

**Comment by bouli80** [comment]
The link you provided is a 404, so I hope I did it right:
``` r
library(haven)
data1 <- read_sav("/Users/tomas/work/research/data/piaac/spss/prgautp1.sav")
write_dta(data1, "/Users/tomas/work/research/data/piaac/piaac.dta")
#> Warning in is_integerish(attr(x, "labels")): NAs introduced by coercion to
#> integer range

#> Warning in is_integerish(attr(x, "labels")): NAs introduced by coercion to
#> integer range

#> Warning in is_integerish(attr(x, "labels")): NAs introduced by coercion to
#> integer range

#> Warning in is_integerish(attr(x, "labels")): NAs introduced by coercion to
#> integer range

#> Warning in is_integerish(attr(x, "labels")): NAs introduced by coercion to
#> integer range

#> Warning in is_integerish(attr(x, "labels")): NAs introduced by coercion to
#> integer range

#> Warning in is_integerish(attr(x, "labels")): NAs introduced by coercion to
#> integer range

#> Warning in is_integerish(attr(x, "labels")): NAs introduced by coercion to
#> integer range

#> Warning in is_integerish(attr(x, "labels")): NAs introduced by coercion to
#> integer range

#> Warning in is_integerish(attr(x, "labels")): NAs introduced by coercion to
#> integer range

#> Warning in is_integerish(attr(x, "labels")): NAs introduced by coercion to
#> integer range

#> Warning in is_integerish(attr(x, "labels")): NAs introduced by coercion to
#> integer range

#> Warning in is_integerish(attr(x, "labels")): NAs introduced by coercion to
#> integer range

#> Warning in is_integerish(attr(x, "labels")): NAs introduced by coercion to
#> integer range
#> Error in if (any(bad_labels)) {: missing value where TRUE/FALSE needed
```

<sup>Created on 2019-12-02 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by hadley** [comment]
I can't download that file, so unfortunately I can't look into it.

**Comment by diggyg97** [comment]
I have the same problem and I can present you with a reprex.

I use the following code:

`dig = read_dta("WB_QoG_swiid_SAMIP_ILE_Digvijay.dta")
sah = read_dta("sahithi.dta")
data = dig %>% full_join(sah, by = c("ccode", "cname" = "country", "ccodealp" = "countrycode","year"))
write_dta(data, "final.dta")`

The write_dta line returns the following error: Error in if (any(bad_labels)) { : missing value where TRUE/FALSE needed

The data is uploaded here: https://drive.google.com/drive/folders/1-sUBtwJRUV5zL4djOUeU653gVl3qwQkT?usp=sharing
Please download the two data files and load them using the above code, merge them and saving them gives me the same error. I don't know what to do, please help. Thank you. @hadley
