### ISSUE TITLE
write_dta should use Stata's multiple missing values when exporting labelled_spss data

### ISSUE THREAD

**Issue by bouli80** [tidyverse/haven#428]
Hi,

When importing an SPSS dataset, read_sav() can import also user defined missing values, which is great.
However, when exporting that dataset as a Stata dta file, these user defined missing values are assigned a numerical value. However, stata has 27 possible values for missing values (., .a, .b, .c, ..., .z), which could be assigned as values for these SPSS user defined missing values. These numeric missing values in Stata are represented by large positive values.  The ordering is: all nonmissing numbers < . < .a < .b < ... < .z

Example:
library(haven)
x1 <- labelled_spss(c(1, 2, 1, 98, 99), c("Did not know" = 98, "Refused to answer" = 99), na_values = c(98, 99))
example <- data.frame(x1)
write_dta(example, "example.dta")

The file example.dta then contains a numeric variable x1 that contains numeric values 1, 2, 1, 98, 99 with the corresponding labels. However, for Stata, 98 and 99 are nonmissing numerical values. I think it would be better if write_dta() converted 98 to .a and 99 to .b, and applied the corresponding value labels to them.

**Comment by hadley** [comment]
Minimal reprex:

``` r
library(haven)
path <- tempfile()

x1 <- labelled_spss(
  c(1, 2, 1, 98, 99), 
  c("Did not know" = 98, "Refused to answer" = 99), 
  na_values = c(98, 99)
)
example <- data.frame(x1)
write_dta(example, path)

str(read_dta(path)$x1)
#>  'haven_labelled' num [1:5] 1 2 1 98 99
#>  - attr(*, "format.stata")= chr "%10.0g"
#>  - attr(*, "labels")= Named num [1:2] 98 99
#>   ..- attr(*, "names")= chr [1:2] "Did not know" "Refused to answer"
```

<sup>Created on 2019-11-06 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by dusadrian** [comment]
If this issue is still open, it would also be great if users would be given the possibility to (consistently) use the same Stata missing values across multiple variables. For instance, if one variable has 98 and 99 defined as missing values, and another variable has 99, the value 99 would be recoded to the same Stata missing code (say .b)
Ideally, if the user could supply the transformation rules (perhaps 99 to .a and 98 to .b) this would make the process completely user friendly.

**Comment by hadley** [comment]
I now see that this question is about converting SPSS-style missings to Stata-style missings. I think unfortunately that this is out of scope for haven.

@dusadrian similarly, if you want to enforce a consistent missing encoding, then it's up to you to write the function to do so.

**Comment by dusadrian** [comment]
@hadley that would not be a problem (I even have a draft function ready), but will `haven` export tagged NAs to Stata missing codes (and import them back)?
I get

```r
library(haven)
path <- tempfile()

tags <- tagged_na('a', 'b')
x1 <- labelled(
  c(1, 2, 1, tags[1], tags[2]), 
  c("Did not know" = tags[1], "Refused to answer" = tags[2])
)
example <- data.frame(x1)
write_dta(example, path)

str(read_dta(path)$x1)
#  dbl+lbl [1:5]  1,  2,  1, NA, NA
#  @ format.stata: chr "%10.0g"
#  @ labels      : Named num [1:2] -2.15e+09 -2.15e+09
#   ..- attr(*, "names")= chr [1:2] "Did not know" "Refused to answer"
```

Stata reads the file exported by `haven` as having simple missing values, coded "."
```
. codebook x1

---------------------------------------------------------------------------------------------------
x1                                                                                      (unlabeled)
---------------------------------------------------------------------------------------------------

                  type:  numeric (double)
                 label:  x1, but 2 nonmissing values are not labeled

                 range:  [1,2]                        units:  1
         unique values:  2                        missing .:  2/5

            tabulation:  Freq.   Numeric  Label
                             2         1  
                             1         2  
                             2         .  
```

**Comment by hadley** [comment]
@dusadrian can you please file a new issue? This seems unrelated to the initial issue.

**Comment by dusadrian** [comment]
As promised, there is a new function `recodeMissing()` in package `DDIwR` that uniformly recodes SPSS missing values to Stata and the other way round. Please see:
https://github.com/dusadrian/DDIwR
