### ISSUE TITLE
Can't import big (0.9gb) spss or stata file

### ISSUE THREAD

**Issue by bdemeshev** [tidyverse/haven#441]
Can't import big (0.9gb) spss or stata file.
```r
ind_sav <- haven::read_spss("USER_RLMS-HSE_IND_1994_2017_v2.sav")
ind_dta <- haven::read_dta("USER_RLMS-HSE_IND_1994_2017_v2_eng.dta")
```
Both commands fail. No error message. The process is killed by OS.

This is the panel study of russian individuals. The dataset can be freely [obtained after registration](https://www.hse.ru/en/rlms/downloads).

**Comment by scottkosty** [comment]
@bdemeshev What OS are you using? How much system RAM do you have?

**Comment by bdemeshev** [comment]
Ubuntu 18.04, 16Gb, more than enough for the file.

I have made similar bug reports for python pandas and gretl. In both cases
there were unoptimal memory allocation in reading function. Both pandas and
gretl are already updated to manage big files correctly :) I am ready to
assist with any information you need!

**Comment by scottkosty** [comment]
Thanks for the quick reply. I'm not a developer. I was just trying to collect more information. Hopefully someone else comes and takes a look.

**Comment by evanmiller** [comment]
@bdemeshev Do you have links to your bug reports to gretl and pandas? That will help with debugging.

**Comment by evanmiller** [comment]
The latest files (1994-2018) open fine for me using ReadStat, the underlying library.

Using haven 2.1.1, the Stata file opens fine. The SPSS file fails with a different error

```
> read_sav("USER_RLMS-HSE_IND_1994_2018_v2_eng.sav")
Error in `levels<-`(`*tmp*`, value = as.character(levels)) : 
  factor level [37] is duplicated
```

Please update your haven version and see if the issue is fixed.

**Comment by bdemeshev** [comment]
Wow! Everything works! Thank you!!!
Just some timings with in-memory dataset sizes:

household spss: 35.416 sec elapsed, 2.11 GB
individual spss: 209.131 sec elapsed, 7.63 GB
household stata: 30.175 sec elapsed, 2.1 GB
individual stata: 160.8 sec elapsed, 7.63 GB

Will close the issue! :)

Resolved [pandas issue](https://github.com/pandas-dev/pandas/issues/25772), not resolved [julia issue](https://github.com/queryverse/StatFiles.jl/issues/15), gretl discussion is in mailing list.
