### ISSUE TITLE
Add print_variable_labels convenience function

### ISSUE THREAD

**Issue by briatte** [tidyverse/haven#443]
Hello,

Would you consider a complement to `print_labels`, which is described as follows in the documentation?

> This is a convenience function, useful to explore the variables of a newly imported dataset.

Since many labelled datasets have very large numbers of variables that the user might want to list and search, here's a function that builds on `print_labels` and on the code posted by @hadley in #237 (except missing variables are returned as `NA` instead of `""`:

```r
#' Print the variable labels of a data frame
#' 
#' This is a convenience function, useful to explore the variables of a newly 
#' imported dataset.
#' @param x A data frame
#' @param name The name of the data frame (optional)
print_variable_labels <- function (x, name = NULL) {
  if (!is.data.frame(x)) {
    stop("x must be a data frame", call. = FALSE)
  }
  var_label <- function(x) {
    label <- attr(x, "label")
    if (is.null(label)) NA_character_ else label
  }
  labels <- vapply(x, var_label, character(1))
  x <- names(x)
  names(x) <- labels
  cat("\nVariable labels:", name, "\n", sep = "")
  lab_df <- data.frame(value = x, label = labels, stringsAsFactors = FALSE)
  print(lab_df, row.names = FALSE)
  invisible(x)
}
```

Example with `iris.dta`

```r
ex <- read_dta(system.file("examples", "iris.dta", package = "haven"))
print_variable_labels(ex)
```

```
> print_variable_labels(ex)

Variable labels:
       value        label
 sepallength Sepal.Length
  sepalwidth  Sepal.Width
 petallength Petal.Length
  petalwidth  Petal.Width
     species      Species
```

The output can get unwieldy if there are many variables, or if the labels are long.

The (invisible) result might be stored for further exploration:

```r
lbl <- print_variable_labels(ex)
lbl[ grepl("Petal", names(lbl)) ]
```

```
> lbl[ grepl("Petal", names(lbl)) ]
 Petal.Length   Petal.Width 
"petallength"  "petalwidth" 
```

This function is only a small step to helping users with interactive exploration labelled data (such as survey data), but perhaps a minimal implementation is good enough for `haven`, leaving it to other packages like `questionr` or `labelled` to provide more.

I will of course submit a PR if that function is of interest.

**Comment by hadley** [comment]
Again, I unfortunately think this is out of scope for haven. It really is a package designed for reading and writing statistical file formats, not generally computing on the data representations used by those packages.
