### ISSUE TITLE
Add look_for_* search functions?

### ISSUE THREAD

**Issue by briatte** [tidyverse/haven#444]
In the spirit of #237 and #443, would there be an interest in offering `haven` users functions to search through variable labels or values, which are very much needed for interactive exploration of labelled data such as large survey datasets?

This would involve:

1. Allowing the `print_labels` and my `print_variable_labels` suggestion in #443 to return their results completely invisibly
2. Writing two functions, `look_for_labels` and `look_for_variables`, that would subset the corresponding `print_*` results

Step 2 can be done, using `grepl` as in #237, although it'd have to grep both variable/value names _and_ labels and support at least `ignore.case`, or it could use `tidyselect`, as in

```r
look_for_variables(labelled_df, starts_with("Municipal"))
look_for_labels(labelled_var, contains("employed"))
```

Another verb for the functions could be `find_*`.

## Rationale

Users can get rather similar things from [`questionr`](https://github.com/juba/questionr), by @juba, and [`labelled`](https://github.com/larmarange/labelled), via @larmarange, but users do not necessarily know those packages. Another similar function, although broader in scope as it search the entire environment, is [`lookfor`](https://github.com/leeper/lookfor) by @leeper.

Minimal search support through both kinds of variable labels in `haven` would be, to my view, hugely beneficial to all those users that I see using `haven` and then returning to either SPSS or Stata just to explore the data, especially when there are lots of variables with uninformative names, which happens often in large surveys like those documented by @ajdamico in [`asdfree`](https://github.com/ajdamico/asdfree).

* * *

Please let me know if adding that kind of interactivity to `haven` would be welcome, and I'll submit a PR implementing what I described above.

**Comment by hadley** [comment]
This is unfortunately out of scope for haven — I have relatively bandwidth for this package so I want to keep it as simple as possible.
