### ISSUE TITLE
Possible workaround for closed issue on R reading SAS format Catalogs (Issues 268,257)

### ISSUE THREAD

**Issue by rogerjdeangelis** [tidyverse/haven#445]
Python import sas catalogs and export to R dataframe                                           
                                                                                               
Rxample code on my github site                                                                 
                                                                                               
Win 7 64bit SAS 9.4 64bit                                                                      
                                                                                               
I have not tried 32bit format catalogs.                                                        
                                                                                               
Python reading sas catalogs without sas and exporting to R                                     
                                                                                               
* R does not support SAS format catalogs?;                                                     
                                                                                               
my github                                                                                      
https://tinyurl.com/y4czlt2r                                                                   
https://github.com/rogerjdeangelis/utl-python-import-sas-catalogs-and-export-to-R-dataframe    
                                                                                               
Python packages;                                                                               
https://github.com/Roche/pyreadstat                                                            
https://github.com/ofajardo/pyreadr#what-objects-can-be-read                                   
                                                                                               
Note the package does not read a stanalone SAS format catalog. It needs                        
a SAS table with the user formats. The package can only                                        
identify labels associated with code in the associated SAS table.

**Comment by ofajardo** [comment]
@rogerjdeangelis just in case it is of any use: the python package does read standalone SAS catalogs. You need to use the function read_sas7bcat. The result will be in meta.value_labels:

```
import pyreadstat
df, meta = pyreadstat.read_sas7bcat("/path/to/file.sas7bcat")
print(meta.value_labels)
```

See here: https://ofajardo.github.io/pyreadstat_documentation/_build/html/index.html
