### ISSUE TITLE
Writing "label" attribute non-obvious.

### ISSUE THREAD

**Issue by aaronrudkin** [tidyverse/haven#448]
I am using haven to export to Stata (via write_dta). In general haven's support for the "labels" attribute (in Stata parlance, "value labels") via `labelled` is fairly good. 

However, haven's support for the "label" attribute (in Stata parlance, "variable labels") when trying to output R data into Stata is poor. While `zap_label` exists to remove the label attribute from data read in from Stata, there is no reverse function to write them, and this is sort of a weird thing in R because assigning an attribute to a column within a tibble is awkward.

Some thoughts about what works and doesn't. If you are building a tibble from labeled vectors, you're fine:
```
ex_var <- sample(1:10, 10, replace = TRUE)
attr(ex_var, "label") <- "This is an example variable label"
tibble(ex_var = ex_var) %>% write_dta("out.dta")
```

But suppose the tibble already exists, it's not intuitive how you would write this attribute:
```
# Assume ex_tibble is some pre-existing dataset being worked with in R
ex_var <- sample(1:10, 10, replace = TRUE)
ex_tibble <- tibble(ex_var = ex_var)
attr(ex_tibble[, 1], "label") <- "This is an example variable label" # Doesn't work
dput(ex_tibble)
```

You might correctly figure you can do this with mapping the tibble:
```
ex_tibble_2 <- tibble(x = sample(1:10, 10, replace = TRUE), y = sample(1:10, 10, replace = TRUE))
ex_label <- c("Label X", "Label Y")
result <- map2(ex_tibble_2, ex_label, function(x, y) { 
  attr(x, "label") <- y
  x
}) %>% bind_cols()
dput(result)
```

If you only want to overwrite one column, you'd probably use, say, `mutate_at` or `mutate` with a closured anonymous function;
```
ex_tibble_2 <- tibble(x = sample(1:10, 10, replace = TRUE), y = sample(1:10, 10, replace = TRUE))
ex_tibble_2 %>% mutate_at(vars(x), function(vector) { 
     attr(vector, "label") <- "Label X"
     vector
 }) %>% dput()

ex_tibble_2 %>% mutate(x = (function(vector) { 
     attr(vector, "label") <- "Label X"
     vector
 })(x)) %>% dput()
```

Although the above two approaches are awkward, they work. But the most awkward of all is when you want to do this with some but not all of the variables. You can get into quasi-quoted stuff to try to repeat this for multiple variables, or you can do the `map2` approach but put some NULL in the vector for those you don't want to label -- either way, probably a little tough for the average user.

So, the feature request here is fairly simple: Think about the most idiomatically haven/tidyverse friendly way to implement simple label writing for existing data frames and then implement it. I guess in my head the thing that makes the most sense is `set_label`, a function that takes a tibble as the first argument, and a vector of "label" as the second argument. If the second argument is a named vector, label those column names. If the second argument is an unnamed vector of length `p` where p is the number of columns, label all columns in order.

Alternatively, I may have missed some obvious functionality here, and this is a user error, and I'd appreciate any suggestions you have for the best way to do this.

**Comment by gorcha** [comment]
Hi Aaron,

In haven the label support is fairly minimal.

I'd recommend checking out the [labelled](https://larmarange.github.io/labelled/) package if you haven't already, it has a bunch of handy extensions to help searching and updating labelled vectors.

Cheers,
Danny

**Comment by aaronrudkin** [comment]
Thanks Danny -- feel free to close this as out of scope if the intent is to build out label functionality in the external labelled package (although maybe an alternate way of interpreting my issue is that it's non-obvious this functionality would be in another third party package and so maybe there's value in reflecting that in the documentation for haven)

**Comment by gorcha** [comment]
Hey Aaron,

Just to clarify I'm not a maintainer, just a regular haven user and some-time contributor ;)

So I can't speak for haven, but I'm pretty sure the label functionality is intentionally minimal so it's just enough to support metadata from supported file formats (hence the `zap_*()` family but no proper support for adding or manipulating these attributes outside of the `labelled()` constructor).

To quote one of the maintainers:
> There is no real advantage to using a labelled vector in R. The point of haven is to be able to read in data formats native to _other_ languages/statistical software.

_Originally posted by @batpigandme in https://github.com/tidyverse/haven/issues/400#issuecomment-418829650_


Totally agree a mention of labelled in the docs (and probably in suggests) would be good though!

Cheers,
Danny

**Comment by hadley** [comment]
@gorcha is correct — the intent of haven is to read and write data from/to statistical file formats, not provide a bunch of tools to work with them.

Also it's pretty easy to set an attribute of column in a dataframe/tibble:

``` r
df <- data.frame(x = 1:10)
attr(df$x, "label") <- "This is an example variable label"
attr(df$x, "label")
#> [1] "This is an example variable label"
```

<sup>Created on 2019-11-06 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>
