### ISSUE TITLE
Add support for Stata "data label" writing

### ISSUE THREAD

**Issue by aaronrudkin** [tidyverse/haven#449]
Stata files have a "data label", which contains a file-level metadata summary of the data. When data is read via `read_dta`, this label is read; i.e. `my_df <- read_dta("test.dta"); attributes(my_df)` clearly shows the attribute "label".

However, when setting the attribute "label" to a tibble inside R and using `write_dta`, this attribute is not written. So, for example, `my_df = tibble(X = 1:10, Y=1:10); attr(my_df, "label") = "Test label"; write_dta(my_df, "test_out.dta"); attributes(read_dta("test_out.dta"))` will not work.

This functionality is supported by `foreign`.

**Comment by gorcha** [comment]
Hey Aaron,

Have submitted a pull request that implements this functionality using a `label` argument to `write_dta()`. This defaults to the `label` attribute of the input data frame consistent with `read_dta()`.

Cheers,
Danny

**Comment by aaronrudkin** [comment]
Thanks for the very quick turnaround time, Danny! Feel free to close this issue on merge.
