### ISSUE TITLE
reading in SAS files (sas7bdat) generated from SAS JMP

### ISSUE THREAD

**Issue by jinsonerinjeri** [tidyverse/haven#451]
I was trying to read a SAS file via HAVEN in R-Studio. I get a “invalid file error and unsupported data features” error. 
The file was exported from SAS JMP as a SAS7BDAT file.  I am able to read other SAS files and able to read the same file if I recreate the same file in SAS/STAT.

**Comment by evanmiller** [comment]
Can you share a link to the file that is not working?

**Comment by jinsonerinjeri** [comment]
I will provide that data sets to you and is in the process of getting a "okay" from our team.

JINSON JOHNSON ERINJERI 

    On Sunday, 27 October 2019, 08:52:12 GMT-4, Evan Miller <notifications@github.com> wrote:  
 
 
Can you share a link to the file that is not working?

**Comment by hadley** [comment]
I've closed this issue due to lack of requested reprex. If you still care about this bug, please open a new issue with a reprex.
