### ISSUE TITLE
Feature Request: Allow Loading of CPORT Files

### ISSUE THREAD

**Issue by billdenney** [tidyverse/haven#453]
This issue is likely identical to that in #321.

Can haven be extended to load SAS files created with cport?

I recognize that the cport format is not the same as xpt, but I hope that by providing an example file there is a chance that we could get closer.  If additional example files would be helpful, I can likely have them generated.  (I don't have a copy of SAS, but I can request files be generated with specific SAS code and data.)

I have a SAS .xpt file that was created with cport by downloading some data [1], saving it into c:\tmp as normal .xpt files, and then running SAS code similar to the following:
```
title 'CPORT of sas files and formats';
 
libname pack  'c:\tmp';
 
proc cport lib=pack file = "c:\tmp\cport_example.xpt";
run;
```

When trying to load it, I get the following error:

``` r
input_filename <- "https://github.com/tidyverse/haven/files/3247349/Combine_CP1805Data_KI20160914.zip"
temporary_zip <- tempfile(fileext="zip")
temporary_xpt <- tempfile(fileext="xpt")
download.file(url=input_filename, destfile=temporary_zip)
unzipped_file <- unzip(temporary_zip, exdir=tempdir())

library(haven)
haven::read_sas(data_file=unzipped_file)
#> Error in df_parse_sas_file(spec_data, spec_cat, encoding = encoding, catalog_encoding = catalog_encoding, : Failed to parse C:/Users/Bill Denney/AppData/Local/Temp/RtmpUxMu83/Combine_CP1805Data_KI20160914.xpt: Invalid file, or file has unsupported features.
```

<sup>Created on 2019-06-03 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

[Combine_CP1805Data_KI20160914.zip](https://github.com/tidyverse/haven/files/3247349/Combine_CP1805Data_KI20160914.zip)

[1] These two files: https://raw.githubusercontent.com/billdenney/PKdata/master/data-raw/KI20160914.csv https://raw.githubusercontent.com/billdenney/PKdata/master/data-raw/CP1805Data.csv

**Comment by billdenney** [comment]
And, if it's out of scope, would it be feasible to detect that it is a cport-created file and give information to the user that "The file was created using the SAS CPORT function.  CPORT files are not supported; please convert to XPORT to load."?

**Comment by hadley** [comment]
This [link](https://www.loc.gov/preservation/digital/formats/fdd/fdd000464.shtml) suggests that unlike xport, cport is not openly documented so we would need to reverse engineer it, and given the limited demand for this file format, I don't think it's worth it.

We don't recommend alternatively file formats for any other `read_` function so I don't think a different error message would be appropriate here.
