### ISSUE TITLE
write_xpt() assigns format "$" and informat "$" by default

### ISSUE THREAD

**Issue by jeblucas** [tidyverse/haven#456]
write_xpt() seems to apply a currency ($) format/informat designation on exported columns (at least in version = 5 which is what I need for FDA filings).

Attaching a screenshot of the output as seen in SAS Universal Viewer with issue labeled.

```r
library(tibble)
library(haven)
try <- tibble::tibble("STUDYID" = as.character(20011234), USUBJID = as.character("20011234-5678"))
glimpse(try)
#> Observations: 1
#> Variables: 2
#> $ STUDYID <chr> "20011234"
#> $ USUBJID <chr> "20011234-5678"
write_xpt(try, file.path(getwd(),"pp.xpt"), version = 5)
```

![image](https://user-images.githubusercontent.com/9466233/59874707-c5b43100-9353-11e9-9a93-8d1020460986.png)

**Comment by hadley** [comment]
Slightly simpler reprex:

``` r
library(haven)
path <- tempfile()
df <- tibble::tibble(x = 20011234, y = "20011234-5678")
write_xpt(df, path, version = 5, name = "test")
```

<sup>Created on 2019-11-06 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

@evanmiller any ideas what the problem might be here? I am calling `readstat_variable_set_format(var, NULL)` for each variable.

**Comment by evanmiller** [comment]
`$` is a generic character format and does not indicate currency

https://support.sas.com/documentation/cdl/en/leforinforref/64790/HTML/default/viewer.htm#n134ahpcz8murvn1x7went6p2czo.htm

**Comment by hadley** [comment]
Thanks for the clarification!
