### ISSUE TITLE
written dta file not readable in Stata

### ISSUE THREAD

**Issue by JoWi2** [tidyverse/haven#461]
When writing a .dta file using haven, it can be opened with Stata MP (the most expensive version  of Stata with the most features).

I checked with an MWE: 

>library(haven)
foo <- mtcars #using mtcars with 32 observations of 11 variables
write_dta(foo, "C:/Users/XXXX/Desktop/foo.dta", version = 15) # writing the data frame into a dta file

When opening the file in Stata (the first line - _use..._ - is the Stata command, the rest is basically the error message), I get

>use "C:\Users\XXXX\Desktop\foo.dta"
dataset too large
    This .dta file format was created by Stata/MP and has more variables than your
    Stata can handle.
r(459);

This is clearly not the case. So if this problem could be resolved in haven, that would be much appreciated!

**Comment by kuriwaki** [comment]
I get an error as well, but with the following StataMP (version 15.1) error message. 

> . use "~/Dropbox/foo.dta", clear
.dta file corrupt
    The marker </sortlist> was not found in the file where it was expected to be.  This means that the file was
    written incorrectly or that the file has subsequently become damaged.
r(688);

Importantly, this only happens when `version = 15` in `write_dta`. I can open the dta fine when `version = 14` (the default) or any other version value from 8 to 14.

**Comment by LulinS** [comment]
Same errors. Appreciated if it can be solved.

**Comment by kuriwaki** [comment]
I updated above [my comment](https://github.com/tidyverse/haven/issues/461#issuecomment-509030486) so the error is reproducible by copy-pasting the snippet into  Stata. The online datasets I read from are two that I generated in haven.  Hope it helps.

**Comment by evanmiller** [comment]
Thanks for the report. It appears that the integer size of column indexes changed with Stata 15. I'll have a fix of some sort soon.

**Comment by hadley** [comment]
I've updated the version of readstat embedded in haven, so this should be fixed in the development version. Please let me know if not.
