### ISSUE TITLE
Error in df_parse_sav_file(spec, encoding, user_na): The file's timestamp string is invalid

### ISSUE THREAD

**Issue by mihagazvoda** [tidyverse/haven#469]
When I try to read `.sav` file using Tidyverse package haven and it's function `read_sav` I get:
```
Invalid time string (length=8):  0: 0: 0
Error in df_parse_sav_file(spec, encoding, user_na): 
The file's timestamp string is invalid.
```
However, if I use `foreign::read.spss` it reads the file with the warning:
```
Compression bias (0) is not the usual value of 100
```
Timestamp values are around 13445740800 - which is strange (seems like epoch time in tenths of a second).

**Comment by evanmiller** [comment]
Hi, what software produced the SAV file in question?

**Comment by hadley** [comment]
Closing this issue due to lack of response.
