### ISSUE TITLE
All Variables in SAS Data Set Produced are Numeric

### ISSUE THREAD

**Issue by npaszty** [tidyverse/haven#480]
**Environment**
NAME="Red Hat Enterprise Linux Server"
VERSION="7.6 (Maipo)"
R version: 3.5.3
SAS version: 9.04.01M3P062415

**Process**
In R Studio, reading csv file to write xpt file with read.csv and write_xpt respectively.
In SAS Studio reading xpt file with proc copy. Variable naming and data in csv file conform to SAS requirements as they are CDISC SDTM.

**Logs**
R: no notes, warnings or errors written to console
SAS: Nothing remarkable in the the log. Same number of records and variables as original csv file.
 NOTE: Input library XPTIN is sequential.
 NOTE: Copying XPTIN.DM to SASOUT.DM (memtype=DATA).
 NOTE: BUFSIZE is not cloned when copying across different engines. System Option for BUFSIZE was used.
 NOTE: There were 270 observations read from the data set XPTIN.DM.
 NOTE: The data set SASOUT.DM has 270 observations and 25 variables.

**Issue**
In resulting SAS data set all variables are type numeric and have no labels.

**Code**
```r
DM <- read.csv("/opt/bee/analyses/CIN/cin_1970/Curation/Prod/DM.csv")
write_xpt(DM, "/opt/bee/analyses/CIN/cin_1970/Curation/Prod/DM.xpt", version =5)
```
```SAS
libname sasout '/opt/bee/analyses/CIN/cin_1970/Curation/Prod';
libname xptin xport '/opt/bee/analyses/CIN/cin_1970/Curation/Prod/DM.xpt';
proc copy in=xptin out=sasout memtype=data;
run;
```

**Comment by hadley** [comment]
1. What should the variable types be?
1. Where do the labels come from?

**Comment by npaszty** [comment]
looks like much of my issue can be attributed to being an R newbie. here are my answers.
1. Variable types should remain as source type so character = character, numeric = numeric. what I found in subsequent testing is that when reading CSV in to R all the character variables are converted to factor variables and during the transport file read in SAS those are converted to numeric variables. so stringsAsFactors=FALSE took care of that.
2. The labels come from the setting attr() on both the data set and the variables. I have the variable labels coming through now but not the data set label. In SAS you can run proc contents on a data set and it will reveal the meta data for the data set and variables. in my proc contents the data set label is missing. I added it to the R data frame by attr(DM, "label") <- "Demographics". Does the write_xpt() function need to have this attribute set in a different way?
3. I did not try this given the findings in 1. and 2.
