### ISSUE TITLE
`labelled` objects error on print when label includes named NA

### ISSUE THREAD

**Issue by aaronrudkin** [tidyverse/haven#481]
I have run into an unusual case where the labels vector includes a named NA.

```r
library(tidyverse)
library(haven)

x = c(1, NA)
labels <- c(1, NA)
names(labels) <- c("a", NA) 

result <- labelled(x, labels)
result # error in data.frame
```

In the motivating case the labels vector is constructed by deframing a tibble column, but as you can see the reprex produces the error just as well. Please note that `labels = c("a" = 1, NA)` works fine. The error only occurs when NA is a named NA.

I discovered this bug when trying to isolate a bug that was coercing NAs to -(2^32). I have not yet located that bug but I'll file it separately if I can reprex it.

**Comment by hadley** [comment]
Minimal reprex:

``` r
library(haven)

labels <- c(1, NA)
names(labels) <- c("a", NA) 

labelled(c(1, NA), labels)
#> <Labelled double>
#> [1]  1 NA
#> 
#> Labels:
#> Error in data.frame(value = value, label = names(labels)): row names contain missing values
```

<sup>Created on 2019-11-06 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>
