### ISSUE TITLE
Variable character length limit for Stata not respected by write_dta

### ISSUE THREAD

**Issue by JackLandry** [tidyverse/haven#485]
Stata has a variable length limit of 32 characters. However, you can export data with variable names over 32 characters from R using write_dta. The result will successfully read into Stata, but you can't perform any operations on the variable or even rename it to something shorter. It's virtually inoperable. Therefore, I think a good addition to haven would be to give an error when exporting dataframes that include variable names with more than 32 characters, or at least a warning to shorten the variable names. Quick example below, including the Stata code that causes errors. 

```r
library(haven)
test <- data.frame("a_variable_name_with_too_many_characters" = 1)
write_dta(test, "test.dta")

##Stata code below 
use "test.dta", clear
tab a_variable_name_with_too_many_characters
ren a_variable_name_with_too_many_characters shorter_varname
```

**Comment by hadley** [comment]
Longer names _are_ supported in stata 14. Export to version 13 if you want the error:

``` r
library(haven)
test <- data.frame("a_variable_name_with_too_many_characters" = 1)
write_dta(test, "test.dta", version = 13)
#> Error: The following variable names are not valid Stata variables: `a_variable_name_with_too_many_characters`
```

<sup>Created on 2020-04-20 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by JackLandry** [comment]
Hi @hadley, unfortunately, longer names are still not supported as of Stata 16, see here: https://www.stata.com/manuals/r.pdf#rLimits 
The maximum length of a variable name is 32 characters.

**Comment by hadley** [comment]
Oh, the problem is that I misinterpreted #383 — and accidentally removed the check for both length and ASCII-ness
