### ISSUE TITLE
n_max does not speed up SAS import

### ISSUE THREAD

**Issue by mayer79** [tidyverse/haven#486]
Thanks for the great package. In haven 2.2, the very useful option `n_max` has been introduced.

I tested it with different SAS data sets with the following result:

- Using `n_max` gives indeed `n_max` rows.

- *The import does not seem to be much faster than importing all lines.*

Is the second observation as expected?

**Comment by corybrunson** [comment]
I was curious about this too, but i've noticed that reads _after_ an initial read of a given file (whatever number of rows were read) both (a) depend more clearly on the number of rows read and (b) are much faster than the first. I took a cursory look at what information about a file might be stored in the active session, e.g. `ls(all.names = TRUE)` and `options()`, but i could not figure it out; and it doesn't seem to be documented in the package. Have i missed it? If not, could this be explained somewhere?

**Comment by hadley** [comment]
@mayer79 it's hard to know; a lot depends on the specifics of your dataset, and you haven't given any details.

@corybrunson Usually the second read is faster than than the first because the OS caches it.
