### ISSUE TITLE
if with value labels, label of variables is missing when exporting into SPSS 

### ISSUE THREAD

**Issue by 180312allison** [tidyverse/haven#487]
I have updated the package to newest version. 
I read my data and then try to export it into sav format.
Everything is OK with d, but when I export it into sav format, I found the label of some variables is missing. After careful examination, I noticed that these variables are all those that have value labels. What is wrong? 

> data = data.frame(var1 = c(1,2), var2 = c(2,3))
> attr(data$var1,"label") = "math"
> attr(data$var2,"label") = "physics"
attr(data$var1, "labels") = c(0,1)
> attr(attr(data$var1,"labels"), "names") = c("good", "bad")
> str(data)
'data.frame':	2 obs. of  2 variables:
    $ var1: num  1 2
..- attr(*, "label")= chr "math"
..- attr(*, "labels")= Named num  0 1
.. ..- attr(*, "names")= chr  "good" "bad"
$ var2: num  2 3
..- attr(*, "label")= chr "physics"
> export(data, "./Outputdata/test.sav")

The SPSS file I get: 
![the SPSS file result](https://user-images.githubusercontent.com/37295094/70739363-98b86800-1d51-11ea-83b7-81146b72e4c9.jpg)

if I used  write_sav(data, "./Outputdata/test.sav"), then the SPSS file I got is like this: 
"Label"s are all there but "Values" labels were disappeared. 
![value labels are lost](https://user-images.githubusercontent.com/37295094/70765839-f4591480-1d96-11ea-9b8f-2a4027f1e9c5.jpg)

**Comment by gorcha** [comment]
Not sure where the `export()` function comes from so can't comment on that, but `write_sav()` will only write value labels if the vector has the class haven_labelled or haven_labelled_spss.

If you create the labelled vector using `labelled()` or `labelled_spss()` they will write successfully. Using the above example:
``` r
library(haven)

data = data.frame(var1 = c(1,2), var2 = c(2,3))
data$var1 = labelled(data2$var1, labels = c(good = 0, bad = 1), label = "math")
attr(data$var2,"label") = "physics"
str(data)
#> 'data.frame':    2 obs. of  2 variables:
#>  $ var1: 'haven_labelled' num  1 2
#>   ..- attr(*, "label")= chr "math"
#>   ..- attr(*, "labels")= Named num  0 1
#>   .. ..- attr(*, "names")= chr  "good" "bad"
#>  $ var2: num  2 3
#>   ..- attr(*, "label")= chr "physics"
write_sav(data, "test.sav")
```

**Comment by 180312allison** [comment]
Thanks a lot！The "export" function comes from the packages "rio", and according to its documentation, it would use haven::write_sav() for SPSS file. It seems there is something wrong with "export".

**Comment by 180312allison** [comment]
> 
> 
> Not sure where the `export()` function comes from so can't comment on that, but `write_sav()` will only write value labels if the vector has the class haven_labelled or haven_labelled_spss.
> 
> If you create the labelled vector using `labelled()` or `labelled_spss()` they will write successfully. Using the above example:
> 
> ```r
> library(haven)
> 
> data = data.frame(var1 = c(1,2), var2 = c(2,3))
> data$var1 = labelled(data2$var1, labels = c(good = 0, bad = 1), label = "math")
> attr(data$var2,"label") = "physics"
> str(data)
> #> 'data.frame':    2 obs. of  2 variables:
> #>  $ var1: 'haven_labelled' num  1 2
> #>   ..- attr(*, "label")= chr "math"
> #>   ..- attr(*, "labels")= Named num  0 1
> #>   .. ..- attr(*, "names")= chr  "good" "bad"
> #>  $ var2: num  2 3
> #>   ..- attr(*, "label")= chr "physics"
> write_sav(data, "test.sav")
> ```

**Comment by gorcha** [comment]
No worries, happy to help!

After having a brief look at the rio package it looks like they're doing something funny with the attributes before writing out, I'd recommend logging an issue there.
