### ISSUE TITLE
read_sas : col_select and NULL value

### ISSUE THREAD

**Issue by Sdurier** [tidyverse/haven#489]
Hi,

I don't know if the problem comes from haven or from rlang but the parameter col_select in read_sas doesn't work when given a name with value NULL attached.

SD
```r
path <- system.file("examples", "iris.sas7bdat", package = "haven")
read_sas(path, col_select = NULL) # OK
var_select <- NULL
read_sas(path, col_select = var_select)
# Error: Can't find any columns matching `col_select` in data.
```

**Comment by hadley** [comment]
Right, because it takes the name of a variable.

**Comment by Sdurier** [comment]
Yes but it happens only with the NULL value, so it seemed strange at first sight.
Thank you for your answer

```r
read_sas(path, col_select = "Species") # OK
var_select <- "Species"
read_sas(path, col_select = var_select) # OK
```
