### ISSUE TITLE
Way to quickly determine number of rows in data set?

### ISSUE THREAD

**Issue by richarddmorey** [tidyverse/haven#490]
I'm using `read_dta` to import Stata files and some of the files that I am importing a large (several gigabytes) and take a while to load (20-30 minutes). For some preliminary reports, it would be useful to quickly determine how many rows there are in the data set without loading the entire data set. Is there any way to do this?

**Comment by evanmiller** [comment]
You can use the underlying command-line tool:

https://github.com/WizardMac/ReadStat

```
$ ./readstat ~/Downloads/GSS2018.dta
Format: Stata binary file (DTA)
Columns: 1064
Rows: 2348
Format version: 113
Byte order: little-endian
```

This works more or less instantaneously.

**Comment by richarddmorey** [comment]
Works brilliantly; thank you @evanmiller.
