### ISSUE TITLE
Error in df_parse_sas_file while reading SAS database

### ISSUE THREAD

**Issue by Ghanshyamsavaliya** [tidyverse/haven#497]
Hi,

I am trying to access the SAS database through haven library.

**Using below code:** 
`
library(haven)`
`products <- read_sas("C:/File.sas7bdat", 
                     NULL)`
`View(products)
`

While reading the above code, I am receiving below error:
`Error in df_parse_sas_file(spec_data, spec_cat, encoding = encoding, catalog_encoding = catalog_encoding,  : 
  Failed to parse C:/File.sas7bdat: File has unsupported compression scheme.`

I have checked your few issue where this kind of error was mentioned as file format error but I have also tried the same file in Python as well but over there I am able to read the file.

Could you please me to solve above issue?

Regards,
Ghanshyam

**Comment by hadley** [comment]
Unfortunately there's not much we can do without the file you are trying to load.
