### ISSUE TITLE
Feature request: Stata file characteristics into R attributes

### ISSUE THREAD

**Issue by randrescastaneda** [tidyverse/haven#498]
Dear all, 

A small feature request. 

It would be great to load all the [chracteristics](https://www.stata.com/manuals/pchar.pdf#pchar) of a dta file into attributes in R when using read_dta(). `characteristics` in stata are basically the same thing as attributes in R. Right now, only the characteristics saved as [notes ](https://www.stata.com/manuals/dnotes.pdf#dnotes) are loaded into R as attributes. All the other characteristics are not loaded. 

When I use [readstata13](https://www.rdocumentation.org/packages/readstata13/versions/0.9.2) all the characteristics are saved in attributes in the list `expansion.fields`. I use this package as a temporary solution, but I prefer to use `haven` as it integrates very well with all my `tidyverse` structure. 

Thank you so much. 
Best.

**Comment by hadley** [comment]
@evanmiller does ReadStat expose this info?

**Comment by evanmiller** [comment]
@hadley ReadStat only exposes the notes.

**Comment by hadley** [comment]
@randrescastaneda sorry, this doesn't look like something we can support at the moment.
