### ISSUE TITLE
SAV encoding for label(s)

### ISSUE THREAD

**Issue by rubenarslan** [tidyverse/haven#499]
I think `read_sav` does not apply its _encoding argument_ to __variable and value labels__. I have to manually set them to `latin1` for a dataset where they are (correctly) encoded that way. I wanted to make a reprex, see below, but apparently I cannot round-trip an encoding other than UTF-8 and I currently don't have SPSS. 

I hope this is easy to fix based on the description. Please let me know if this is not clear. I can share an sav file with latin1 encoding, but would first have to truncate a dataset that I may not share on another computer with SPSS.

## Not a real reprex, only shows encoding being lost

``` r
x <- data.frame(y = 1)
attributes(x$y)$label <- "ä"
attributes(x$y)$label <- iconv(attributes(x$y)$label, from = "UTF-8", to = "latin1")
Encoding(attributes(x$y)$label)
#> [1] "latin1"
haven::write_sav(x, "x.sav")
x <- haven::read_sav("x.sav")
x$y
#> [1] 1
#> attr(,"label")
#> [1] "ä"
#> attr(,"format.spss")
#> [1] "F8.2"
Encoding(attributes(x$y)$label)
#> [1] "UTF-8"
```

<sup>Created on 2020-02-27 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

## Workaround
```r
for (i in 1:ncol(base2)) {
  lab <-  attributes(base2[[i]])[["label"]]
  if (!is.null(lab)) {
    Encoding(lab) <- "latin1"
    lab <- iconv(lab, from = "latin1", to = "UTF-8")
    attributes(base2[[i]])[["label"]] <- lab
  }
  labs <- attributes(base2[[i]])[["labels"]]
  if (!is.null(labs)) {
    Encoding(names(labs)) <- "latin1"
    names(labs) <- iconv(names(labs), from = "latin1", to = "UTF-8")
    attributes(base2[[i]])[["labels"]] <- labs
  }
}
```

**Comment by hadley** [comment]
`read_sav()` always loads data into UTF-8 encoding.

**Comment by rubenarslan** [comment]
Sorry, is this a wontfix? 
To restate the error description (maybe giving an "almost reprex" was misleading?).

`read_sav` correctly converts _data_ (eg. character variables) into UTF-8 even when encoded as latin1 in SPSS. But it doesn't do so for _metadata_ (variable/value labels). I'd say that's a bug. Do you understand this and think this is not a bug? Or do I need to get SPSS again and make a reprex?

**Comment by hadley** [comment]
Your reprex doesn't demonstrate any problem?

**Comment by rubenarslan** [comment]
I was trying to avoid installing the JRE and SPSS again to be able to make a full reprex, and thought the verbal description might be enough (I also thought maybe you didn't intend haven to always convert to UTF-8. Here's one now. Pretty sure this is a bug.

See this file [example_of_encoding_problem.sav.zip](https://github.com/tidyverse/haven/files/4510658/example_of_encoding_problem.sav.zip).

String variable contents, variable names, and variable labels are correctly transformed from latin1 to UTF8, but not value labels. With files I was sent, I've also had problems with variable labels in the past, but I think I cannot create a file showing this without setting up a Windows computer with a latin1 locale (SPSS follows the system locale by default).

``` r
enc <- haven::read_sav("example_of_encoding_problem.sav")
testthat::expect_equal(enc$pfz14[[1]], "äää")
Encoding(enc$pfz14[[1]])
#> [1] "UTF-8"
testthat::expect_equal(names(enc)[3], "pzufmo2ä")
Encoding(names(enc)[3])
#> [1] "UTF-8"
testthat::expect_equal(attributes(enc$pzufmo1)$label, 
                       "Zufriedenheit Mobilität im Allgemeinen")
testthat::expect_equal(names(attributes(enc$pfz14)$labels)[[11]],
                       "[-6] Fragebogenversion mit geaenderter Filterführung")
#> Error: names(attributes(enc$pfz14)$labels)[[11]] not equal to "[-6] Fragebogenversion mit geaenderter Filterführung".
#> 1/1 mismatches
#> x[1]: "[-6] Fragebogenversion mit geaenderter FilterfÃ¼hrung"
#> y[1]: "[-6] Fragebogenversion mit geaenderter Filterführung"
```

<sup>Created on 2020-04-21 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by evanmiller** [comment]
@rubenarslan Where did your example file come from? Inspecting its contents, it appears that `Filterführung` is encoded with UTF-8 (umlaut at byte #579), even though the rest of the file is Latin-1.

The content error arises because ReadStat is treating that UTF-8 string as Latin-1, and then attempting to transcode it to UTF-8. This is possibly a bug in the program that produced the file - if it is SPSS, I will need to investigate further to figure out which versions of SPSS use UTF-8 value labels when the rest of the file is another encoding.

**Comment by rubenarslan** [comment]
@evanmiller Hi, thanks for jumping in. I wanted to make a reprex based on a file I'm working with which is distributed by the DIW (German Economic Research Institute). I don't know exactly how they produce their files, but they somehow export them straight from their database and I think it might be a custom program. So the fault could be with them (but I've also gotten files from them where the encoding just works, maybe more recent/different team).

I now also noticed that when trying to make a minimal file, that the resaving fixed the problems I had with umlauts in variable labels, presumably because I save the file in SPSS instead of using their custom program. 
So unfortunately this reprex doesn't reproduce my exact problem and I don't know how to make a reprex with a file that I am allowed to share given that editing in SPSS doesn't work, nor does roundtripping in haven. 

If your hunch is that this is not a general problem, but a problem with this specific file/program, I have my workaround for this file, and obviously you don't need to fix problems resulting from nonstandard software. Sorry for the bother, I figured it was something about ReadStat because of the discrepancy between character vars and metadata.

**Comment by evanmiller** [comment]
@rubenarslan The file's header is marked as

```
IBM SPSS STATISTICS DATA FILE 64-bit Macintosh 20.0.0
```

In my general experience nobody is really running an exact-but-old X.0.0 release, and so it is likely a custom program of some kind. Most SAV-producing libraries are polite enough to leave hints in the header about their origin, but I'm not seeing any tell-tale clues in this file. It's possible DIW has some kind of back-end "solution" from IBM that includes the exporter.

I could possibly provide a path in the code that looks for "64-bit Macintosh 20.0.0 and encoding is Latin-1", but this could conceivably cause problems for other files. Is there any possibility of raising the issue directly with the DIW?

Also: Do we know if SPSS reads these files in correctly? If so, then SPSS must know something about the files that I do not.

I notice that the `foreign` package has the same problem as haven (see value label for -6):

```
> read.spss("example_of_encoding_problem.sav")
re-encoding from latin1
$pfz14
[1] "äää                                     " "                                    1.00"

$pzufmo1
[1] [-2] trifft nicht zu                         [8] 8 Zufrieden: Skala 0-Niedrig bis 10-Hoch
17 Levels: [-6] Fragebogenversion mit geaenderter FilterfÃ¼hrung ... [10] 10 Zufrieden: Skala 0-Niedrig bis 10-Hoc

$pzufmo2ä
[1] [-2] trifft nicht zu                         [7] 7 Zufrieden: Skala 0-Niedrig bis 10-Hoch
17 Levels: [-6] Fragebogenversion mit geaenderter FilterfÃ¼hrung ... [10] 10 Zufrieden: Skala 0-Niedrig bis 10-Hoc

attr(,"label.table")
attr(,"label.table")$pfz14
NULL

attr(,"label.table")$pzufmo1
        [10] 10 Zufrieden: Skala 0-Niedrig bis 10-Hoc          [9] 9 Zufrieden: Skala 0-Niedrig bis 10-Hoch 
                                                 "10"                                                   "9" 
         [8] 8 Zufrieden: Skala 0-Niedrig bis 10-Hoch          [7] 7 Zufrieden: Skala 0-Niedrig bis 10-Hoch 
                                                  "8"                                                   "7" 
         [6] 6 Zufrieden: Skala 0-Niedrig bis 10-Hoch          [5] 5 Zufrieden: Skala 0-Niedrig bis 10-Hoch 
                                                  "6"                                                   "5" 
         [4] 4 Zufrieden: Skala 0-Niedrig bis 10-Hoch          [3] 3 Zufrieden: Skala 0-Niedrig bis 10-Hoch 
                                                  "4"                                                   "3" 
         [2] 2 Zufrieden: Skala 0-Niedrig bis 10-Hoch          [1] 1 Zufrieden: Skala 0-Niedrig bis 10-Hoch 
                                                  "2"                                                   "1" 
         [0] 0 Zufrieden: Skala 0-Niedrig bis 10-Hoch                                     [-1] keine Angabe 
                                                  "0"                                                  "-1" 
                                 [-2] trifft nicht zu                                     [-3] nicht valide 
                                                 "-2"                                                  "-3" 
                    [-4] unzulaessige Mehrfachantwort             [-5] in Fragebogenversion nicht enthalten 
                                                 "-4"                                                  "-5" 
[-6] Fragebogenversion mit geaenderter FilterfÃ¼hrung 
                                                 "-6" 

attr(,"label.table")$pzufmo2ä
        [10] 10 Zufrieden: Skala 0-Niedrig bis 10-Hoc          [9] 9 Zufrieden: Skala 0-Niedrig bis 10-Hoch 
                                                 "10"                                                   "9" 
         [8] 8 Zufrieden: Skala 0-Niedrig bis 10-Hoch          [7] 7 Zufrieden: Skala 0-Niedrig bis 10-Hoch 
                                                  "8"                                                   "7" 
         [6] 6 Zufrieden: Skala 0-Niedrig bis 10-Hoch          [5] 5 Zufrieden: Skala 0-Niedrig bis 10-Hoch 
                                                  "6"                                                   "5" 
         [4] 4 Zufrieden: Skala 0-Niedrig bis 10-Hoch          [3] 3 Zufrieden: Skala 0-Niedrig bis 10-Hoch 
                                                  "4"                                                   "3" 
         [2] 2 Zufrieden: Skala 0-Niedrig bis 10-Hoch          [1] 1 Zufrieden: Skala 0-Niedrig bis 10-Hoch 
                                                  "2"                                                   "1" 
         [0] 0 Zufrieden: Skala 0-Niedrig bis 10-Hoch                                     [-1] keine Angabe 
                                                  "0"                                                  "-1" 
                                 [-2] trifft nicht zu                                     [-3] nicht valide 
                                                 "-2"                                                  "-3" 
                    [-4] unzulaessige Mehrfachantwort             [-5] in Fragebogenversion nicht enthalten 
                                                 "-4"                                                  "-5" 
[-6] Fragebogenversion mit geaenderter FilterfÃ¼hrung 
                                                 "-6" 

attr(,"variable.labels")
                                   pfz14                                  pzufmo1                                 pzufmo2ä 
           "Haeufigkeit Spazieren gehen" "Zufriedenheit Mobilität im Allgemeinen"      "Zufriedenheit Mobilität im Winter" 
attr(,"codepage")
[1] 28591
Warning message:
In read.spss("example_of_encoding_problem.sav") :
  example_of_encoding_problem.sav: Long string value labels record found (record type 7, subtype 21), but ignored
```

Unless there are other client programs that read these files correctly (PSPP or SPSS), my inclination would be to close the issue.

**Comment by ytmytm** [comment]
Checked on SPSS 25 - it decodes the file from latin1
```
Variable Information								
Variable	Position	Label	Measurement Level	Role	Column Width	Alignment	Print Format	Write Format
pzufmo1	2	Zufriedenheit Mobilität im Allgemeinen	Scale	Input	27	Right	F40.2	F40.2
Variables in the working file								
```
But the codelist has wrong entry as well:
```
Variable Values		
Value		Label
pzufmo1	-6,00	[-6] Fragebogenversion mit geaenderter FilterfÃ¼hrung
(...)
```

**Comment by rubenarslan** [comment]
hey, I'm good with closing this issue. My shareable example doesn't have the same problem as the file I can't share, it seems likely it's an issue on their end, and I have low expectations for being able to work with them to fix the problem on their end, so I'll just use my workaround.

@evanmiller the header was regenerated when I saved my example. I'm "using" 20.0.0. don't know how to check the header for the original file, but maybe we just drop it.

**Comment by evanmiller** [comment]
@rubenarslan I see. In light of @ytmytm's report here, and without access to the specific generating files, there's not much I can do.

You can check the header in any text editor by the way - just look at the first 30 bytes or so.

**Comment by e-kotov** [comment]
@rubenarslan , can you check if https://janmarvin.github.io/readspss/reference/read.sav.html solves your problem?
```r
readspss::read.sav("your_sav_file.sav", encoding = 2, fromEncoding = "CP1252", convert.factors = T)
```
