### ISSUE TITLE
[maybe bug?] convert variable into factor with associated value labels

### ISSUE THREAD

**Issue by tobwen** [tidyverse/haven#501]
The library _sjlabelled_ recently came up with a function, I wasn't able to find in _haven_. It allows to convert variable into factor with associated value labels: https://strengejacke.github.io/sjlabelled/reference/as_label.html

Would it be possible to implement this in _haven_?

**Edit**: Actually, _as_factor_ should do it, but `View(as_factor(dataset))` doesn't seem to work on an SPSS dataset imported via _haven_. I need to use _add_labelled_class_ from https://cran.r-project.org/web/packages/expss/ to get it working.

So it's actually implemented, but it's broken?

**Comment by gorcha** [comment]
Hey tobwen,

`as_factor()` works fine from what I can see. For e.g.:
``` r
library(haven)
library(dplyr)

x <- tibble(a = labelled(c(1, 1, 1, 2, 2), c("male" = 1, "female" = 2)),
            b = labelled(c(0, 0, 1, 1, 1), c("yes" = 1, "no" = 0)))
x
#> # A tibble: 5 x 2
#>            a         b
#>    <dbl+lbl> <dbl+lbl>
#> 1 1 [male]     0 [no] 
#> 2 1 [male]     0 [no] 
#> 3 1 [male]     1 [yes]
#> 4 2 [female]   1 [yes]
#> 5 2 [female]   1 [yes]

as_factor(x)
#> # A tibble: 5 x 2
#>   a      b    
#>   <fct>  <fct>
#> 1 male   no   
#> 2 male   no   
#> 3 male   yes  
#> 4 female yes  
#> 5 female yes
```

Do you have a reproducible example (reprex)?

Danny

**Comment by tobwen** [comment]
Danny, you're totally right. Don't know what was wrong on my side. It works when feeding the function through `as_factor`. Check this out (German text, since I wanted to use a real life example stripped from real data):

Please download [test.zip](https://github.com/tidyverse/haven/files/4283975/test.zip)

```
library(haven)
library(expss)
library(pivottabler)

gimme_pivot <- function(obj) {
    pt <- pivottabler::PivotTable$new()
    pt$addData(test)
    pt$addRowDataGroups("stadt", totalCaption="gesamt", addTotal = T)
    pt$addColumnDataGroups("altersgruppen")
    pt$defineCalculation(calculationName="count", caption="n() of answers", summariseExpression="n()")
    pt$evaluatePivot()
    return (pt)
}
```

## Okay, this doesn't work of course:
```
test <- haven::read_spss("test.sav")
gimme_pivot(test)
        2  4  NA  Total  
1          1          1  
2       1             1  
3              1      1  
gesamt  1  1   1      3
```

## I thought, that's the only way, since it adds the class _labelled_
```
gimme_pivot(expss::add_labelled_class)
        30 bis unter 45 Jahre  über 65 Jahre  NA  Total  
abc                                        1          1  
def                         1                         1  
ghi                                            1      1  
gesamt                      1              1   1      3

```

## But this also works as expected!
```
gimme_pivot(haven::as_factor(add_labelled_class))
        30 bis unter 45 Jahre  über 65 Jahre  NA  Total  
abc                                        1          1  
def                         1                         1  
ghi                                            1      1  
gesamt                      1              1   1      3  
```

**Comment by tobwen** [comment]
I think we can close this issue, can't we?
