### ISSUE TITLE
Inconsistent import of dates with value labels or missings via read_sav

### ISSUE THREAD

**Issue by beckerbenj** [tidyverse/haven#505]
Not sure whether this is a bug report or feature request:

In SPSS, variables of class "Date" can be given value labels or missings. In these cases, read_sav with user_na = TRUE transforms the variables into class "haven_labelled_spss" instead of "Date". The actual values, value labels and missings are then stored as numeric values, but it seems that very different transformations are applied (Dates in the attributes seem to follow the logic documented here: http://scs.math.yorku.ca/index.php/R:_Importing_dates_from_SPSS). So values and value labels and missings for "Date" variables do not match after importing via read_sav with user_na = TRUE. 

Would it be possible to assimilate values and the corresponding attributes and to state the necessary conversion back to "Date" explicitly somewhere in the haven documentation, maybe here: https://cran.r-project.org/web/packages/haven/vignettes/datetimes.html?

Example sav data with a unlabeled and a labeled date variable:
![grafik](https://user-images.githubusercontent.com/35807186/79491197-5f08ae00-801e-11ea-8f69-b6adb3716c3a.png)

[labeled_date_illustration.zip](https://github.com/tidyverse/haven/files/4489028/labeled_date_illustration.zip)
``` r
test <- haven::read_sav("N:/spss/labeled_date_illustration.sav", user_na = TRUE)
lapply(test, function(x) x)
#> $date1
#> [1] "1990-01-01"
#> 
#> $date2
#> <Labelled SPSS double>
#> [1] 7305
#> Missing values: 12850531200
#> 
#> Labels:
#>        value   label
#>  12850531200 missing

## same value has now different values in variable and attributes
as.numeric(test$date2)
#> [1] 7305
attributes(test$date2)$na_values
#> [1] 12850531200
attributes(test$date2)$labels
#>     missing 
#> 12850531200

## convert to original value with different transformations
as.Date(as.numeric(test$date2), origin = "1970-01-01")
#> [1] "1990-01-01"
as.Date(attributes(test$date2)$na_values/86400, origin = "1582-10-14")
#> [1] "1990-01-01"
```

<sup>Created on 2020-04-16 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by hadley** [comment]
I think this is sufficiently esoteric that we'll never have the time to implement it in haven, sorry.
