### ISSUE TITLE
Consider making `haven_labelled` vectors inherit from base type

### ISSUE THREAD

**Issue by lionel-** [tidyverse/haven#509]
Might have helped with https://github.com/yrosseel/lavaan/issues/163

**Comment by larmarange** [comment]
In that case, `labelled()` should return vectors with double classes (i.e. `c("haven_labelled", "numeric")` or `c("haven_labelled", "character")`)

**Comment by hadley** [comment]
@larmarange yes, that's what @lionel- is saying.

**Comment by lionel-** [comment]
Do we warn when we create these classes? It would help to link to a pkgdown page that explains what the labelled class is and why, and how to convert to numeric or factor before diving into data analysis.

**Comment by hadley** [comment]
I think if you look at the docs for the package it's reasonably obvious, but I can do an additional pass to make sure. I don't think very many people have problems though.
