### ISSUE TITLE
Error "Can't safely combine labelled vectors with different label sets."

### ISSUE THREAD

**Issue by deschen1** [tidyverse/haven#511]
With the latest `vctrs`, `dplyr` and `haven` packages, simple arithmetics are not possible anymore when the objects are of type haven_labelled.

I know that there always is some ambiguity when combining categorial data, e.g. factors with different labels. However I'd consider it a bug in case of the haven_labelled objects if they have the same "main" type (e.g. numeric) and just the labels differ. From a data analysis point of view, labels of a numeric type of object should never tell us anything about the mathematical operations that are allowed to be performed on these objects.

Consider the following data:

```r
test <- structure(list(Q16_1 = structure(c(1, 1, 0, 1, 1, 1, 1, 1, 1, 1),
                                         label = "Q16_1 MYLABEL 1",
                                         labels = c(`Not Selected Q16_1` = 0, 'Selected Q16_1' = 1),
                                         class = "haven_labelled"),
                       Q16_2 = structure(c(1, 1, 0, 1, 0, 1, 1, 1, 0, 0),
                                         label = "Q16_2 MYLABEL 2",
                                         labels = c(`Not Selected Q16_2` = 0, 'Selected Q16_2' = 1),
                                         class = "haven_labelled")),
                  class = c("tbl_df", "tbl", "data.frame"), row.names = c(NA, -10L))
```

Imagine, Q16_1 and Q16_2 are survey questions where respondents provided information which groceries they would they would pick from a range of available items. That's a pretty standard multi-response survey setting, where each available item is represented by its own column and coded "1" if it was selected by the respondent and "0" if it wasn't selected.

Now, the most simple thing that you could probably do is to calculate how many items a respondent has selected, so you simply want to calculate the sum across all items. This has worked smoothly until the latest update to the `haven` package, but now fails with an error:

```r
test %>%
  rowwise() %>%
  mutate(x = sum(c_across(num_range(prefix = "Q16_", range = 1:2))))
```

Error:

```r
Error: Problem with `mutate()` input `x`.
x Can't combine `Q16_1` <labelled<double>> and `Q16_2` <labelled<double>>.
Can't safely combine labelled vectors with different label sets.
i Input `x` is `sum(c_across(num_range(prefix = "Q16_", range = 1:2)))`.
i The error occured in row 1.
Run `rlang::last_error()` to see where the error occurred.
```

**Comment by courtiol** [comment]
Smaller reprex:
``` r
sum(haven::labelled(1, labels = c("A" = 1)), 
    haven::labelled(1, labels = c("A" = 1)))
#> <labelled<double>[1]>
#> [1] 2
#> 
#> Labels:
#>  value label
#>      1     A

sum(haven::labelled(1, labels = c("A" = 1)), 
    haven::labelled(1, labels = c("B" = 1)))
#> Error: Can't combine `..1` <labelled<double>> and `..2` <labelled<double>>.
#> Can't safely combine labelled vectors with different label sets.
```
<sup>Created on 2020-05-13 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by hadley** [comment]
I think if you want to ignore the labels, you should convert to some data structure that doesn't have them. It's not obvious to me that stripping the labels is a good principle.

**Comment by deschen1** [comment]
I'm not saying the labels should be stripped. I'm just saying that relying on the labels as a source to determine the appropriateness of arithmetic operations should be avoided. Labels are informative to humans, but should not be for machines if the underlying data structure is of a numeric type (as opposed to e.g. factor types).

My point is just that the current `haven` package prevents the user from doing valid arithmetic operations. It was a simple task in the past and worked well, but the current approach is probably too strict. Converting the columns to e.g. numeric is a workaround, yes, but it brings a lot of disadvantages (i.e. losing all the labels. And having labels is the whole point of the `haven` package).

**Comment by courtiol** [comment]
But, @deschen1, if you do not strip them when doing arithmetic, which labels would you expect to find after, say: 

``` r
haven::labelled(c(0, 1), c('Not Selected Q16_1' = 0, 'Selected Q16_1' = 1)) + 
  haven::labelled(c(1, 1), c('Not Selected Q16_2' = 0, 'Selected Q16_2' = 1))
#> <Labelled double>
#> [1] 1 2
#> 
#> Labels:
#>  value              label
#>      0 Not Selected Q16_1
#>      1     Selected Q16_1
```
<sup>Created on 2020-05-14 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

As you can see in this simple code that mimic your rowwise job the old **{haven}** does run but it only keeps the label from the first variable, which is not correct either.

So to me there are only 2 clean options: either it is impossible and vectors must first be converted as indicated by @hadley, or we consider that this is a very common operation (I think it is) and we should allow it but then the labels cannot be kept. (Or both should be possible and set by a global option.)

Am I missing something?

**Comment by deschen1** [comment]
You are right. Doing some arithmetic operation on several vectors with differing labels means that the new variable can't have a default label and the old "keep the first label" is not consistent/correct.

This also makes sense when looking what we are actually doing. the input vectors have their labels, fine. But then you do something, like calculating a sum or mean. Applying these operations already tell us that you can't simply apply some old label, because you have a completely different entity here (e.g. a sum or a mean).

So I wouldn't expect the new variable to have a label at all (i.e. it needs to be manually created afterwards if I want it).

**Comment by hadley** [comment]
Note to self: check that `<labelled<double>> %% <double>` works (used by sjmisc)

**Comment by hadley** [comment]
I'm not 100% convinced that stripping labels in any arithmetic operation is correct, but it seems relatively safe so I'll do it.
