### ISSUE TITLE
Can't convert <integer> to <labelled<double>>

### ISSUE THREAD

**Issue by larmarange** [tidyverse/haven#519]
With the new version of `haven`, an error is produced when comparing a labelled double vector with an integer. I guess that it could be fixed by indicating to `vctrs` how to convert properly.

```r
library(haven)
v <- labelled(c(10, 55, 23, 40, 90, 60), labels = c("90+" = 90), label = "Age")
v < 50
#> [1]  TRUE FALSE  TRUE  TRUE FALSE FALSE
v < 50L
#> Error: Can't convert <integer> to <labelled<double>>.
```

To be noted, there is no problem when comparing a labelled integer vector with a numeric value:

```r
library(haven)
v <- labelled(c(10L, 55L, 23L, 40L, 90L, 60L), labels = c("90+" = 90), label = "Age")
v < 50
#> [1]  TRUE FALSE  TRUE  TRUE FALSE FALSE
v < 50L
#> [1]  TRUE FALSE  TRUE  TRUE FALSE FALSE
```

**Comment by hadley** [comment]
Fixed in 7af774bcf966b504ceda59ce38dc654d513ebdcf
