### ISSUE TITLE
Error: `function.haven_labelled()` not implemented.

### ISSUE THREAD

**Issue by peterolejua** [tidyverse/haven#520]
Arch linux 5.6.14-arch1-1 
RStudio Version 1.2.5042
R version 4.0.0 (2020-04-24)

```r
library(haven)
raw_data <- read_dta(
  "piloto_triage.dta"
  )
summary(raw_data)
```
```Error: `summary.haven_labelled()` not implemented.```

Another example

```{r }
table1(data=data_tabla_2 ,
       ~ .  | resultado_de_la_biopsia,
       droplevels = T,
       overall="Total")
```
```Error: `quantile.haven_labelled()` not implemented.```

**Comment by hadley** [comment]
Could you please rework your reproducible example to use the [reprex package](http://reprex.tidyverse.org) ? That makes it easier to see both the input and the output, formatted in such a way that I can easily re-run in a local session.

**Comment by kommueller** [comment]
Hi, I am experiencing a similar issue using

R Studio Version 1.3.959
R version 4.0.0 (2020-04-24)
haven Version 2.3.0

```
library(haven)
d1 <- read_sav("data/ESS7DE.sav")
mean(d1$agea
```

`Error: `median.haven_labelled()` not implemented.`

**Comment by peterolejua** [comment]
Hello @hadley. A reprex output was given above by @kommueller It's the same problem.

**Comment by peterolejua** [comment]
> Hi, I am experiencing a similar issue using
> 
> R Studio Version 1.3.959
> R version 4.0.0 (2020-04-24)
> haven Version 2.3.0
> 
> ```r
> library(haven)
> 
> d1 <- read_sav("C:/Users/mueller/Nextcloud/Lehre/23-FSS20/stat_ba_fss20/data/ESS7DE.sav")
> 
> summary(d1$agea)
> #> Error: `summary.haven_labelled()` not implemented.
> ```
> 
> Created on 2020-05-28 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)

**Comment by peterolejua** [comment]
I'm not sure if I have to downgrade because everything was working fine a couple of weeks ago

**Comment by kommueller** [comment]
> 
> 
> Hello @hadley. A reprex output was given above by @kommueller It's the same problem. Kom what OS are you working with? also linux?

No, I'm working on Windows 10 - and teaching a class where students with different setups experience the same issue after updating to the latest version of haven.

**Comment by hadley** [comment]
This is a problem with haven 2.2.0; I'll release fix tomorrow.

**Comment by kommueller** [comment]
> 
> 
> This is a problem with haven 2.2.0; I'll release fix tomorrow.

Thank you so much for the great support!

**Comment by hadley** [comment]
Note to self: need to add methods for `median`, qunatile`, and `summary`

**Comment by peterolejua** [comment]
@hadley hello. Thanks for the support. Are we supposed to reinstall it? I don't see an update available. How do we fresh-install it?

**Comment by hadley** [comment]
You can either install it from Github, or wait until I've released it to CRAN.

**Comment by peterolejua** [comment]
CRAN please :)!!! Will it take too much?

**Comment by hadley** [comment]
You can follow the release process at https://github.com/tidyverse/haven/issues/523
