### ISSUE TITLE
Using haven to label data for STATA: Error: If any elements of `.data` are named, all must be named

### ISSUE THREAD

**Issue by drevanzyl** [tidyverse/haven#526]
Hello, 

I'm using haven to label my variables for STATA data exports. For more information about the method I'm using, follow this link: https://community.rstudio.com/t/haven-seems-to-recode-change-variable-values-when-exporting-labeled-data-to-spss-and-stata/23817. Here is the example code:

```
library(haven)

lookup <- lookup <- c(
  "Never [0]"                  = 0,
  "Monthly or less [1]"        = 1,
  "2 to 4 times a month [2]"   = 2,
  "2 to 3 times a week [3]"    = 3,
  "4 or more times a week [4]" = 4
)

audit$a_audit_1_1 =  factor(
  audit$a_audit_1_1,
  levels = lookup,
  labels = names(lookup)
)

# do other tasks in R...
audit$a_audit_1_1 <- labelled(
  x      = lookup[as.character(audit$a_audit_1_1)],
  labels = lookup
)
write_dta(audit, ...)
```

Since June 1, I'm getting the following when applying my labeling scripts to any of my variables:

```
> library(haven)
> df$group <-
+         labelled(x  =  group_lookup[as.character(df$group)],
+                  labels = group_lookup, label = "Study Group")
Error: If any elements of `.data` are named, all must be named
> 
```

Also, none of my variables are labeled in the STATA export. 

I'm assuming that the error might be related to this: [More descriptive error message needed if column names are NA](https://github.com/tidyverse/dplyr/issues/1101). 

I have more than a thousand variables and I can't figure out why this problem recently started or which variable is causing the problem. 

Here are a few additional things I've tried to identify missing column names or unnamed elements:
```
> names(df)[names(df) == ""]
character(0)
> 
> names(df)[is.na(names(df))]
character(0)
>
> traceback()
6: stop("If any elements of `.data` are named, all must be named", 
       call. = FALSE)
5: validate_names(.data)
4: new_vctr(x, labels = labels, label = label, ..., class = c(class, 
       "haven_labelled"), inherit_base_type = TRUE)
3: new_labelled(x, labels = labels, label = label)
2: validate_labelled(new_labelled(x, labels = labels, label = label))
1: labelled(x = group_lookup[as.character(df$group)], labels = group_lookup, 
       label = "Study Group")
>
```

I would appreciate any ideas on how to troubleshoot this further. 

Thank you. 

André

I've also looked for help from the RStudio Community: [Using haven to label data for STATA: Error: If any elements of `.data` are named, all must be named](https://community.rstudio.com/t/using-haven-to-label-data-for-stata-error-if-any-elements-of-data-are-named-all-must-be-named/68411)

**Comment by drevanzyl** [comment]
It seems to be an issue in haven version 2.3.1.

This resolved the problem:

```
> remove.packages("haven")
Removing package from ‘C:/Users/andre/Documents/R/win-library/4.0’
(as ‘lib’ is unspecified)
> library(devtools)
Loading required package: usethis
> install_version("haven", version = "2.2.0", repos = "http://cran.us.r-project.org")
```

**Comment by hadley** [comment]
Can you please provide a minimal reprex (reproducible example)? The goal of a reprex is to make it as easy as possible for me to recreate your problem so that I can fix it: please [help me help you](https://nypdecider.files.wordpress.com/2014/08/help-me-help-you.gif)! 

If you've never heard of a reprex before, start by reading "[What is a reprex](http://reprex.tidyverse.org/articles/reprex.html)", and follow the advice further down the page. Please make sure your reprex is created with the reprex package as it gives nicely formatted output and avoids a number of common pitfalls.

**Comment by drevanzyl** [comment]
This works using haven 2.2.0:

``` r
library(tidyverse)
library(haven)
df <- data.frame(
          id = c(1, 2, 3, 4, 5, 6, 7, 8, 9, 10),
       group = c(1, NA, NA, 2, NA, 1, NA, NA, 1, 2),
         var = c(2, NA, NA, 4, NA, 5, NA, NA, 3, 5)
      ) %>% 
        mutate(group = as.factor(group))


group_lookup <- c("Group 2" = 2,
                  "Group 1" = 1)
df$group = factor(df$group, levels = group_lookup, labels = names(group_lookup))

df$group <-
        labelled(x  =  group_lookup[as.character(df$group)],
                 labels = group_lookup, label = "Group")

table(df$group)
#> 
#> 1 2 
#> 3 2
```

<sup>Created on 2020-06-03 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

If I use haven 2.3.1 using the same code then I get the following message: `Error: If any elements of `.data` are named, all must be named`

``` r
library(tidyverse)
library(haven)
df <- data.frame(
          id = c(1, 2, 3, 4, 5, 6, 7, 8, 9, 10),
       group = c(1, NA, NA, 2, NA, 1, NA, NA, 1, 2),
         var = c(2, NA, NA, 4, NA, 5, NA, NA, 3, 5)
      ) %>% 
        mutate(group = as.factor(group))


group_lookup <- c("Group 2" = 2,
                  "Group 1" = 1)
df$group = factor(df$group, levels = group_lookup, labels = names(group_lookup))

df$group <-
        labelled(x  =  group_lookup[as.character(df$group)],
                 labels = group_lookup, label = "Group")
#> Error: If any elements of `.data` are named, all must be named

table(df$group)
#> 
#> Group 2 Group 1 
#>       2       3
```

<sup>Created on 2020-06-03 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by hadley** [comment]
Here's a minimal reprex:

``` r
library(haven)
x <- c(1, 2, NA)
names(x) <- c("x", "y", NA)
labelled(x, c("Group 2" = 2, "Group 1" = 1))
#> Error: If any elements of `.data` are named, all must be named
```

<sup>Created on 2020-06-03 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

Related to https://github.com/r-lib/vctrs/issues/1108

**Comment by hadley** [comment]
If you need a work around in the meantime, you can just do `unname(group_lookup[as.character(df$group)])`

**Comment by drevanzyl** [comment]
> If you need a work around in the meantime, you can just do `unname(group_lookup[as.character(df$group)])`

Thanks. I'll rather use the old version of haven to save time. I'll have to apply your suggestion to around 702 variables and I'm not sure how to do that quickly.

**Comment by corneliushennch** [comment]
> If you need a work around in the meantime, you can just do `unname(group_lookup[as.character(df$group)])`

I just had exactly the same issue as @drevanzyl described. @hadley your work around worked perfectly for me using haven 2.3.1. Thank you!

**Comment by DavisVaughan** [comment]
Fixed by https://github.com/r-lib/vctrs/pull/784

``` r
library(haven)
x <- c(1, 2, NA)
names(x) <- c("x", "y", NA)
labelled(x, c("Group 2" = 2, "Group 1" = 1))
#> <labelled<double>[3]>
#>  x  y    
#>  1  2 NA 
#> 
#> Labels:
#>  value   label
#>      2 Group 2
#>      1 Group 1
```
