### ISSUE TITLE
Error in df_parse_sas_file with Dates

### ISSUE THREAD

**Issue by DanChaltiel** [tidyverse/haven#536]
I was working on a project when I had the brightest idea: updating my packages. I used RStudio "update" widget and picked my favorites: 

```r
install.packages("rlang")
install.packages(c("bookdown", "broom", "data.table", "DT", "emmeans", "expss", "flextable", "ggplot2", "glue", "haven", "lubridate", "officer", "purrr", "rlang", "rms", "roxygen2", "survival", "tibble", "usethis", "xml2"), lib="C:/Users/D_CHALTIEL/Documents/Program Files/R/R-3.6.1/library")
```

Unfortunately,  this led to a reading problem when using `haven::read_sas` on some tables:

> ```
> Error in df_parse_sas_file(spec_data, spec_cat, encoding = encoding, catalog_encoding = catalog_encoding,  : 
>   Evaluation error: Internal error: Corrupt `Date` with unknown type character..
> ```

This function uses `.Call` so I cannot dig into it to help to find the issue.

Of course, I have no idea which version of these packages I had before updating.

I tried reverting to previous versions and I had to reinstall version 0.2.1 (date 2016-07-19) for it to work again:

`remotes::install_version("haven", "0.2.1", upgrade="never")`

I'm sorry but I cannot share my dataset due to copyright policy so I cannot provide a reproducible example.

### EDIT:

Actually, reverting to v0.2.1 only delayed the error to the column evaluation time. Still, this allows me to identify the column that was the cause of the error. Here is its `dput`:

```r

mytable=haven::read_sas('mytable.sas7bdat')
dput(mytable[,19])
#> structure(list(myvar = structure(c("21424", "21487", "21480", 
#>                                       "21607", "21656", "21739", "21845", "21809", "21929", "21992", 
#>                                       "21997", "21987", "21585", "21662", "21662", "21584", "", "21662", 
#>                                       "21783", "21817", "21879", "21571", "", "21572"), 
#>                                     label = "Date", class = "Date")), 
#>           row.names = c(NA, -24L), class = c("tbl_df", "tbl", "data.frame"))
```

Simply running this `structure` call reproduces the error: `Internal error: Corrupt Date with unknown type character.`

**Comment by hadley** [comment]
If you can't provide a reprex, then unfortunately there's nothing I can do to help.

**Comment by DanChaltiel** [comment]
@hadley Actually, it seems to be a problem with `tibble` that bubbles up to `vctrs::date_validate()`:

``` r
structure(list(myvar = structure(c("21424", "21487"), label = "Date", class = "Date")), 
          row.names = c("1", "2"), class = c("tbl_df", "tbl", "data.frame"))
#>        myvar
#> 1 2028-08-28
#> 2 2028-10-30
structure(list(myvar = structure(c("21424", "21487"), label = "Date", class = "Date")), 
          row.names = c("1", "2"), class = c("data.frame"))
#>        myvar
#> 1 2028-08-28
#> 2 2028-10-30

library(tibble)

structure(list(myvar = structure(c("21424", "21487"), label = "Date", class = "Date")), 
          row.names = c("1", "2"), class = c("tbl_df", "tbl", "data.frame"))
#> Error: Internal error in `date_validate()`: Corrupt `Date` with unknown type character.
structure(list(myvar = structure(c("21424", "21487"), label = "Date", class = "Date")), 
          row.names = c("1", "2"), class = c("data.frame"))
#>        myvar
#> 1 2028-08-28
#> 2 2028-10-30
```

<sup>Created on 2021-04-08 by the [reprex package](https://reprex.tidyverse.org) (v1.0.0)</sup>

I will forward this last example to a more appropriate place.
