### ISSUE TITLE
as_factor() for haven_labelled_spss objects doesn't respect missingness (NA)

### ISSUE THREAD

**Issue by rpruim** [tidyverse/haven#539]
It looks like there is no `as_factor.haven_labelled_spss()` and `as_factor.haven_labelled()` doesn't process the NA values that can be attached to `"haven_labelled_spss"` objects.

``` r
suppressPackageStartupMessages(library(haven))

x <- labelled_spss(1:10, c(Good = 1, Bad = 8), na_values = 9:10) 
fx <- as_factor(x)
is.na(x)
#>  [1] FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE  TRUE  TRUE
is.na(fx)
#>  [1] FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE
fx
#>  [1] Good 2    3    4    5    6    7    Bad  9    10  
#> Levels: Good 2 3 4 5 6 7 Bad 9 10
```

<sup>Created on 2020-08-05 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by rpruim** [comment]
Adding something along these lines to `as_factor.haven_labelled()` seems like it would do the trick:

```r
  na_values <- attr(x, "na_values")                  #<<
  na_range <- attr(x, "na_range") %||% c(Inf, -Inf)  #<<
 
  x <- vec_data(x)                                   #<<
  x[x %in% na_values] <- NA                          #<<
  x[x >= na_range[1] & x <= na_range[2]] <- NA       #<<
```

Inserting the above after `labels <- attr(x, "labels")` handles some basic test cases:

```r
x0 <- labelled_spss(1:10, labels = c(Good = 1, Bad = 8))
## 
x1 <- labelled_spss(1:10, labels = c(Good = 1, Bad = 8), na_values = c(9, 10))
## 
x2 <- labelled_spss(1:10, labels = c(Good = 1, Bad = 10), na_range = c(5, 8))
## 
as_factor(x0)
##  [1] Good 2    3    4    5    6    7    Bad  9    10  
## Levels: Good 2 3 4 5 6 7 Bad 9 10
## 
as_factor(x1)
##  [1] Good 2    3    4    5    6    7    Bad  <NA> <NA>
## Levels: Good 2 3 4 5 6 7 Bad
## 
as_factor(x2)
##  [1] Good 2    3    4    <NA> <NA> <NA> <NA> 9    Bad 
## Levels: Good 2 3 4 9 Bad
```

**Comment by rpruim** [comment]
I've just been reading the documentation for `{labelled}`, especially the `to_factor()` function.  That package provides many ways to handle user-defined NA values.

Perhaps it would be good enough to emit a warning if there are user-defined NAs that occur in the data indicating that they have *not* been converted to NAs.  Could even suggest using `labelled::to_factor()` for converting labelled vectors to factors.

At a minimum, it would be worth documenting that `as_factor()` doesn't handle user-defined NAs, since users might be expecting that it would.

**Comment by hadley** [comment]
@rpruim want to do a PR?

**Comment by rpruim** [comment]
@hadley: Possibly.  Two questions.

1. What is the timeline for getting this done?
2. What solution are we looking to implement?

Regarding #2: I'm not an SPSS user, and I've used relatively little data that arrived in SPSS format, so I'd want to make sure I'm using a reasonable approach.   It's been a while since I was thinking about this, and I'll have to reread the {labelled} documentation.  But are we looking for a solution like the one I outlined above or something else?

a. It seems like converting all of the things identified by `na_values` or `na_range` into NA makes sense (even though it is lossy).  Is there a reason not to do this?  Should it be a user option of some sort?

b. The SPSS labels are a little trickier.  If their primary use is for display (in tables and plots), they might not be very handy to program with.

  * Should there be an option for whether to use the original levels or convert to the SPSS labels?
  * Should information about the levels/labels be stored in an attribute, or should the conversion be lossy?
  
I may need to consult with my local SPSS users and look at how things are currently done for `haven_labelled`.

**Comment by hadley** [comment]
I think it needs to be done in ~24 hours in order to get into the next haven release, but I think there are sufficient questions to make that unlikely/impossible.

One possible principle to guide this work would be to ensure that `read_spss("foo.sav")$x` is the same as `as_factor(read_spss("foo.sav", user_na = TRUE)$x)`. This is basically giving you the ability to convert `labelled_spss()` to a factor after reading it.

Even given that, it's still not clear to me that you'd want this behaviour by default, since by converting multiple values to `NA` you are losing data that a factor could use. So maybe it should be a separate function?

**Comment by larmarange** [comment]
> a. It seems like converting all of the things identified by `na_values` or `na_range` into NA makes sense (even though it is lossy). Is there a reason not to do this? Should it be a user option of some sort?

When you import survey data from SPSS, multiple missing values are often used to store different types of missingness, i.e. to separate "refusals", "don't know", "filtered", and "missing on paper form". 

As a social scientist, it could be important to distinguish these different types of missingness. In that case, I will use `read_spss(user = TRUE)` to keep the information and later on, on a case by case, depending of my research question, the type of analysis, the level of missingness, the variable, I will decide de keep the information (explicit levels) or to convert them to regular `NA`s.

For example, when analyzing sensitive data such as sexual behavior, it is very important (and informative) to clearly distinguish people who refused to answer and people who didn't know how to answer.

Therefore, it is important to offer the choice to users and to have an option in `as_factor()`.

In `labelled::to_factor()` you have an option `user_na_to_na` to indicate if user na should be transformed in regular factor levels or be transformed into `NA`. 

Regarding **default behavior**, I would argue that it is better to not convert by default to NAs. In such case, if you want to convert to NA and forgot to add the option, it will be clearly visible in your results and you will correct your code. While if by default user na are converted into NAs, it would be "invisible".

In addition, if the user has explicitly specified `user_na = TRUE` in `read_spss()`, he implicitly expressed that he needs/wants to keep the details and therefore converting user_na to `NA` should be an explicit request.

**Comment by hadley** [comment]
Oh, we already have a function that does this: `zap_missing()`. So maybe all we need is to document this in `as_factor()`

**Comment by rpruim** [comment]
That sounds promising.  I'm not sure your 24-hour time frame will work with my schedule, unfortunately.  Is there someone else who can get to it today?

**Comment by hadley** [comment]
Yeah, me 😄

**Comment by rpruim** [comment]
Sorry about that.  I'd be happy to help, but I need to grade a stack of exams first.  Given the choice, I'd prefer to write R code...
