### ISSUE TITLE
create data dictionary

### ISSUE THREAD

**Issue by shannonpileggi** [tidyverse/haven#540]
A feature that would be nice to include in haven is the ability to create a data dictionary, from either labelled or unlabelled data. sjPlot::view_df performs the function that I am seeking, except returns the result as a formatted html table.  It would be useful to have the result returned as a data frame in R, that is easily searchable.  Below is some rough example code that I started to achieve this objective – I’m sure that someone on your team could make it much more efficient!

``` r
library(reprex)
library(tidyverse)
library(haven)
library(sjlabelled)
#> 
#> Attaching package: 'sjlabelled'
#> The following objects are masked from 'package:haven':
#> 
#>     as_factor, read_sas, read_spss, read_stata, write_sas, zap_labels
#> The following object is masked from 'package:forcats':
#> 
#>     as_factor
#> The following object is masked from 'package:dplyr':
#> 
#>     as_label
library(sjPlot)
#> Learn more about sjPlot with 'browseVignettes("sjPlot")'.
```

Convert list to data frame

@param var\_list A list of variables in sections to convert to a long data frame.
Note that list elements must be of same type (e.g., character).

@param name1 quoted name of first list element, defaults to section

@param name2 quoted name of second list element, defaults to variable

@return A tibble.
@export

@examples

``` r
list_to_df <- function(var_list, name1 = "section", name2 = "variable"){
  purrr::map2_df(names(var_list),
                 var_list,
                 ~ tibble::tibble(!!name1 := .x, !!name2 := .y))
}
```

Convert list to a look-up table

@param var\_list A list of variables in sections to convert to a look-up table as
elements separated by columns.

@return A tibble.
@export

@examples

``` r
list_to_lookup <- function(var_list, name1 = "section", name2 = "variable"){
  purrr::map2_df(
    names(var_list),
    var_list,
    ~ tibble::tibble(!!name1 := .x, !!name2 := paste(.y, collapse = ", "))
  )
}
```

Create a data dictionary for SPSS data sets

@param data the SPSS labelled data frame imported by haven::read\_sav
@param form the return format can either be “wide” (default, 1 row per variable) or “long” (1 row per variable and value code)

@return a tibble with variable name, variable label, variable class, and value codes
@export

@examples

``` r
create_data_dictionary <- function(data, form = "wide"){
  
  # fetch variable class ----
  var_class <- purrr::map(data, class) %>% 
    purrr::map(., 1) %>% 
    tibble::enframe(name = "variable_name", value = "variable_class") %>% 
    tibble::rowid_to_column(var = "variable_id") %>% 
    tidyr::unnest(variable_class)
  
  # number of factors ----
  num_factor <- sum(var_class[["variable_class"]] == "factor")
  
  # number of haven labelled ----
  num_haven  <- sum(var_class[["variable_class"]] == "haven_labelled")
  
  
  if(num_haven == 0) {
    code_values_labelled <- NULL
    code_labels_labelled <- NULL
  } else {
    # fetch variable labels ----
    var_labels <- data %>% 
      sjlabelled:::get_label() %>% 
      tibble::enframe(name = "variable_name", value = "variable_label") %>% 
      tibble::rowid_to_column(var = "variable_id")
    
    # fetch value codes from haven labelled ----
    code_values_labelled <- data %>% 
      dplyr::select_if(haven::is.labelled) %>%
      purrr::map(.f = sjlabelled::get_values) %>% 
      purrr::map(as.character) %>% 
      list_to_df(name1 = "variable_name", name2 = "value_code") %>% 
      dplyr::group_by(variable_name) %>% 
      dplyr::mutate(value_id = dplyr::row_number()) %>% 
      dplyr::ungroup()
    
    # fetch value labels from haven labelled ----
    code_labels_labelled <- data %>% 
      dplyr::select_if(haven::is.labelled) %>% 
      purrr::map(.f = sjlabelled::get_labels) %>% 
      list_to_df(name1 = "variable_name", name2 = "value_label")  %>% 
      dplyr::group_by(variable_name) %>% 
      dplyr::mutate(value_id = dplyr::row_number()) %>% 
      dplyr::ungroup()
  }
  
  if(num_factor == 0) {
    code_factor <- NULL
  } else {
    # fetch value levels from factor ----
    code_factor <- data %>% 
      dplyr::select_if(is.factor) %>%
      purrr::map(.f = levels) %>% 
      list_to_df(name1 = "variable_name", name2 = "value_label") %>% 
      dplyr::group_by(variable_name) %>% 
      dplyr::mutate(
        value_id = dplyr::row_number(), 
        value_code = as.character(value_id)
      ) %>% 
      dplyr::ungroup()
  }
  
  # stack labels and values from haven labelled and factors ----
  if(num_haven == 0 & num_factor == 0){
    code_labels <- NULL
    code_values <- NULL
  } else if (num_haven > 0 & num_factor == 0) {
    code_labels <- code_labels_labelled
    code_values <- code_values_labelled
  } else if (num_haven == 0 & num_factor > 0) {
    code_labels <- code_factor %>% dplyr::select(variable_name, value_label, value_id)
    code_values <- code_factor %>% dplyr::select(variable_name, value_code, value_id)
  } else if (num_haven > 0 & num_factor > 0) {
    code_labels <- dplyr::bind_rows(code_labels_labelled, code_factor %>% dplyr::select(variable_name, value_label, value_id))
    code_values <- dplyr::bind_rows(code_values_labelled, code_factor %>% dplyr::select(variable_name, value_code, value_id))
  }
  
  # if either haven labelled or factors are present, assemble dictionary with value and
  # label look ups ----
  if (num_haven > 0 | num_factor > 0) {
    # assemble into long data frame with 1 row per code ----
    variable_view_long <- var_labels %>% 
      dplyr::left_join(var_class, by = c("variable_name", "variable_id")) %>%
      dplyr::left_join(code_values, by = c("variable_name")) %>% 
      dplyr::left_join(code_labels, by = c("variable_name", "value_id")) %>% 
      dplyr::mutate(
        value_string = case_when(
          is.na(value_id) ~ NA_character_,
          variable_class == "factor" ~ as.character(glue::glue('{value_label}')),
          variable_class == "haven_labelled" ~ as.character(glue::glue('{value_code} = {value_label}'))
        )
      ) %>% 
      dplyr::select(variable_id, variable_name, variable_label, variable_class, value_id, value_code, value_label, value_string) 
    
    # create look up of values for wide data frame ----
    value_lookup <- variable_view_long %>%
      tidyr::drop_na(value_id) %>% 
      dplyr::select(variable_name, value_string) %>% 
      split(., f = .$variable_name) %>%
      purrr::map(., 2) %>% 
      list_to_lookup(name1 = "variable_name", name2 = "value_codes")
    
    # assemble into wide data frame with 1 row per variable ----
    variable_view_wide <- variable_view_long %>% 
      dplyr::select(variable_id, variable_name, variable_label, variable_class) %>%
      dplyr::distinct() %>% 
      dplyr::left_join(value_lookup, by = "variable_name")
  }
  
  # if neither haven labelled nor factors are present, assemble dictionary with just class
  if (num_haven == 0 & num_factor == 0) {
    return_view <- var_class 
  } else {
    if (form == "long") return_view <- variable_view_long
    if (form == "wide") return_view <- variable_view_wide
  }
  
  return(return_view)
  
}

# Create example data with a mix of data types ----
ex_data <- tibble(
  id = 1:10,
  ctry = c(rep(1, 5), rep(2, 5)),
  cdy = rep(c(1, 3), 5),
  text = LETTERS[1:10]
  ) %>% 
  mutate(
    ctry = factor(ctry, labels = c("US", "UK")),
    cdy = haven::labelled(
      cdy, 
      labels = c("MMs" = 1, "Skittles" = 3), 
      label = "Preferred Candy")
  )

# Demonstrate dictionary on example data ----
sjPlot::view_df(ex_data)
```

<table style="border-collapse:collapse; border:none;">

<caption>

Data frame: ex\_data

</caption>

<tr>

<th style="border-bottom:double; font-style:italic; font-weight:normal; padding:0.2cm; text-align:left; vertical-align:top;">

ID

</th>

<th style="border-bottom:double; font-style:italic; font-weight:normal; padding:0.2cm; text-align:left; vertical-align:top;">

Name

</th>

<th style="border-bottom:double; font-style:italic; font-weight:normal; padding:0.2cm; text-align:left; vertical-align:top;">

Label

</th>

<th style="border-bottom:double; font-style:italic; font-weight:normal; padding:0.2cm; text-align:left; vertical-align:top;">

Values

</th>

<th style="border-bottom:double; font-style:italic; font-weight:normal; padding:0.2cm; text-align:left; vertical-align:top;">

Value Labels

</th>

</tr>

<tr>

<td style="padding:0.2cm; text-align:left; vertical-align:top;">

1

</td>

<td style="padding:0.2cm; text-align:left; vertical-align:top;">

id

</td>

<td style="padding:0.2cm; text-align:left; vertical-align:top;">

</td>

<td style="padding:0.2cm; text-align:left; vertical-align:top;" colspan="2">

<em>range: 1-10</em>

</td>

</tr>

<tr>

<td style="padding:0.2cm; text-align:left; vertical-align:top; background-color:#eeeeee">

2

</td>

<td style="padding:0.2cm; text-align:left; vertical-align:top; background-color:#eeeeee">

ctry

</td>

<td style="padding:0.2cm; text-align:left; vertical-align:top; background-color:#eeeeee">

</td>

<td style="padding:0.2cm; text-align:left; vertical-align:top; background-color:#eeeeee">

</td>

<td style="padding:0.2cm; text-align:left; vertical-align:top; background-color:#eeeeee">

US<br>UK

</td>

</tr>

<tr>

<td style="padding:0.2cm; text-align:left; vertical-align:top;">

3

</td>

<td style="padding:0.2cm; text-align:left; vertical-align:top;">

cdy

</td>

<td style="padding:0.2cm; text-align:left; vertical-align:top;">

Preferred Candy

</td>

<td style="padding:0.2cm; text-align:left; vertical-align:top;">

1<br>3

</td>

<td style="padding:0.2cm; text-align:left; vertical-align:top;">

MMs<br>Skittles

</td>

</tr>

<tr>

<td style="padding:0.2cm; text-align:left; vertical-align:top; background-color:#eeeeee">

4

</td>

<td style="padding:0.2cm; text-align:left; vertical-align:top; background-color:#eeeeee">

text

</td>

<td style="padding:0.2cm; text-align:left; vertical-align:top; background-color:#eeeeee">

</td>

<td style="padding:0.2cm; text-align:left; vertical-align:top; background-color:#eeeeee">

</td>

<td style="padding:0.2cm; text-align:left; vertical-align:top; background-color:#eeeeee">

\<output omitted\>

</td>

</tr>

</table>

``` r
create_data_dictionary(ex_data)
#> # A tibble: 4 x 5
#>   variable_id variable_name variable_label    variable_class value_codes        
#>         <int> <chr>         <chr>             <chr>          <chr>              
#> 1           1 id            ""                integer        <NA>               
#> 2           2 ctry          ""                factor         US, UK             
#> 3           3 cdy           "Preferred Candy" haven_labelled 1 = MMs, 3 = Skitt~
#> 4           4 text          ""                character      <NA>
create_data_dictionary(ex_data, form = "long")
#> # A tibble: 6 x 8
#>   variable_id variable_name variable_label variable_class value_id value_code
#>         <int> <chr>         <chr>          <chr>             <int> <chr>     
#> 1           1 id            ""             integer              NA <NA>      
#> 2           2 ctry          ""             factor                1 1         
#> 3           2 ctry          ""             factor                2 2         
#> 4           3 cdy           "Preferred Ca~ haven_labelled        1 1         
#> 5           3 cdy           "Preferred Ca~ haven_labelled        2 3         
#> 6           4 text          ""             character            NA <NA>      
#> # ... with 2 more variables: value_label <chr>, value_string <chr>
```

<sup>Created on 2020-08-10 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by larmarange** [comment]
Did you have a look at `labelled::look_for()` function with `details = TRUE`?

Most of the features you mentioned seem already implemented.

**Comment by shannonpileggi** [comment]
Thanks for pointing this out!   However, an inherent limitation in this approach is that you assume the user knows what they are actually looking for.  If the user does not know exactly what they are looking for, then having a full dictionary as a data frame for reference that is both scannable and searchable is a huge help (I regularly work with .sav data files in R with 3000+ variables, and I have to find what I need).

**Comment by larmarange** [comment]
`look_for()` could be applied on a full data frame without any query. In that case, it will return all variables.

**Comment by shannonpileggi** [comment]
Ah ok, that functionality was not immediately apparent to me!  Yes, then the two approaches produce very similar output.  Example shown below for CDC's YRBSS data.  

The ability to switch between wide and long quickly still may be a useful feature (think when you have a variable for state with 50+ codes). And there is already some overlap in efforts between haven, sjlabelled, and labelled, but I think there is a place for a function like this in haven.  Your call of course  :)

Using my function:
![image](https://user-images.githubusercontent.com/17747575/89789901-38034a00-daef-11ea-982e-abc7f8718c18.png)

Using labelled::look_for:
![image](https://user-images.githubusercontent.com/17747575/89790010-55d0af00-daef-11ea-96a9-7646e5032d5a.png)

**Comment by larmarange** [comment]
Regarding `labelled::look_for()` I will look at improving how results are printed and to add an option for presenting results in a long format.

Regarding the relevance of such a feature in `haven`, it's up to haven developers to say if it is in haven's scope or not.

**Comment by hadley** [comment]
This is definitely out of scope for haven 😄
