### ISSUE TITLE
Huge difference in file size CSV vs DTA

### ISSUE THREAD

**Issue by elfatherbrown** [tidyverse/haven#541]
Hi. Im clearly a newbie with working with dta files, but I noticed a huge difference in size when writing a 2 million row dataframe in CSV with, say, vroom and the exact same dataframe with haven::write_dta. 

In CSV my file is 2.7GB with no compression. The resulting haven::write_dta that goes up to 8GB!

Is this normal? Should I be doing something to my dataframe's content before using write_dta?

**Comment by evanmiller** [comment]
The DTA file format is fixed-width, which means that if you have a column containing "A", "AA", and "AAAAAAAA", all three values will take up the same amount of space (eight bytes). Haven calculates each column's width by taking the maximum length of all of its row values. If your data is variable-width, there can be a large amount of inflation compared to CSV.

The file would be smaller if Haven supported the strL data type (see #437), but this is not implemented.
