### ISSUE TITLE
File has an unsupported character set when reading SAS file

### ISSUE THREAD

**Issue by hhchang0210** [tidyverse/haven#545]
Please briefly describe your problem and what output you expect. If you have a question, please don't use this form. Instead, ask on <https://stackoverflow.com/> or <https://community.rstudio.com/>.

Please include a minimal reproducible example (AKA a reprex). If you've never heard of a [reprex](http://reprex.tidyverse.org/) before, start by reading <https://www.tidyverse.org/help/#reprex>.

Brief description of the problem

```r
library(haven)
a<- read_sas("D:/h_nhi_opdte10302_30.sas7bdat")
#> Unsupported character set code: 118
#> Error in df_parse_sas_file(spec_data, spec_cat, encoding = encoding, catalog_encoding = catalog_encoding, : Failed to parse D:/h_nhi_opdte10302_30.sas7bdat: File has an unsupported character set.
```

**Comment by hhchang0210** [comment]
Hi,
I put the reprex result above. Hope it will help.

**Comment by hadley** [comment]
That's not a very useful reprex because we don't have your D drive.

**Comment by hadley** [comment]
Here's a real reprex:

``` r
path <- tempfile() 
download.file("https://github.com/tidyverse/haven/files/5202464/h_nhi_opdte10302_30.zip", path)
haven::read_sas(path)
#> Error in df_parse_sas_file(spec_data, spec_cat, encoding = encoding, catalog_encoding = catalog_encoding, : Failed to parse /private/tmp/RtmpcwZIHi/filed99a6ec8db65: Invalid file, or file has unsupported features.
```

<sup>Created on 2020-09-10 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0.9001)</sup>

**Comment by hadley** [comment]
And this appears to be fixed in the dev version.

**Comment by hhchang0210** [comment]
Thank you a lot. It solved the problem. Sorry not familiar with reprex.
