### ISSUE TITLE
Feature request: Endlabelled into numeric variable

### ISSUE THREAD

**Issue by BernhardClemm** [tidyverse/haven#549]
As far as I can see, this is not part of the `haven` package yet, so I would like to suggest a new feature:

People working with survey data will often encounter variables that are meant to be numeric, but come in factor or character format because of end-labelled scales in questionnaires. Imagine a question "Do you agree that...?" with a response scale with options "1 - do not agree at all", "2", "3", "4", "5 - Completely agree". A common way to recode this into a numeric variable might be:

```r
data <- data %>%
  mutate(var_num = case_when(var == "1 - do not agree at all" ~ 1,
                                                   var == "2" ~ 2,
                                                   var == "3" ~ 3,
                                                   var == "4" ~ 3,
                                                   var == ""5 - Completely agree" ~ 5))
```
This gets tiresome if the numeric information is always contained in the levels. I wrote a short function that just takes the first (or last, depending of the specification) number and turns into a numeric value (I am sure this function can be improved!):

```
endlabelled.as.numeric <- function(col, which_number = "first") {
  if (which_number == "first") {
    vector <- as.numeric(str_extract(col, "[0-9]+"))
  } else if (which_number == "last") {
    vector_list <- sapply(str_extract_all(col, "[0-9]+"), tail, 1)
    vector <- as.numeric(as.character(vector_list))
  }
  return(vector)
}
```
This would simplify my problem as follows:
```
data <- data %>%
  mutate(var_num = endlabelled.as.numeric(var))
```

**Comment by hadley** [comment]
Thanks for filing this issue! Unfortunately, I don't think it's a good fit for this package:  developing good software requires relentless focus, which means that we have to say no to many good ideas. Even though I'm closing this issue, I really appreciate the feedback, and hope you'll continue to contribute in the future 😄

**Comment by BernhardClemm** [comment]
Thanks for your feedback – I understand. Do you know of any package that might be a good fit (and is open to pull requests)?
