### ISSUE TITLE
How do I convert a double to a factor?

### ISSUE THREAD

**Issue by kambanane** [tidyverse/haven#552]
This is probably a very simple question, but how do I convert a haven_labelled double variable to a haven_labelled factor?

**Comment by larmarange** [comment]
to convert a haven_labelled double vector into a factor (there is no "haven_labelled factor"), you can use `haven::as_factor()`, cf https://haven.tidyverse.org/reference/as_factor.html  or `labelled::to_factor()` cf https://larmarange.github.io/labelled/reference/to_factor.html

**Comment by batpigandme** [comment]
I'm gonna close this issue, since it seems like @larmarange has covered it!
