### ISSUE TITLE
write_* quietly changes datetime to UTC

### ISSUE THREAD

**Issue by atungate** [tidyverse/haven#555]
I noticed that haven exports datetimes as UTC regardless of timezone (which I do not think needs to change). However, I think it helpful for the UTC conversion to be explicit. E.g., with either a message in R if there is a non-UTC datetime, or a note in the documentation. Small issue, but some haven users may not realize they are exporting their datetime as UTC. 

Exemplified here: 
```
library(haven)
library(tibble)

test = tibble(date = as.Date("1999-12-31 22:00"),
              time = readr::parse_time("22:00"),
              date_time_edt = as.POSIXct("1999-12-31 22:00 EST"), # haven quietly coerces to UTC for date-time
              date_time_utc = as.POSIXct("1999-12-31 22:00", tz = "UTC"))

# SPSS 
spss_tmpfile = tempfile(fileext = ".sav")
write_sav(test, spss_tmpfile)[]
read_sav(spss_tmpfile)

# SAS 
sas_tmpfile = tempfile(fileext = ".sas7bdat")
write_sas(test, sas_tmpfile)[]
read_sas(sas_tmpfile)

# STATA 
stata_tmpfile = tempfile(fileext = ".dta")
write_dta(test, stata_tmpfile)[]
read_dta(stata_tmpfile) # side-note, check "time" column on import. you may be aware but I don't use stata, so I am not sure

# Cleanup
ls(pattern = "_tmpfile") # just to make sure I don't remove anything unintended from your env
file.remove(unlist(mget(ls(pattern = "_tmpfile"))))
rm(list = ls(pattern = "_tmpfile"))
```

Related:
https://github.com/tidyverse/haven/issues/25

**Comment by hadley** [comment]
I am (a) unsure about where to document this and (b) unsure if the current behaviour is correct. I don't think the other packages have a notion of time zone, so it seems likely that we convert the date that the user sees, not the date you'd see if the timezone was set to UTC.

**Comment by hadley** [comment]
If we wanted to write dates as the user sees them in R, we can use something like this:

``` r
epoch <- function(x) {
  as.numeric(x) - as.numeric(as.POSIXct("1970-01-01", tz = attr(x, "tzone")))
}

x <- as.POSIXct("1970-01-01 15:00", tz = "America/Chicago")
epoch(x)
#> [1] 54000
x <- as.POSIXct("1970-01-01 15:00", tz = "Pacific/Auckland")
epoch(x)
#> [1] 54000
```

<sup>Created on 2021-04-09 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

**Comment by atungate** [comment]
Just saw the update--great solution. Thanks for all your work to improve haven!
