### ISSUE TITLE
Error from connection stream but not from direct file

### ISSUE THREAD

**Issue by gowerc** [tidyverse/haven#563]
I am getting an error message when trying to read in a sas7bdat file as a binary string however I don't get an error message when reading it in directly from the file system:

![image](https://user-images.githubusercontent.com/8447209/104060662-2386c300-51ef-11eb-8788-51a68385e67d.png)

Unfortunately it is a corporate dataset so I can't share it :( 

This is causing issues as we are pulling binary data over an internal API into memory but then as a result of this bug are now having to write it to disk before we can parse it which obviously causes an unnecessary computation overhead

**Comment by hadley** [comment]
Unfortunately there's not much I can do without a reprex.
