### ISSUE TITLE
special character encoding problem when using write_sav

### ISSUE THREAD

**Issue by toerpe** [tidyverse/haven#567]
I try to read and write sav files using haven's read_sav and write sav functions (and also sjlabelled's read_spss and write_spss).

I encountered a problem when I write a .sav file and try to read it back to R.
The problem occurs, when I have a special (Hungarian) character in as the 8th character of the variable name.

A small example:
```r
df1 <- data.frame(aaaaaaaáaa = sample(c("egy", "kettő"), 10, replace = TRUE))
write_sav(df1, "df1.sav")
df2 <- read_sav("df1.sav")
```
And the error message:
Error parsing string "AAAAAAAĂ=aaaaaaaĂˇaa" around byte #8/20, character =
Error in df_parse_sav_file(spec, encoding, user_na, cols_skip, n_max,  : 
  Failed to parse C:/Google Drive/MUNKA/AKOS/df1.sav: Invalid file, or file has unsupported features.

When the special character is in a different position the code shown above seems to work fine.
read_sav also works fine when I create the .sav file in SPSS, but once I write it with write_sav I cannot read it back.

Thank you for your help in advance.

**Comment by hadley** [comment]
Looks like this is fixed in the dev version, thanks to a newer version of ReadStat:

``` r
library(haven)

df1 <- data.frame(aaaaaaaáaa = sample(c("egy", "kettő"), 10, replace = TRUE))
write_sav(df1, "df1.sav")
df2 <- read_sav("df1.sav")
df2
#> # A tibble: 10 x 1
#>    aaaaaaaáaa
#>    <chr>     
#>  1 egy       
#>  2 egy       
#>  3 egy       
#>  4 egy       
#>  5 kettő     
#>  6 egy       
#>  7 kettő     
#>  8 egy       
#>  9 kettő     
#> 10 kettő
```

<sup>Created on 2021-04-08 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>
