### ISSUE TITLE
Unable to Allocate Memory 

### ISSUE THREAD

**Issue by kwainfan** [tidyverse/haven#568]
Please briefly describe your problem and what output you expect. If you have a question, please don't use this form. Instead, ask on <https://stackoverflow.com/> or <https://community.rstudio.com/>.

Please include a minimal reproducible example (AKA a reprex). If you've never heard of a [reprex](https://reprex.tidyverse.org/) before, start by reading <https://www.tidyverse.org/help/#reprex>.

---

Trying to load a large Stata file into R and I get the following error: 
Error in df_parse_dta_file(spec, encoding, cols_skip, n_max, skip, name_repair = .name_repair) : 
  Failed to parse A:/~: Unable to allocate memory.

R version: 4.0.3
RStudio: 1.4.1103
Haven 2.3.1

```r
# insert reprex here
```

**Comment by hadley** [comment]
Sorry, not much I can do to help here.
