### ISSUE TITLE
Compress .dta files

### ISSUE THREAD

**Issue by jackobailey** [tidyverse/haven#569]
Stata contains an in-built command `compress` that can dramatically decrease file sizes. It converts labelled vectors [from long to byte type](https://www.stata.com/manuals13/ddatatypes.pdf). The readstata13 package's `save.dta13` function can provide such compression, but doesn't play well with labelled vectors. At present, the file sizes that write_dta produces are much larger then they need to be.

Any chance you could provide support for compression in write_dta at some point?

**Comment by hadley** [comment]
ReadStat doesn't currently support compression for `.dta` files, so the answer is no, sorry.
