### ISSUE TITLE
tagged NA missing values not (correctly) formatted

### ISSUE THREAD

**Issue by dusadrian** [tidyverse/haven#572]
This one should be very easy to fix, this is a reprex:

```r
library(haven)
library(labelled)
tags <- tagged_na('a', 'b')
values <- c(3, 1, -9, tags[1], 2, 4, tags[2], 5)
labels <- c(Good = 1, Bad = 5, Refuse = -9, DK = tags[1], NR = tags[2])
x <- labelled(values, labels = labels)
na_values(x)  <- c(-9, tags)

x
# <labelled_spss<double>[8]>
# [1]     3     1    -9 NA(a)     2     4 NA(b)     5
# Missing values: -9, NA, NA

# Labels:
#  value  label
#      1   Good
#      5    Bad
#     -9 Refuse
#  NA(a)     DK
#  NA(b)     NR
```

The final part of the output is correctly formatted since it uses the function `print_values()` which further uses the `print.haven_labelled()` to print an object of class `haven_labelled`.

But the "Missing values" part is not formatted, and I believe it would be much more clear to see something like:
```r
x
# <labelled_spss<double>[8]>
# [1]     3     1    -9 NA(a)     2     4 NA(b)     5
# Missing values: -9, NA(a), NA(b)

# Labels:
#  value  label
#      1   Good
#      5    Bad
#     -9 Refuse
#  NA(a)     DK
#  NA(b)     NR
```

**Comment by hadley** [comment]
Code is in `obj_print_footer.haven_labelled_spss()`

**Comment by dusadrian** [comment]
Yes indeed, one possible fix:

```r
obj_print_footer.haven_labelled_spss <- function(x, ...) {
  na_values <- attr(x, "na_values")
  na_values[is_tagged_na(na_values)] <- paste0("NA(", sort(na_tag(na_values[is_tagged_na(na_values)])), ")")
  if (!is.null(na_values)) {
    cat_line("Missing values: ", paste(na_values, collapse = ", "))
  }

  na_range <- attr(x, "na_range")
  if (!is.null(na_range)) {
    cat_line("Missing range:  [", paste(na_range, collapse = ", "), "]")
  }

  NextMethod()
}
```

**Comment by hadley** [comment]
@dusadrian do you want to do a PR?

**Comment by dusadrian** [comment]
I would love to contribute of course.

However there is a related issue #574 where @larmarange proposes to not even allow tagged NA values in labelled_spss vectors (that makes sense too, if so decided).

For the moment, the proposed fix correctly displays the values and in the future it will not do any harm.

**Comment by hadley** [comment]
Are you allowed to label tagged NAs in SPSS or Stata?

**Comment by dusadrian** [comment]
That is the philosophical discussion in larmarange/labelled#93

Yes, missing values can carry labels in both SPSS and Stata. But while SPSS has to "declare" which of the real numbers is to be treated as missing (with or without labels), Stata simply uses tagged NAs (no need for further declarations, the same with or without labels).

What @larmarange says is that once a value is **set** to a tagged NA, it is not necessary to declare it because it is obviously a missing value (treated as an NA anyways).

Hence my initial confusion, and I assume many others' too. To completely differentiate `haven_labelled` from `haven_labelled_spss` class objects, @larmarange proposes this:

```r
library(haven)
library(labelled)
values <- c(3, 1, -9, 2, 4, -8, 5)
labels <- c(Good = 1, Bad = 5, DK = -8, NR = -9)
x <- labelled(values, labels = labels)
na_values(x)  <- c(-8, -9)
```

This is a "pure" SPSS type object, no tagged NA values. It could have been created directly with `labelled_spss()` and the `na_values` argument, but since there is a function `na_values()` in package `labelled`, I used it as a "declaration" of missing values.


```r
tags <- tagged_na('a', 'b')
values <- c(3, 1, tags[1], 2, 4, tags[2], 5)
labels <- c(Good = 1, Bad = 5, DK = tags[1], NR = tags[2])
x <- labelled(values, labels = labels)
```

Here, it does not make sense and it really is unnecessary to further "declare" missing values: they are obviously missing, and even carry a label, everything is alright.


``` r
tags <- tagged_na('a', 'b')
values <- c(3, 1, -9, tags[1], 2, 4, tags[2], 5)
labels <- c(Good = 1, Bad = 5, Refuse = -9, DK = tags[1], NR = tags[2])
x <- labelled(values, labels = labels)
na_values(x)  <- c(-9, tags)

# or the same with
x <- labelled_spss(values, labels = labels, na_values= c(-9, tags))
```

This is the confusing part which should not work anymore, because it mixes SPSS style and Stata style missing values in the same object, yet treat it as if it was SPSS alone (because it adds the `haven_labelled_spss` class). The function `na_values()` from package `labelled` automatically adds the class `haven_labelled_spss` to an object, even if the object was not created using `labelled()` not `labelled_spss()` (such as the example above).

If the function `na_values()` would be restricted to objects of class `haven_labelled_spss`, the distinction would be clear and no more misunderstandings would arise. But the same would have to hold with `labelled_spss()`, it should only accept real numbers and not tagged NA values.

If this would be a formal decision, the fix from `obj_print_footer.haven_labelled_spss` would not be necessary of course.

**Comment by hadley** [comment]
Ok, in that case I think it would be better to clarify that you shouldn't mix Stata/SAS and SPSS style missings.
