### ISSUE TITLE
Should `labelled_spss()` have more checks?

### ISSUE THREAD

**Issue by larmarange** [tidyverse/haven#574]
Maybe it could be relevant to add more checks in `labelled_spss()`:

- regular NAs / tagged NAs should not be allowed in `na_values`
- regular NAs / tagged NAs should not be allowed in `na_range`
- in `na_range` the first value should be less or equal to the second value

**Comment by dusadrian** [comment]
@hadley  and @larmarange, with the recent commit this issue has been closed and now there is a clear distinction between the `haven_labelled` and `haven_labelled_spss` objects, which is great.

But just to show that it is actually possible to mix SPSS and Stata missing codes, and get away without needing `user_na_to_na()`, I took the liberty of forking and hacking packages `haven` and `vctrs`:

``` r
devtools::install_github("dusadrian/haven")
devtools::install_github("dusadrian/vctrs")
library(haven)

x <- labelled_spss(c(1:5, 99, tagged_na('a')),
                   labels = c("Don't know" = 99, "Refuse" = tagged_na('a')),
                   na_values = 99)
x
# <labelled<double>[7]>
# [1]     1     2     3     4     5    99 NA(a)
# Missing values: 99

# Labels:
#  value      label
#     99 Don't know
#  NA(a)     Refuse

mean(x)
# [1] NA

mean(x, na.rm = TRUE)
# [1] 3

is.na(x)
# [1] FALSE FALSE FALSE FALSE FALSE  TRUE  TRUE

x == 99
# [1] FALSE FALSE FALSE FALSE FALSE  TRUE    NA
```

This makes `labelled_spss()` redundant, it could be collapsed into the function `labelled()`. And of course, SPSS-type "declared" missing (real) values can actually be treated as missing.
It may very well be this is not the best implementation, but I believe the principle is there.
