### ISSUE TITLE
read_sav returns `Error: Invalid input type, expected 'list' actual 'NULL'`

### ISSUE THREAD

**Issue by sjkiss** [tidyverse/haven#576]
I tried installing the development version of `haven` to address [this](https://github.com/tidyverse/dplyr/issues/5196) problem, but `read_sav` seems to no longer read in this data file properly. It returns `Error: Invalid input type, expected 'list' actual 'NULL'`

```r
remotes::install_github('tidyverse/haven')
library(haven
dat<-read_sav('https://github.com/LISPOP/public-health-canada/raw/main/data/ORD-571352-N3W7_Final_SPSS_032221.SAV')

```

**Comment by sjkiss** [comment]
Can confirm: jumping back to haven 2.3.1 reads the file in properly.

**Comment by hadley** [comment]
Underlying bug in cpp11: https://github.com/r-lib/cpp11/issues/166
