### ISSUE TITLE
write_sav storing NA values as blanks character strings

### ISSUE THREAD

**Issue by sjkiss** [tidyverse/haven#578]
I tried to recreate my environment with `dput()`. I'm trying to create a smaller subset of an SPSS file for a class; other use cases though might be to reduce an SPSS file with collaborators. After loading the `.sav` file totally normally and done some data cleaning, I only want to export one variable, e.g. the variable `vote` below. You'll see in the output from `dput()` there are some missing values there, which AFAIK seem to be properly stored on my end as NA. So I try write out the object `test` into an `.sav` file that I can share with students for an exam (or send to collaborators, whatever). But, the SPSS file that I have exported via `write_sav` is storing NA values as blank strings on re-import. via `read_sav()`.

```r
library(haven)
library(tidyverse)
library(labelled)
test<-structure(list(vote = c(NA, NA, "Liberal", "BQ", "NDP", "BQ", 
                              "Greens", "BQ", "Conservative", "Liberal", NA, "BQ", "Conservative", 
                              NA, NA, NA, "Liberal", "Liberal", NA, "Greens", NA, "Liberal", 
                              "Greens", "Liberal", "Liberal")), row.names = c(NA, -25L), class = c("tbl_df", 
                                                                                                   "tbl", "data.frame"))
#Check the variable
table(test$vote)
#Missing values are stored as NA
table(test$vote, useNA = "ifany")
#Write out into test.sav
write_sav(test, 'test.sav')
#Read back in
test<-read_sav('test.sav')
#Check the table
#Note that missing values are no longer NA
table(test$vote)  
table(test$vote, useNA = "ifany")
```

**Comment by hadley** [comment]
Thanks for providing some code that illustrates the problem — it's a great start 😄 However, your code seems to do more than required to illustrate the problem, and the extra complexity is making it hard for me to understand. Can you please try and simplify your example some more? The more minimal you can make the reprex, the faster I can identify the problem and fix it.

**Comment by sjkiss** [comment]
Revised the request with a streamlined code via `dput()` and some more background info. Thank you for looking into it.

**Comment by hadley** [comment]
Minimal reprex:

``` r
library(haven)
path <- tempfile()

df <- data.frame(x = c("a", "b", NA))
write_sav(df, path)
read_sav(path)$x
#> [1] "a" "b" "" 
#> attr(,"format.spss")
#> [1] "A2"
```

<sup>Created on 2021-04-08 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

**Comment by hadley** [comment]
Hmmm, the problem is that by default SPSS uses `""` for missing values. If you want them to become "real" missing values, you need to set an `na_value`:

``` r
library(haven)
path <- tempfile()

df2 <- data.frame(x = labelled_spss(c("a", "b", NA), na_values = ""))
write_sav(df2, path)
read_sav(path)$x
#> [1] "a" "b" NA 
#> attr(,"format.spss")
#> [1] "A2"
```

<sup>Created on 2021-04-08 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

(Requires #581).
