### ISSUE TITLE
Define a `readr::output_column` method for `haven_labelled` objects

### ISSUE THREAD

**Issue by dusadrian** [tidyverse/haven#585]
Tagged NA values, in `haven_labelled` objects have specific (and different meanings) than regular NA values, but all this information is lost when saving to a CSV file, all missing data being written as NA.

```r
library(haven)
library(readr)
path <- tempfile()
x <- data.frame(A = labelled(c(1, tagged_na('a'))))
write_csv(x, tempfile)

# A
# 1
# NA
```

Other software such as Stata export this dataset as:

```
# A
# 1
# .a
```

Would it be possible to add such an option for `write_csv()`?

**Comment by dusadrian** [comment]
Thanks Jim, that would be another great feature in `haven`.

**Comment by hadley** [comment]
I'm not sure this would be a net win, since nothing currently reads in these tagged NAs. I think this is out of scope for haven, because tagged NAs abuse R's NA system a little are not designed to be long term storage mechanisms.

**Comment by dusadrian** [comment]
Yes indeed, it is the main reason why I (subsequently) created package 'declared'. Most of these issues are now obsolete.

**Comment by hadley** [comment]
Do you mind closing those issues with a pointer to declared?

**Comment by dusadrian** [comment]
Done. Only one more issue left open, which has nothing to do with declared but with haven. When exporting to SPSS, it loses the missing values information.
