### ISSUE TITLE
Option to print / format tagged NAs

### ISSUE THREAD

**Issue by dusadrian** [tidyverse/haven#590]
The default way of printing a tagged NA value is, for instance: `NA(a)`.
I do understand the reason (missing values are NAs in R after all and this is not going to change) but some users might prefer to see`.a` instead.

This is just a printing matter, with zero side effects on the overall functionality of the package. It involves setting / getting custom options for the package haven, something like:

```r
format_tagged_na <- function(x, digits = getOption("digits"), format = getOption("haven")$tagged) {
  out <- format(vec_data(x), digits = digits)
  if (format == "default") {
    out[is_tagged_na(x)] <- paste0("NA(", na_tag(x)[is_tagged_na(x)], ")")
  } else if (format == "dot") {
    out[is_tagged_na(x)] <- paste0(".", na_tag(x)[is_tagged_na(x)])
  }
  # format again to make sure all elements have same width
  format(out, justify = "right")
}
```

There is an obvious disadvantage to have multiple ways of displaying missing values, but this would be optional.

EDIT: it is possible to overwrite this function after loading the haven namespace, but I would rather use a formal option, if considered desirable.

**Comment by hadley** [comment]
Thanks for filing this issue! Unfortunately, I don't think it's a good fit for this package: developing good software requires relentless focus, which means that we have to say no to many good ideas. Even though I'm closing this issue, I really appreciate the feedback, and hope you'll continue to contribute in the future 😄

**Comment by dusadrian** [comment]
Thanks very much for the response @hadley, this is not a problem of course.
One can always resort to unlocking the package `haven`'s environment and overwrite this function as deemed fit.
