### ISSUE TITLE
Adding more options to merge differently labelled vectors

### ISSUE THREAD

**Issue by deschen1** [tidyverse/haven#593]
Inspired by the bug fix for this one (https://github.com/tidyverse/haven/issues/543) I was wondering if there should be more user control in how to merge vectors when labels don't match perfectly.

If I'm not mistaken, haven just merges things if there are no competing labels and otherwise takes the left-hand side. However, I think it would make sense to also consider cases where taking the right-hand side would be better, e.g. take a survey situation where you add new data points to your existing data set for which new labels existed in one of the survey questions, e.g. for the old data the survey asked in one question about Pepsi and Coke, and now for the new data points it asked about Pepsi, Coke and 7Up.

**Comment by hadley** [comment]
In that case, you'll need to implement your own strategy. haven only provides simple tools to ensure that it's possible to rbind multiple data frames together.
