### ISSUE TITLE
write_sav() fails to set missing values

### ISSUE THREAD

**Issue by dusadrian** [tidyverse/haven#596]
Information about missing values is lost, roundtrip reprex below

```r
library(haven)
library(tibble)
test <- tibble(A = labelled_spss(1:10, c(Good = 1, Bad = 8, DK = 9, NR = 10), na_values = c(9, 10)))
test$A
# <labelled_spss<integer>[10]>
#  [1]  1  2  3  4  5  6  7  8  9 10
# Missing values: 9, 10

# Labels:
#  value label
#      1  Good
#      8   Bad
#      9    DK
#     10    NR

write_sav(test, "test.sav")

testback <- read_sav("test.sav")
testback$A
# <labelled<double>[10]>
#  [1]  1  2  3  4  5  6  7  8  9 10

# Labels:
#  value label
#      1  Good
#      8   Bad
#      9    DK
#     10    NR
```

**Comment by gorcha** [comment]
HI @dusadrian,

This appears to be an issue in readstat - it supports writing missing values for doubles, but not for integers.
It'll need to be fixed in readstat before we can do anything in haven, I'll raise an issue over there.

In the mean time, as a work around you can convert to numeric before making it a labelled vector:
``` r
library(haven)
library(tibble)
test <- tibble(A = labelled_spss(as.numeric(1:10), c(Good = 1, Bad = 8, DK = 9, NR = 10), na_values = c(9, 10)))
test$A
#> <labelled_spss<double>[10]>
#>  [1]  1  2  3  4  5  6  7  8  9 10
#> Missing values: 9, 10
#> 
#> Labels:
#>  value label
#>      1  Good
#>      8   Bad
#>      9    DK
#>     10    NR

write_sav(test, "test.sav")

testback <- read_sav("test.sav", user_na = TRUE)
testback$A
#> <labelled_spss<double>[10]>
#>  [1]  1  2  3  4  5  6  7  8  9 10
#> Missing values: 9, 10
#> 
#> Labels:
#>  value label
#>      1  Good
#>      8   Bad
#>      9    DK
#>     10    NR
```

<sup>Created on 2021-08-04 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

**Comment by dusadrian** [comment]
Thanks @gorcha , that is a good workaround in the meantime. And hopefully, it will be solved in ReadStat soon.

**Comment by gorcha** [comment]
Hi @dusadrian - sorry, to clarify I think this issue should stay open in haven.

This change will still need to be made in haven, it just needs to be implemented in readstat first :slightly_smiling_face:

**Comment by dusadrian** [comment]
Oh, I see. Alright then, I am reopening it to make sure it will be solved at some point.
