### ISSUE TITLE
Option to replace NA with -99 when writing SPSS SAV

### ISSUE THREAD

**Issue by bertvandepoel** [tidyverse/haven#598]
I've always worked with R in the past and never really felt the need to consider of explore commercial solutions. Now as part of an interdisciplinary research team, it seems however that we have to exchange data between users of SPSS and R, mostly output from R into SPSS. To streamline this process, I've been trying out haven's write_SAV function. While my colleagues report that it largely works as expected, they did mention that NA isn't translated to -99, which apparently is a common way of dealing with NA in SPSS (though I find it very strange personally). 

I have been unable to find an option to control how R's NA is translate to SPSS SAV within write_SAV, so I thought I'd write this feature request to ask whether such a feature could be implemented.

**Comment by hadley** [comment]
Thanks @dusadrian!
