### ISSUE TITLE
Unable to allocate memory-- haven 2.4.1

### ISSUE THREAD

**Issue by broad32** [tidyverse/haven#604]
Resurrecting an old issue that appears to have resurfaced in the latest haven update:

https://github.com/tidyverse/haven/issues/342

I cannot attach the file, but this is the error:

 Failed to parse file.sas7bdat: Unable to allocate memory.

I recognize that I could revert to the old version of haven, but wanted to bring attention to this issue in case it spurs a faster change to the library.  Perhaps the next update will resolve this issue.

**Comment by hadley** [comment]
There's no way to fix the problem without a SAS file that illustrates the issue, sorry.
