### ISSUE TITLE
write_dta limits you to 31 character column names even though Stata allows 32 character names

### ISSUE THREAD

**Issue by jacobkap** [tidyverse/haven#605]
In Stata the maximum number of characters that a column name may have is 32 characters (https://www.stata.com/manuals/r.pdf#rLimits). write_dta checks the length of each column name if there is a name >31 characters, but since 32 characters is allowed this should be >32 or >=31. 

```r
library(haven)
example <- data.frame(name_that_is_32_characters_long_ = 1)
write_dta(example, "example.dta")

example <- data.frame(name_that_is_31_characters_long = 1)
write_dta(example, "example.dta")
```

**Comment by sbae** [comment]
Ditto. This was causing a crash to me this morning. Updating the limit to >32 seems to be working well. I created a pull request (https://github.com/tidyverse/haven/pull/616).
