### ISSUE TITLE
`write_dta` can't save numeric labelled variables without value labels

### ISSUE THREAD

**Issue by domingoscisci** [tidyverse/haven#606]
Hi all,
I have a data.frame of double (no integer) variables that I want to label (only variable label, not value labels). If I try to use the `labelled()` function, a vector of class _dbl+lbl_ is correctly created, but it cannot be saved in a Stata file using `write_dta()`. If I use the `attr()` function the problem does not arise.
It is probably not correct to use `labelled()` to label the variable only. In this case, perhaps it might be useful to make this explicit within the documentation (maybe I missed something?).

Here is a reprex:

```r
library(tibble)
library(haven)


dat <- tibble(
  a = c(0.1, 0.2, 0.3, 0.4, 0.5)
)

# label variable with haven::labelled
dat$a <- labelled(dat$a, label = "test label")

# write_dta fails
write_dta(dat, tempfile(fileext = "dta"))
#> Error: Stata only supports labelling with integers.
#> Problems: `a`


dat <- tibble(
  a = c(0.1, 0.2, 0.3, 0.4, 0.5)
)

# label variable with attr
attr(dat$a, "label") <- "test label"

# write_dta ok
write_dta(dat, tempfile(fileext = "dta"))
```

Thank you for your help,
Domingo

**Comment by jmobrien** [comment]
Seconding this issue, and noting that it is uniquely a problem with non-integer numerics lacking value labels:

``` r
require(haven) # 2.4.1
#> Loading required package: haven
df <- 
  data.frame(
    x1 = labelled(1:10),
    x2 = labelled(as.numeric(1:10), labels = c(one = 1)),
    x3 = labelled(as.character(1:10)),
    x4 = labelled(as.numeric(1:10))
  )

path <- tempfile()
write_dta(df, path)
#> Error: Stata only supports labelling with integers.
#> Problems: `x4`
```

<sup>Created on 2021-06-03 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

**Comment by jmobrien** [comment]
Problem seems to be here:

https://github.com/tidyverse/haven/blob/dbd65a3c3aa087ecacf1a378360ad9c967954cf1/R/haven-stata.R#L150

`is_integerish()` returns FALSE if the labels are missing, producing this issue.  Submitted PR #609 to address.

**Comment by dusadrian** [comment]
If you don't mind a workaround, this solves your example:

``` r
install.packages("declared")
devtools::install_github("dusadrian/DDIwR")
library(declared)
library(DDIwR)
df <- as_declared(df)
convert(df, to = "Stata")

# or convert(df, to = "path/to/file.dta")
```

I would highly recommend using declared objects instead of labelled. Apart from being superior in treating missing values, they also allow variables without value labels, and they are fully compatible with the traditional labelled objects.
