### ISSUE TITLE
stripping value labels from imported SPSS `.sav` data

### ISSUE THREAD

**Issue by xmatic** [tidyverse/haven#610]
In `haven` docs, I've seen examples of how `zap_labels()` will strip value labels from variables. In each case in the docs, the variable used in the example was created using an `R` assignment operator (`<-`) to directly create a vector (e.g. image below, via: https://haven.tidyverse.org/reference/zap_labels.html ).

![zap labels vector creation](https://user-images.githubusercontent.com/5103936/120904341-fbb65280-c608-11eb-9771-2f4e53ace9f8.jpg)

However, I'm trying to use `zap_labels()` on data I've imported using haven's `read_sav()`, and it doesn't seem to be working as I expect. 

----------

Code: (I'm on Windows 10):

I import a `.sav` file using `haven` like so:
```r
June18 <- read_sav("C:/ ... filename.sav", 
  user_na = FALSE) %>% 
  as_factor() 
```

----------
The variable I'm exploring is `V1Q1_W35`

Attributes:
```{r}
attributes(June18$V1Q1_W35)
```
Output:
> $levels
> [1] "Very fair"       "Somewhat fair"   "Not very fair"   "Not fair at all" "Refused"        

----------

In the original `.sav` file, value label mappings for `V1Q1_W35` look like this:
![value label mappings](https://user-images.githubusercontent.com/5103936/120883509-dc80dc00-c59a-11eb-8210-9ed949015fb8.jpg)

----------

So, per my understanding, if I do `zap_labels()` to `V1Q1_W35`, I should see the original numbers in the data like `1`, `2`, `3`, `4` and `99`.

However, when I do the following, I still see value labels.
```{r}
attributes(zap_labels(June18$V1Q1_W35))
```
Output:
> $levels
> [1] "Very fair"       "Somewhat fair"   "Not very fair"   "Not fair at all" "Refused"        

----------

**So my question is: in this situation (trying to see the different levels), what should I be doing to see the original numbers in the data instead of the value labels they are mapped to?**

**Comment by gorcha** [comment]
Hi @xmatic, the issue here is that you're using `as_factor()` when you read in the sav file, which is converting labelled variables into standard R factors and losing the haven metadata.
``` r
library(haven)

x_labelled <- labelled(1:5, c(good = 1, bad = 5))
x_labelled
#> <labelled<integer>[5]>
#> [1] 1 2 3 4 5
#> 
#> Labels:
#>  value label
#>      1  good
#>      5   bad

x_factor <- as_factor(x_labelled)
x_factor
#> [1] good 2    3    4    bad 
#> Levels: good 2 3 4 bad

zap_labels(x_labelled)
#> [1] 1 2 3 4 5

zap_labels(x_factor)
#> [1] good 2    3    4    bad 
#> Levels: good 2 3 4 bad
```

<sup>Created on 2021-07-25 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

**Comment by hadley** [comment]
Thanks @gorcha!

**Comment by xmatic** [comment]
Thank you for clarifying this @gorcha . Much appreciated.
