### ISSUE TITLE
Failed to read .sas7bdat file with SAS inencoding="EUC-CN" into R with package haven

### ISSUE THREAD

**Issue by huanlusanofi** [tidyverse/haven#612]
Hello developer, my name is Bryce, I work for a global pharmaceutical company and currently work on local submission in China.

One of my job is to prepare documentations for submission, which requires to extract some of the information from .sas7bdat file. What is the most tricky part is that those .sas7bdat files I need contain Chinese characters as dataset label and variable label, and those files were created in SAS with encoding as "EUC-CN".

All acceptable encodings in SAS are listed here: https://support.sas.com/documentation/onlinedoc/dfdmstudio/2.6/dmpdmsug/Content/dfU_Encodings_SAS.html

Is there anyway I can still use haven in R to extract the dataset label and variable label as what they should be in Chinese? Thank you very much!

**Comment by gorcha** [comment]
Can you please provide a minimal reproducible example using the [reprex](http://reprex.tidyverse.org) package?
The goal of a reprex is to make it as easy as possible for me to recreate your problem so that I can fix it.
If you've never made a minimal reprex before, there is lots of good advice [here](https://reprex.tidyverse.org/articles/reprex-dos-and-donts.html).

**Comment by gorcha** [comment]
Just to confirm, what's the issue that you're having? EUC-CN is a supported encoding, so the variable and value labels should read in successfully.

If the file encoding is set to "EUC-CN" it should be automatically used by `read_sas()`, but if it's not picking it up successfully you can try manually setting it with the encoding argument, like:
```r
read_sas(file, encoding = "euc-cn")
```

**Comment by huanlusanofi** [comment]
> Just to confirm, what's the issue that you're having? EUC-CN is a supported encoding, so the variable and value labels should read in successfully.
> 
> If the file encoding is set to "EUC-CN" it should be automatically used by `read_sas()`, but if it's not picking it up successfully you can try manually setting it with the encoding argument, like:
> 
> ```r
> read_sas(file, encoding = "euc-cn")
> ```

Thank you gorcha! I made it once I have my haven package upgraded to 2.4.1, thank you anyway!
