### ISSUE TITLE
read_dta of 2GB files uses 19GB memory

### ISSUE THREAD

**Issue by ozak** [tidyverse/haven#617]
I am opening a large 2GB Stata file. If I do so in Stata it only uses 2GB memory. Using read_dta it ends eating up 19+GB of memory. Is there a way to improve memory use by this function?

**Comment by hadley** [comment]
It's possible there's some bug leading to run away memory usage, but that seems fairly unlikely, so it's most likely to be a difference between how stata and R store data.
