### ISSUE TITLE
write_xpt version = 8 files not able to be read by SAS

### ISSUE THREAD

**Issue by Nate884** [tidyverse/haven#632]
So this is a clarification of "SAS doesn't read write_xpt", specifically, SAS is not able to import any write_xpt with the "version = 8" parameter, but does with "version = 5". 

```r
write_xpt (mtcars, "mtc_h8.xpt", version = 8)
```

What is especially tricky is that it is able to be read by the SAS Viewer/Universal Reader as a valid XPT file, but is unable to be imported into SAS. 

```sas
LIBNAME MTCH8 XPORT "mtc_h8.xpt";
PROC COPY INlib=MTCH8 OUTlib=work memtype=data ;
RUN;
```

gives the following error:

```sas
NOTE: Input library MTCH8 is sequential.
ERROR: File MTCH8.ALL. is not a SAS data set.
NOTE: Statements not processed because of errors noted above.
NOTE: PROCEDURE COPY used (Total process time):
      real time           0.01 seconds
      cpu time            0.00 seconds
```

**Comment by gorcha** [comment]
Hi!

I've had a poke around and it looks like version 8 XPT files can't be read by `PROC COPY`, they need to use a special macro `%XPT2LOC`. Check out the [XPT V8 announcement](https://support.sas.com/kb/46/944.html) and the [XPT2LOC documentation](https://documentation.sas.com/doc/en/pgmsascdc/9.4_3.5/movefile/p1tp8gighlgeifn173i6kzw2w3bu.htm#!) for a bit more information.

So this should load the data set successfully:
```sas
LIBNAME MTCH8 XPORT "mtc_h8.xpt";
%XPT2LOC(libref=work, filespec=MTCH8);
RUN;
```

**Comment by gorcha** [comment]
Closing since this appears to be solved, feel free to reopen if you're still having issues.
