### ISSUE TITLE
Add `user_na` option to `zap_labels()`

### ISSUE THREAD

**Issue by gorcha** [tidyverse/haven#638]
Currently `zap_labels()` converts user missing values in labelled_spss objects to `NA`.

This should be controllable by the user. I think adding a `user_na` option like `read_sav()` is the best approach, where `FALSE` (default) converts to `NA` and `TRUE` keeps them as valid values.

``` r
library(haven)
x <- labelled_spss(1:3, na_values = 1)
# Current behaviour
zap_labels(x)
#> [1] NA  2  3

# Desired behaviour
zap_labels(x, user_na = TRUE)
#> [1] 1  2  3
```

<sup>Created on 2021-09-15 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by LuiNov** [comment]
Hey, 

I have an issue reading a dta file with several missings. Numerics are -5:0 and labels are ("Missing:Other", "Not askey") etc. . How can I specify those to the function so I get the clean dataset ?????

I think it doesn't fit into this issue but I didn't know elsewhere to comment.... Thanks a lot :-)

**Comment by gorcha** [comment]
Hi @LuiNov - I've just moved this to its own issue at #645, shall reply over there.
