### ISSUE TITLE
Feature request : low-memory confings -> adding possibility to filter within the reader

### ISSUE THREAD

**Issue by arnaud-feldmann** [tidyverse/haven#639]
Hi,

Firstly, thanks for your very useful work !

I have a feature request, through maybe it isn't possible as I know neither the SAS format nor the way haven reads it.

The problem is : in the low-memory configs, one can't read sas file larger than the memory size. Could this problem in some cases be solved with some kind of internal filtering ? That way it would allows people like me to work with R in places where you got no R servers, and where everywhere works with SAS.

The best would be some kind of compatibility with the dplyr verbs, that allows some kind of optimised summarize too, but I realise that this is a dream, more complicated, and that a sas table isn't a SQLite db.

**EDIT :** I just realized that **skip** and **n_max** can be used to loop and filter around a sas file without breaking the ram, so maybe the FR is useless. Don't know if it is the expected use through.

**Comment by gorcha** [comment]
Hi @arnaud-feldmann,

Thanks for the feedback! Unfortunately there are no plans to implement a set of chunked reader functions at the moment - it's a significant undertaking implementing and maintaining a robust callback API so it's out of our scope (see also #194).

The `skip` and `n_max` functions can definitely be used to implement this behaviour though :slightly_smiling_face:
See this recent pull request #633, courtesy of @Shaunson26, for a simple implementation.
