### ISSUE TITLE
`write_sav()` does not check for duplicated variable names

### ISSUE THREAD

**Issue by sjkiss** [tidyverse/haven#641]
I am trying to export a data set as an sav file via `write_sav`. It would be convenient for me to have haven_labelled versions of variables as well as pure factor variables. I'm trying to export the data with the labelled versions of the variables with lower case names and with the factor version of the variables 

```r
#This creates my data frame with one labelled variable and a duplicate factor
test<-structure(list(francophone = structure(c(0, 0, 0, 0, 0, 0, 0, 0, 0, 0), labels = c(Francophone = 1, `Not Francophone` = 0), label = "Dichotomous variable, R is francophone", class = c("haven_labelled", "vctrs_vctr", "double")), Francophone = structure(c(1L, 1L, 1L,1L, 1L, 1L, 1L, 1L, 1L, 1L), .Label = c("Not Francophone", "Francophone"), label = "Dichotomous variable, R is francophone", class = "factor")), row.names = c(NA,-10L), class = c("tbl_df", "tbl", "data.frame"))

#Create a second factor but with a significantly different name
test$Franco<-test$Francophone
#Export the data-set and look.
test %>% 
  write_sav(., path="~/Desktop/test2.sav")

```
<img width="1159" alt="Screen Shot 2021-09-24 at 10 32 30 AM" src="https://user-images.githubusercontent.com/5245117/134693254-fd5c51a9-e9df-492d-9a19-f65aaf4577f2.png">

My desired outcome would be for `write_sav()` to treat variable names case sensitively

**Comment by gorcha** [comment]
Hi!

This is an SPSS thing - SPSS is itself case insensitive, so there's no way to write "francophone" and "Francophone" as separate variables unfortunately.

Really this should throw an error when attempting to write the file in haven, so we really need to add variable name validation to `write_sav()`.
