### ISSUE TITLE
Feature request: random sample reader 

### ISSUE THREAD

**Issue by juansebastianl** [tidyverse/haven#642]
I wanted to ask what people's thoughts about implementing a random sample reader, specifically for large files. It would work very similar to `n_max` (take an integer as an input) and allow a `read_dta` or the other haven functions to return a sample of the dataset of that size. It seems like a more simple undertaking than a full chuncked API  (i.e. #194 ) but at the same time would allow people who have large data files to have quick dev time before scheduling batch scripts (same idea as `head` but with a sample which would provide a more representative picture). I don't have a good sense for the c++ codebase, though, so I don't know.

**Comment by gorcha** [comment]
Hi @juansebastianl,

Thanks for filing this issue! Unfortunately, I don't think it's a good fit for this package: developing good software requires relentless focus, which means that we have to say no to many good ideas. Even though I'm closing this issue, I really appreciate the feedback, and hope you'll continue to contribute in the future.

Basically it's a bit more complicated than it seems given the back end set up. Doing a proportional sample using `skip` and `n_max` is much more straightforward, so I think this is more of a +1 for the chunked reader functions.

Here's a simple example that keeps 10% of a Stata file by reading in chunks of 1000 and sampling each with dplyr's `slice_sample()`:
``` r
library(haven)
library(dplyr)

read_dta_sample <- function(..., prop = 0.1, chunk_size = 1000) {
  skip = 0
  out <- tibble()
  
  while (TRUE) {
    chunk <- read_dta(..., skip = skip, n_max = chunk_size)
    if (nrow(chunk) == 0) break
    
    out <- bind_rows(out, slice_sample(chunk, prop = prop))
    skip = skip + chunk_size
  }
  
  out
}

path <- system.file("examples", "iris.dta", package = "haven")
read_dta_sample(path)
#> # A tibble: 15 × 5
#>    sepallength sepalwidth petallength petalwidth species   
#>          <dbl>      <dbl>       <dbl>      <dbl> <chr>     
#>  1        6.30       2.5         4.90      1.5   versicolor
#>  2        7.70       2.60        6.90      2.30  virginica 
#>  3        5.80       2.70        4.10      1     versicolor
#>  4        5.90       3           4.20      1.5   versicolor
#>  5        4.80       3           1.40      0.100 setosa    
#>  6        7          3.20        4.70      1.40  versicolor
#>  7        5.60       2.80        4.90      2     virginica 
#>  8        7.60       3           6.60      2.10  virginica 
#>  9        5.10       3.80        1.5       0.300 setosa    
#> 10        6.40       3.10        5.5       1.80  virginica 
#> 11        4.90       3.10        1.5       0.100 setosa    
#> 12        6.60       2.90        4.60      1.30  versicolor
#> 13        5.20       4.10        1.5       0.100 setosa    
#> 14        4.5        2.30        1.30      0.300 setosa    
#> 15        5.60       3           4.5       1.5   versicolor
```

<sup>Created on 2021-09-26 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>
