### ISSUE TITLE
Error: basic_string::_M_construct null not valid

### ISSUE THREAD

**Issue by jakoberr** [tidyverse/haven#649]
I have a SPSS-file for my research work, which I would like to analyse with R and I'm using `haven::read_sav()` to read it in. However, when I run `haven::read_sav(path_to_file)` I get the following error message:

`Error: basic_string::_M_construct null not valid`

The SPSS file can be opened via SPSS without any (obvious) error messages and as far as I can see, nothing is wrong with variable/label names, etc. 
The problem is, that I can't share the file publicly, because it contains highly confidential information and since it contains a lot (as in: hundreds) of variables, I struggle a bit to create a similar dummy data sets for e.g. a reprex.

I tried researching a bit beforehand, but my C++ knowledge is rather limited. This error message seems to be thrown, if there is any kind of null pointer problem.

Any help is very much appreciated, let me know, if there is any information I can add.

**Comment by gorcha** [comment]
Hi @jakoberr, thanks for the bug report!

Unfortunately we can't really look into it without an example file - the code base for file reading is relatively complex and there aren't really any hints here that we could pursue without being able to reproduce the error.

A few checks you could do that might help to narrow it down using the chunking API are:
* Use the `col_select` argument to try reading in each column one by one and see if it errors on all or only specific columns, like so:
```r
my_cols <- c("col1", "col2", ...)

for (column in my_cols) {
  cat(column, "\n")
  invisible(read_sav(path_to_file, col_select = column))
}
```

* Try reading in all columns but no rows to check if it's an issue with metadata or data:
```r
read_sav(path_to_file, n_max = 0)
```

* Use the `skip` and `n_max` arguments to only load in specific rows to see if it errors on a specific row, for e.g.:
```r
num_rows <- 1000

for (i in seq_len(num_rows)) {
  cat(i, "\n")
  invisible(read_sav(path_to_file, skip = i - 1, n_max = 1))
}
```

**Comment by gorcha** [comment]
No worries at all, always happy to help! Glad you figured the issue out, as strange as it is 🙂
