### ISSUE TITLE
`labelled_spss()` overwrites the pre-existing information, please fix

### ISSUE THREAD

**Issue by aito123** [tidyverse/haven#652]
Hello i have a petition for the `labelled_spss()` function in haven package. When i define variable label or value label for a variable in a df and this variable already has a variable or value it does not pass the preexisting information.

For example:
```r
base1 %>% 
  mutate(variable=labelled_spss(variable, label = "Name for the variable")
```
If my variable in my base1 has value labels like "Yes" / "No" this are dropped. I think the ideal would be that if I don't specify a value label, the preexisting value label should be pass.

Please let me know if you need further information to solve this problem. Huge fan of haven btw.

Sincerely,
Santiago

**Comment by HaloReach2552** [comment]
Tu primer issue
ajajaja sigues usando spps . Saludos

**Comment by gorcha** [comment]
Hi Santiago,

The `labelled()` and `labelled_spss()` functions are intended to create new labelled vectors, so they purposefully don't retain existing metadata to avoid unexpected behaviour.

I'd recommend having a look at the [labelled](https://larmarange.github.io/labelled) package for manipulating metadata for existing vectors. haven provides the `labelled` and `labelled_spss` classes as an intermediate class between Stata/SPSS/SAS and native R classes, but the labelled package provides some extra helper functions for modifying the metadata of labelled vectors, including `var_label()` and `set_variable_labels()` for working with variable labels.

In your case you could use either function, like so:
```r
base1 %>%
  set_variable_labels(variable = "Name for the variable")

var_label(base1$variable) <- "Name for the variable"
```

Hope that helps!
Danny

**Comment by aito123** [comment]
Hello Danny thanks for the quick response. I like `labelled_spss()` because it allows you to define `label=` and `labels=` in the same function. And i `haven`'t found a function that does the same job in the `labelled` or in `sjlabelled` packages. Any recommendation or i would need two functions? One for label and other for labels? 

Thanks

**Comment by gorcha** [comment]
Hey Santiago, no worries!

I think it depends on what you want to do - `labelled()` and `labelled_spss()` create labelled vectors, and the functions from the labelled package mainly edit attributes/metadata for existing vectors.

`labelled()` and `labelled_spss()` are perfect for creating a new labelled vector/converting a standard vector into a labelled vector (inc. the variable label where relevant), but not so good for editing metadata since they drop any existing attributes.
The additional functions from labelled are perfect for editing metadata, including cases where a variable is not labelled but needs other metadata attached.

For example:
``` r
library(dplyr)
library(haven)
library(labelled)

x <- tibble(
  cat_var = c(1, 1, 1, 0, 0),
  num_var = c(1.1, 2.2, 3.3, 4.4, 5.5),
  txt_var = letters[1:5]
)

x <- x %>%
  mutate(
    cat_var = labelled(cat_var, labels = c("Yes" = 1, "No" = 0))
  ) %>%
  set_variable_labels(
    cat_var = "A categorical variable",
    num_var = "A numeric variable",
    txt_var = "A free text variable"
  )

str(x)
#> tibble [5 x 3] (S3: tbl_df/tbl/data.frame)
#>  $ cat_var: dbl+lbl [1:5] 1, 1, 1, 0, 0
#>    ..@ labels: Named num [1:2] 1 0
#>    .. ..- attr(*, "names")= chr [1:2] "Yes" "No"
#>    ..@ label : chr "A categorical variable"
#>  $ num_var: num [1:5] 1.1 2.2 3.3 4.4 5.5
#>   ..- attr(*, "label")= chr "A numeric variable"
#>  $ txt_var: chr [1:5] "a" "b" "c" "d" ...
#>   ..- attr(*, "label")= chr "A free text variable"
```

<sup>Created on 2021-11-30 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>
