### ISSUE TITLE
write_sas produces SAS datasets that can't be opened in SAS

### ISSUE THREAD

**Issue by szimmer** [tidyverse/haven#654]
If I create a SAS dataset using, `write_sas`, it cannot be opened by SAS Universal Viewer or SAS programming language. 

``` r
library(haven)
library(tidyverse)
mtcars %>% as_tibble(rownames = "car") %>%
   write_sas("mtcars.sas7bdat")
```

<sup>Created on 2021-11-29 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

When I try to open the dataset in SAS Universal Viewer, it gives an error that "Unable to load table mtcars. One common cause is when the table has an associated index which was not found".

**Comment by ldx007jjo** [comment]
same https://github.com/tidyverse/haven/issues/224

**Comment by gorcha** [comment]
Closing since the discussion is at #224, thanks for the report!
