### ISSUE TITLE
`haven::write_dta()` doesn''t convert data to STATA 13

### ISSUE THREAD

**Issue by aito123** [tidyverse/haven#655]
Everything works fine with the function `write_dta(..., version = 13, encoding="latin1)` but when i open my file in stata and check for thee version of myy data set with the funcction `version.dta` it appears to be 14, 15 and 16 version. Not the one i defined.

Can you please check the consistency of this function when saving it in older versions of stata (like 13?). Thanks

**Comment by gorcha** [comment]
Hi!

From what I can see version=13 successfully writes using the correct file format (dta version 117).

I can't find any reference for the `version.dta` function - where is this coming from? Is this a stata function?
Does this happen with all files you output, or only when using specific data frames?

**Comment by aito123** [comment]
Hi Gorcha thanks for the quick responde.
Sorry for wasting your time, i figure out that i had a typo error (the version= argument was inside the name of the file so it wasn't recognizing it). versiondta is a stata function to know in what version is the .dta. anyway thanks for the attention and i close the comment.

**Comment by gorcha** [comment]
Not a problem! Always happy to help :slightly_smiling_face:
