### ISSUE TITLE
write_xpt is unable to keep the attribute of label

### ISSUE THREAD

**Issue by yangwenghou123** [tidyverse/haven#665]
Dear Team,

I'd like to use write_xpt to convert data.frame to xpt for submission.
The label of xpt is required, but it will be lost after using this function.
read_xpt is able to keep the dataset label of xpt created by SAS though.
Did I miss something when use write_xpt, or there is no such feature to keep df label?

```r
tmp <- tempfile(fileext = ".xpt")
mydf <- mtcars
attr(mydf, "label") <- "test"
attr(mydf, "label")
write_xpt(mydf, tmp)

mydf2 <- read_xpt(tmp)
attr(mydf2, "label")
```

**Comment by gorcha** [comment]
Hi!

Writing data set labels for XPT files has been added to the development version of haven, but it isn't up on CRAN yet.

Are you using the version installed from CRAN or from GitHub?

**Comment by yangwenghou123** [comment]
Hi!

I am using the version from CRAN.
May I ask how soon the development version will be probably available?
Thank you!

**Comment by gorcha** [comment]
No worries!

We don't have a planned release date at the moment but the next release should be coming pretty soon.
In the meantime, if you'd like to take advantage of the new features in the development version you can install it from GitHub with `devtools::install_github("tidyverse/haven")`.
