### ISSUE TITLE
write_sav() seems fail to write character vectors for which all records are blank

### ISSUE THREAD

**Issue by khanhhtt** [tidyverse/haven#671]
Hi team,

write_sav() seems automatically convert empty string variable (character vectors for which all records are blank) into numeric in the output .sav file. Even though the the formats displayed in SPSS's variable view are correct (still string) but when I compare with the raw data, SPSS recognize the empty string variable as a numeric variable. 

![image](https://user-images.githubusercontent.com/93310387/161368900-fea42f79-bcbb-49b5-9418-626826529f19.png)

Moreover, when I did some analysis on this variable (e.g. descriptive statistic) then the SPSS automatically stop.

Below is the R scripts I used to read and write the file.
```
data <- read_sav("TEST1.sav")
write_sav(data, "TEST2.sav")
```
[TEST data.zip](https://github.com/tidyverse/haven/files/8401924/TEST.data.zip)

I enclose herewith the Test data as an example. **var2** is the empty string variable that I mentioned.

Thank you in advance for looking into this.

**Comment by gorcha** [comment]
Hi @khanhhtt, thanks for the bug report!

We've made a small change to the way that blank string variable widths are set in output files which I think will fix this.

Could you please try installing the current development version from GitHub and see if it resolves this issue?
```r
devtools::install_github("tidyverse/haven")
```

Thanks!
