### ISSUE TITLE
Release haven 2.5.0

### ISSUE THREAD

**Issue by gorcha** [tidyverse/haven#674]
Prepare for release:

* [x] `git pull`
* [x] Check [current CRAN check results](https://cran.rstudio.org/web/checks/check_results_haven.html)
* [x] [Polish NEWS](https://style.tidyverse.org/news.html#news-release)
* [x] `devtools::build_readme()`
* [x] `urlchecker::url_check()`
* [x] `devtools::check(remote = TRUE, manual = TRUE)`
* [x] `devtools::check_win_devel()`
* [x] `rhub::check_for_cran()`
* [x] `rhub::check(platform = 'ubuntu-rchk')`
* [x] `rhub::check_with_sanitizers()`
* [x] `revdepcheck::cloud_check()`
* [x] Update `cran-comments.md`
* [x] `git push`
* [x] Draft blog post — https://github.com/tidyverse/tidyverse.org/pull/575
* [x] Slack link to draft blog in #open-source-comms

Submit to CRAN:

* [x] `usethis::use_version('minor')`
* [x] `devtools::submit_cran()`
* [x] Approve email

Wait for CRAN...

* [x] Accepted :tada:
* [x] `git push`
* [x] `usethis::use_github_release()`
* [x] `usethis::use_dev_version()`
* [x] `git push`
* [x] Finish blog post
* [x] Tweet
* [x] Add link to blog post in pkgdown news menu

**Comment by gorcha** [comment]
Over to you, @hadley

**Comment by hadley** [comment]
@gorcha revdepchecks look good. Would you mind suggesting a few new features that I should highlight in the blog post? I normally just skim the `NEWS.md` looking for the bullets that I think are likely to affect a decent number of people.

**Comment by gorcha** [comment]
Sure!

In general this release is focused on improvements and bug fixes for file writing.

Noteworthy new features are:
* Support for writing StrL variables. With the addition of StrL support it's now possible to write Stata files with character variables longer than 2045 characters, which was a hard upper limit.
* Support for setting custom variable widths.
* With the addition of custom variable width support and some XPT writing related bug fixes it is now possible to create FDA compliant SAS transport files using haven.

**Comment by hadley** [comment]
Do I remember correctly that the support for `strL` also considerably decreases file sizes?

**Comment by gorcha** [comment]
It can do in some cases with smaller character vectors but not universally (only noticeably where there's a lot of duplication). By far the biggest impact of adding strL support is that we can now write strings with more than 2045 characters.

One change that has a big Stata file size improvement is setting the minimum string variable width to 1 instead of 0 - ReadStat used str2045 for 0 width string variables previously, but these now use str1. Since str# uses a fixed amount of bytes per record this saves a huge amount of space in files with blank string variables.

**Comment by hadley** [comment]
Ah got it, thanks!
