### ISSUE TITLE
Labelled column headers are right aligned in tibble output

### ISSUE THREAD

**Issue by MokeEire** [tidyverse/haven#676]
Column headers for labelled columns are right aligned in console tibble output which can make it difficult to interpret which values are associated with which column. See below:

![image](https://user-images.githubusercontent.com/19700454/163455894-252bcc24-c386-4e06-9454-769e86eb4d2e.png)

`col3` is almost above the values of `col4`, making it difficult to read.

Hopefully useful reprex

```r
library(purrr)
library(tibble)
library(haven)

# Combine labelled columns into tibble
map_dfc(paste0("col", 1:4), 
        # Create labelled column
        ~tibble(!!.x := labelled(sample(c(1,5,8,9), 20, replace = T),
                                 labels = c(Yes = 1, No = 5,
                                            `Don't know` = 8,
                                            Refused = 9))))
```

**Comment by gorcha** [comment]
Hey @MokeEire,

Thanks for the change request! haven defaults to right alignment since these are ultimately double variables, but agree that left alignment makes more sense in most cases once labels are included.
