### ISSUE TITLE
`col_select` doesn't appear on the help page for `read_sav`

### ISSUE THREAD

**Issue by Moohan** [tidyverse/haven#682]
The new(ish) parameter `col_select` doesn't appear on the help page when accessed in R e.g. `?read_sav`. Oddly it does appear on the pkgdown site though: https://haven.tidyverse.org/reference/read_spss.html It does also appear on the tooltip in RStudio and can be used.

If it's just a case of adding the correct roxygen comments to the function definition, taking the details from the pkgdown documentation, then I'd be happy to do a PR?

**Comment by gorcha** [comment]
Hi @Moohan, thanks for the report!

I can't replicate this, the `col_select` appears correctly on each of the relevant help pages in a freshly installed copy of haven from CRAN, and in the generated .Rd page for the current dev version at [man/read_spss.Rd](https://github.com/tidyverse/haven/blob/d913105db0d485f95c3965bac13d0c42b9f7cb7d/man/read_spss.Rd) it looks like it's coming through fine as well.

Are you using a version installed straight from CRAN?

**Comment by Moohan** [comment]
I'm not really sure what the issue was... I seem to have two versions installed, v2.4.3 in the system library (to which I don't have write permissions) and v2.5.0 in my personal library. I had definitely installed the personal one from CRAN previously, but I just re-installed and the help page now displays as expected.

Thanks for your time
