### ISSUE TITLE
`NA_character_` is considered as length 2

### ISSUE THREAD

**Issue by bundfussr** [tidyverse/haven#699]
It seems that `NA_character_` is handled as a string of length 2 when writing a SAS transport file with `write_xpt()`. Consider for example:
```r
t <- data.frame(MYFL = c("Y", NA_character_), id = c(1, 2))
attr(t[["MYFL"]], "width") <- 1
haven::write_xpt(t, "t.xpt", version = 5, name = "t")
```
It produces
```
Warning message:
Column `MYFL` contains string values longer than user width 1. Width set to 2 to accommodate. 
```
and the length of `MYFL` in the SAS transport file is 2.

Is this intended?

I would expect length 1 and no warning.

**Comment by gorcha** [comment]
Hi @bundfussr, thanks for the bug report - this definitely shouldn't come through as length 2, will have a look.
