### ISSUE TITLE
Release haven 2.5.2

### ISSUE THREAD

**Issue by gorcha** [tidyverse/haven#715]
Prepare for release:

* [x] `git pull`
* [x] Check [current CRAN check results](https://cran.rstudio.org/web/checks/check_results_haven.html)
* [x] [Polish NEWS](https://style.tidyverse.org/news.html#news-release)
* [x] `devtools::build_readme()`
* [x] `urlchecker::url_check()`
* [x] `devtools::check(remote = TRUE, manual = TRUE)`
* [x] `devtools::check_win_devel()`
* [x] `rhub::check_for_cran()`
* [x] `rhub::check(platform = 'ubuntu-rchk')`
* [x] `rhub::check_with_sanitizers()`
* [x] `revdepcheck::cloud_check()`
* [x] Update `cran-comments.md`
* [x] `git push`

Submit to CRAN:

* [x] `usethis::use_version('patch')`
* [x] `devtools::submit_cran()`
* [x] Approve email

Wait for CRAN...

* [x] Accepted :tada:
* [x] `git push`
* [x] `usethis::use_github_release()`
* [x] `usethis::use_dev_version()`
* [x] `git push`

**Comment by gorcha** [comment]
Hey @hadley, thinking this might need to be a minor (2.6.0) release instead of patch (2.5.2) because of the `write_sas()` soft deprecation - what do you think?

**Comment by hadley** [comment]
I think a patch is probably fine, since `write_sas()` never really worked well. This is more of an acknowledgement that we don't think we can do anything about it.

**Comment by gorcha** [comment]
Hey @hadley, just waiting for rhub to finish checking - could you please run the revdepcheck?

**Comment by hadley** [comment]
Started!

**Comment by gorcha** [comment]
Thanks @hadley! The rhub checks took forever to run but they're done now - some of the checks have errored but it seems to be due to failures in dependency builds and not haven itself.

On the CRAN check results page r-oldrel-windows-ix86+x86_64 is erroring at the moment with a cryptic `install log '' does not exist` message. The install log on the CRAN checks page looks fine, and I've tried building on win-builder with oldrel without issue, so not sure if we should be concerned about this?

**Comment by gorcha** [comment]
P.S. I've updated your email address to the new posit one in DESCRIPTION, shall add a note to `cran-comments.md`

**Comment by hadley** [comment]
@gorcha I think you can ignore the  r-oldrel-windows-ix86+x86_64 problem and no need to add a note for my email address because CRAN seems to handle it automatically now.

**Comment by hadley** [comment]
Just checked the revdeps in. No obvious problems!

**Comment by gorcha** [comment]
OK great! In that case good to submit :slightly_smiling_face:

**Comment by hadley** [comment]
@gorcha https://win-builder.r-project.org/incoming_pretest/haven_2.5.2_20230227_145948/Debian/00check.log 😞

**Comment by gorcha** [comment]
@hadley Annoying! It looked like including `void` in the declarations in the header files had fixed it but evidently not. I'm surprised this didn't show up on any of the test platforms, since we had both gcc and clang covered!

I've added `void` to the appropriate function declarations so should be good to resubmit. Shall follow up upstream and see if we can get the change made to ReadStat.

**Comment by hadley** [comment]
Resubmitted 😄

**Comment by hadley** [comment]
Gah, one last thing:

```
* checking C++ specification ... NOTE
  Specified C++11: please drop specification unless essential
```

I think it's ok to just delete this from the DESCRIPTION?

**Comment by gorcha** [comment]
Always one last thing!

Yep that should do it, I've seen some mention of this coming from Makevars but the DESCRIPTION seems to be the only place we mention it. Have updated, hopefully that's it!

**Comment by hadley** [comment]
And now on CRAN 🥳
