### ISSUE TITLE
Feature request: Generate dataframe of variable names and labels

### ISSUE THREAD

**Issue by dougj892** [tidyverse/haven#722]
I often work with Stata datasets containing household survey data. These datasets often contain thousands of variables so typically the first thing I do before doing any analysis is to generate a dataframe with one column for all variable names and one column for all variable labels so I can easily search for which variables to use in the analysis. It would be awesome if haven included a simple helper function to do this. And happy to submit a pull request for this myself if this would be useful for others.

**Comment by larmarange** [comment]
You could have a look at labelled::look_for()

See https://larmarange.github.io/labelled/articles/look_for.html

**Comment by dougj892** [comment]
Oh cool! Thanks for the tip. That is exactly what I am looking for.

**Comment by gorcha** [comment]
Thanks @larmarange!
